---
title: "Membran og ion parameter"
author: "Steffen"
date: "18/3/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(include = FALSE)
library(plyr)
library(dplyr)
library(tidyr)
library(ggplot2)
library(visdat)
library(GGally)
library(Hmisc)
library(DMwR2)
library(data.table)
library(mltools)
library(ggfortify)
library(ggiraphExtra)
library(coronavirus)
library(lubridate)
library(plotly)
#library(naniar)
library(readxl)
require(readr)
library(zoo)
library(latex2exp)
library(fs)
library(plyr)
library(matrixStats)
library(haven)
library(sjmisc)
require(gridExtra)
require(ggpubr)

colors = c(
  '#1f77b4',  # muted blue
  '#ff7f0e',  # safety orange
  '#2ca02c',  # cooked asparagus green
  '#d62728',  # brick red
  '#9467bd',  # muted purple
  '#8c564b',  # chestnut brown
  '#e377c2',  # raspberry yogurt pink
  '#7f7f7f',  # middle gray
  '#bcbd22',  # curry yellow-green
  '#17becf'   # blue-teal
)
```


```{r Basic ion information}

ion_data = data.frame(
  ion = c("Na", "Cl", "SO4", "SiO2","Ca","HCO3"),
  Mw=c(23,35,96,60,40,61),
  molar_con = c(50.1, 76.4, 160, NA,119,NA),# Molær konduktivitet[S*cm^2*mol^-1]
 stokes=c(1.84,1.21,2.3,NA,3.1,NA)*0.1,
 pauling=c(0.95,1.81,2.9,NA,0.99,NA)*0.1,
 hydrated=c(3.58,3.32,3.82,NA,3.12,NA)*0.1,
 z=c(1,-1,-2,-1,2,-1)
)


```

```{r steric, echo=FALSE, message=FALSE, warning=FALSE}
radius_navne = c("stokes","pauling","hydrated")

df_steric=data.frame( 
  rp=double(),
  Na=double(),
  Cl=double(),
  SO4=double(),
  SiO2=double(),
  Ca=double(),
  HCO3=double()
)
store_df_steric = data.frame()
for (j in 1:3) {
  radius=radius_navne[j]
  radii = ion_data%>%select(c(ion,radius))

for (i in 1:100) {
 rper = seq(0.5,1,0.005)
 rp= rper[i]
 
 
  steric=(1-(radii[,2]/rp))^2
  df_steric[i,2:7]=steric
  df_steric[i,1]=rp
}
store_df_steric = rbind(store_df_steric,df_steric %>%mutate(type = radius_navne[j]))
}
store_df_steric = store_df_steric%>%mutate(ex = "Steric")
steric.long = store_df_steric%>%filter(type=="stokes") %>% 
  gather(key,value,Na,Cl,SO4,SiO2,Ca,HCO3)
level_order = c('Na','Cl','SO4','SiO2','Ca','HCO3')

ggplot(steric.long,aes(x=rp,y=value,color=factor(key,level=level_order)))+geom_line()+
  scale_color_brewer(palette="Set1",labels = level_order)+
  theme_bw()+labs(y = "Phi S", x = "rp [nm]", color = "Ion")


steric.long = store_df_steric%>%filter(type=="pauling") %>% 
  gather(key,value,Na,Cl,SO4,SiO2,Ca,HCO3)
ggplot(steric.long,aes(x=rp,y=value,color=factor(key,level=level_order)))+geom_line()+
  scale_color_brewer(palette="Set1",labels = level_order)+
  theme_bw()+labs(y = "Phi S", x = "rp [nm]", color = "Ion")


steric.long = store_df_steric%>%filter(type=="hydrated") %>% 
  gather(key,value,Na,Cl,SO4,SiO2,Ca,HCO3)
ggplot(steric.long,aes(x=rp,y=value,color=factor(key,level=level_order)))+geom_line()+
  scale_color_brewer(palette="Set1",labels = level_order)+
  theme_bw()+labs(y = "Phi S", x = "rp [nm]", color = "Ion")

```

```{r Dielectric exclusion, message=FALSE, warning=FALSE}


radius_navne = c("stokes","pauling","hydrated")
E_b = 78.4
E_la = 31
delta = 0.28 #nm
e = 1.602*10^-19 #C
E_0 = 8.85*10^-12 #F m^-1
k_B = 1.386*10^-23
Temp=25
Temp=Temp+273.15
  
  
df_DE=data.frame( 
  rp=double(),
  Na=double(),
  Cl=double(),
  SO4=double(),
  SiO2=double(),
  Ca=double(),
  HCO3=double()
)
store_df_DE = data.frame()
for (j in 1:3) {
  radius=radius_navne[j]
  radii = ion_data%>%select(c(ion,radius,z))

for (i in 1:500) {
 rper = seq(0.5,3,0.005)
 rp= rper[i]
 
 


  E_p=E_la+(E_b-E_la)*(1-(delta/rp))^2
  dW = (radii$z^2*e^2)/(8*pi*E_0*radii[,2]*10^-9)*(1/E_p-1/E_b)
  phi_DE = exp(-dW/(k_B*Temp))
  
  df_DE[i,2:7]=phi_DE
  df_DE[i,1]=rp
}
store_df_DE = rbind(store_df_DE,df_DE %>%mutate(type = radius_navne[j]))
}

store_df_DE = store_df_DE%>%mutate(ex = "Dielectric")

level_order = c('Na','Cl','SO4','SiO2','Ca','HCO3')
DE.long = store_df_DE%>% 
  gather(key,value,Na,Cl,SO4,SiO2,Ca,HCO3)

ggplot(DE.long%>%filter(type=="stokes"),aes(x=rp,y=value,color=factor(key,level=level_order)))+geom_line()+
  scale_color_brewer(palette="Set1",labels = level_order)+
  theme_bw()+labs(y = "Phi DE", x = "rp [nm]", color = "Ion")+ylim(c(0,1))

ggplot(DE.long%>%filter(type=="pauling"),aes(x=rp,y=value,color=factor(key,level=level_order)))+geom_line()+
  scale_color_brewer(palette="Set1",labels = level_order)+
  theme_bw()+labs(y = "Phi DE", x = "rp [nm]", color = "Ion")+ylim(c(0,1))

ggplot(DE.long%>%filter(type=="hydrated"),aes(x=rp,y=value,color=factor(key,level=level_order)))+geom_line()+
  scale_color_brewer(palette="Set1",labels = level_order)+
  theme_bw()+labs(y = "Phi DE", x = "rp [nm]", color = "Ion")+ylim(c(0,1))


```

```{r nye plot}

r=0.5

DSPM = rbind(store_df_steric,store_df_DE)
DSPM.long2 = DSPM%>%filter(rp==r&ex=="Dielectric")%>%gather(key="key",value="value",Na,Cl,SO4,Ca)
DSPM.long = DSPM%>%filter(rp==r&ex=="Steric")%>%gather(key="key",value="value",Na,Cl,SO4,Ca)

ggplotly(ggplot(DSPM.long, aes(fill=type, y=value, x=key)) + 
    geom_bar(position="dodge", stat="identity")+labs(title="Steric exclusion for r = 0.5 nm",
        x ="Ion", y = "Exclusion factor"))



ggplotly(ggplot(DSPM.long2, aes(fill=type, y=value, x=key)) + 
    geom_bar(position="dodge", stat="identity")+labs(title="Dielectric exclusion for r = 0.5 nm",
        x ="Ion", y = "Exclusion factor")+scale_fill_manual(values=colors[8:10]))


ggplotly(ggplot(DSPM.long2, aes(fill=key, y=value, x=type))+ 
    geom_col(position="dodge",alpha=0.8)+labs(title="Dielectric exclusion for r = 0.5 nm",
        x ="Ion", y = "Exclusion factor")+scale_fill_manual(values=colors[1:4]))

```


```{r template}
library(deSolve)
library(shiny)
library(shinyWidgets)
library(plotly)

ui <- fluidPage(
  sidebarLayout(
    sidebarPanel(
      fluidRow(
        column(width=6,
               sliderInput("a", "Coef 1",0, 5, 1, step=0.2),
               sliderInput("b", "Coef 2", 0, 5, 1, step=0.2)
        )
      )
    ),
    mainPanel(
      selectInput("Var",
                  label = "Choose variable to plot:",
                  choices = c("First"="U", "Second"="V"), 
                  selected = c("U")
      ),
      
      plotlyOutput("plot0")
      
    )
  )
)

LV<-function(t,y,p){ # define Lotka-Volterra system
  with(as.list(p),{
    z<-rep(0,2)
    z[1]<-y[1]-a*y[1]*y[2]
    z[2]<-b*y[1]*y[2]-y[2]
    
    return(list(z))
  })
}

Run_LV<-function(a,b){ # run the simmulation
  t <- seq(from=0, to=10, by=0.1)
  y0<-c(1.5,0.7) # initial condition
  para<-c(list("a"=a,"b"=b)) # values of parameters
  
  out <- ode(y=y0, times=t, func=LV, parms=para ,method="ode45")
  
  return(list("out"=out))
}

server <- function(input, output) {
  
  solution <- reactive({
    sim<-Run_LV(input$a,input$b)
    sim$out
  })
  output$plot0<-renderPlotly({
    sol <- req(solution())
    xvar<-sol[,1] # time
    if(input$Var=="U"){
      yvar<-sol[,2] # will plot U component
    }else{
      yvar<-sol[,3] # will plot V component
    }
    
    data<- data.frame(xvar,yvar)
    plot_ly(data,x=~xvar, y=~yvar, type = 'scatter', mode = 'lines')
  })
  
}
shinyApp(ui = ui, server = server)
```


```{r Interactive}
library(deSolve)
library(shiny)
library(shinyWidgets)
library(plotly)

ui <- fluidPage(
  sidebarLayout(
    sidebarPanel(
      fluidRow(
        column(width=6,
               sliderInput("r", "Pore Radius",0.5, 2, 0.5, step=0.005)
        )
      )
    ),
    mainPanel(
      selectInput("Var",
                  label = "Choose Exclsion factor to plot:",
                  choices = c("Steric"="U", "Dielectric"="V","Steric2"="X","Dielectric2"="W"), 
                  selected = c("U")
      ),
      
      plotlyOutput("plot0")
      
    )
  )
)

ion_data = data.frame(
  ion = c("Na", "Cl", "SO4", "SiO2","Ca","HCO3"),
  Mw=c(23,35,96,60,40,61),
  molar_con = c(50.1, 76.4, 160, NA,119,NA),# Molær konduktivitet[S*cm^2*mol^-1]
 stokes=c(1.84,1.21,2.3,NA,3.1,NA)*0.1,
 pauling=c(0.95,1.81,2.9,NA,0.99,NA)*0.1,
 hydrated=c(3.58,3.32,3.82,NA,3.12,NA)*0.1,
 z=c(1,-1,-2,-1,2,-1)
)

LV <- function(r) {
  radius_navne = c("stokes", "pauling", "hydrated")
  df_steric = data.frame(
    rp = double(),
    Na = double(),
    Cl = double(),
    SO4 = double(),
    SiO2 = double(),
    Ca = double(),
    HCO3 = double()
  )
  store_df_steric = data.frame()
  for (j in 1:3) {
    radius = radius_navne[j]
    radii = ion_data %>% select(c(ion, radius))
    rp = r
    
    
    steric = (1 - (radii[, 2] / rp)) ^ 2
    df_steric[1, 2:7] = steric
    df_steric[1, 1] = rp
    store_df_steric = rbind(store_df_steric, df_steric %>% mutate(type = radius_navne[j]))
  }
  
  store_df_steric = store_df_steric %>% mutate(ex = "Steric")

return(store_df_steric)
}

LV2 <- function(r){
  
radius_navne = c("stokes","pauling","hydrated")
E_b = 78.4
E_la = 31
delta = 0.28 #nm
e = 1.602*10^-19 #C
E_0 = 8.85*10^-12 #F m^-1
k_B = 1.386*10^-23
Temp=25
Temp=Temp+273.15
  
df_DE=data.frame( 
  rp=double(),
  Na=double(),
  Cl=double(),
  SO4=double(),
  SiO2=double(),
  Ca=double(),
  HCO3=double()
)
store_df_DE = data.frame()
for (j in 1:3) {
  radius=radius_navne[j]
  radii = ion_data%>%select(c(ion,radius,z))


 rp= r
 
 


  E_p=E_la+(E_b-E_la)*(1-(delta/rp))^2
  dW = (radii$z^2*e^2)/(8*pi*E_0*radii[,2]*10^-9)*(1/E_p-1/E_b)
  phi_DE = exp(-dW/(k_B*Temp))
  
  df_DE[1,2:7]=phi_DE
  df_DE[1,1]=rp
store_df_DE = rbind(store_df_DE,df_DE %>%mutate(type = radius_navne[j]))
}
store_df_DE = store_df_DE%>%mutate(ex = "Dielectric")
return(store_df_DE)
}



server <- function(input, output, session) {
  solution <- reactive({
    sim <- rbind(LV(input$r), LV2(input$r))
    
  })
  
  output$plot0 <- renderPlotly({
    sol <- req(solution())
    if (input$Var == "U") {
      ex_var = "Steric" # will plot steric exclusin
      plt = aes(fill = type, y = value, x = key)
    } else if (input$Var == "V") {
      ex_var = "Dielectric" # will plot DE
      plt = aes(fill = type, y = value, x = key)
    } else if (input$Var == "W") {
      #plot DE but radius grouped
      ex_var = "Dielectric"
      plt = aes(fill = key, y = value, x = type)
    } else if(input$Var =="X"){
      ex_var = "Steric"
      plt = aes(fill = key, y = value, x = type)
    }
    Data = sol %>% filter(ex == ex_var)
    Data = Data %>% gather(key, value, Na, Cl, SO4, Ca)
    str_r = as.character(input$r)
    ggplotly(
      ggplot(Data, plt) +
        geom_bar(
          position = "dodge",
          alpha = 0.8,
          stat = "identity"
        ) + labs(
          title = paste(ex_var, "exclusion w/ r =",  str_r, "nm"),
          x = "Ion",
          y = "Exclusion factor"
        ) + ylim(c(0, 1))
     + scale_fill_manual(values = colors))
  })
  
}
shinyApp(ui = ui, server = server)
```


