---
title: "ICR_phase_2"
date: "25/3/2022"
output: 
  html_document:
    toc: true
    toc_depth: 3
editor_options: 
  markdown: 
    wrap: sentence

---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,warning=F,message=F)
#knitr::opts_chunk$set(include = FALSE)
library(plyr)
library(dplyr)
library(tidyr)
library(ggplot2)
library(visdat)
library(GGally)
library(Hmisc)
library(DMwR2)
library(data.table)
library(mltools)
library(ggfortify)
library(ggiraphExtra)
library(coronavirus)
library(lubridate)
library(plotly)
#library(naniar)
library(readxl)
require(readr)
library(zoo)
library(latex2exp)
library(fs)
library(plyr)
library(matrixStats)
library(haven)
library(sjmisc)
require(gridExtra)
require(ggpubr)

colors = c(
  '#1f77b4',  # muted blue
  '#ff7f0e',  # safety orange
  '#2ca02c',  # cooked asparagus green
  '#d62728',  # brick red
  '#9467bd',  # muted purple
  '#8c564b',  # chestnut brown
  '#e377c2',  # raspberry yogurt pink
  '#7f7f7f',  # middle gray
  '#bcbd22',  # curry yellow-green
  '#17becf'   # blue-teal
)
```
## Results {.tabset}

### PLC data



```{R ID: 4 PLC data , echo=FALSE, message=FALSE}

CWF_ICR_1 = read_delim("data/ICR_1_batch_24_01_22.csv",delim = "\t", escape_double = FALSE, 
                  trim_ws = TRUE, skip = 5) #Hente data og få det til passe ned i en tabel
#str(CWF)
dat_ICR_1 = as.data.frame(CWF_ICR_1) #Ændrer strukturen af dataen til noget vi kan arbejde med
old_names=colnames(CWF_ICR_1) #Vi finder de latterlige navne kolonnerne i dataen har 
new_names=c("time","level","con0201","pH0201","con0301","flow0301",
            "p0301","p0302","p0401","flow0401","p0501","con0501",
            "temp0501","p0601","temp0601","16","17","18","19","20",
            "21","pmp0201","pmp0301","pmp0401","pmp0501","flow_avg0301",
            "p_avg0301","p_avg0302","p_avg0401","flow_avg0401",
            "p_avg0501","FT0302","weight0302","flow0501","weight0501","36","pH0301",
            "pH0501","con0302","40") #Vi finder på nogle lidt bedre nogle
dat_ICR_1 = dat_ICR_1 %>% rename_at(vars(old_names),~new_names) #Vi ændrer navnene til de nye
dat_ICR_1$time = dmy_hms(dat_ICR_1$time)#Vi ændrer formatet af 'dato' kolonnen til et standard format for tid og datoer istedet for at det bare er noget tekst
#str(dat)

dat_ICR_1=dat_ICR_1[-c(1:19968),]


### Finde t=0 (fosøgsstart = der hvor flow er over 16 mL/min)
flow_boolean = dat_ICR_1$flow0501>1&dat_ICR_1$flow0501<25
start_tid = min(which(flow_boolean))
dat_ICR_1=dat_ICR_1[-c(1:start_tid),]
flow_boolean_slut = dat_ICR_1$flow0501<1
slut_tid = min(which(flow_boolean_slut))
dat_ICR_1=dat_ICR_1[-c(slut_tid:(nrow(dat_ICR_1)) ),]
### Tid i s fra forsøgs start
dat_ICR_1 = dat_ICR_1%>%
   mutate(sek=(
           as.numeric(as.POSIXct(dat_ICR_1$time))-as.numeric(dat_ICR_1$time[1], format='%Y-%m-%d %H:%M:%S'))
                )  


### TMP ###
dat_ICR_1 = dat_ICR_1 %>% mutate(TMP=(p_avg0301+p_avg0302)/2-p_avg0501)

dat_ICR_1 %>%
  plot_ly(x=~(sek)/3600,
          y=~TMP,
          name="TMP",
          type='scatter',
          mode='lines',
          line=list(color= colors[1]))%>%
  add_lines(x=~sek/3600,
          y=~pH0201,
          name=' pH',
          type='scatter',
          mode='line',
          line=list(color=colors[2]))%>%
add_lines(x=~sek/3600,
          y=~con0301,
          name='Conductivity',
          type='scatter',
          mode='line',
      line=list(color=colors[3]))%>%
  layout(title="PLC data ID: 4 ",
         legend=list(x=0.9,y=0.9),
         yaxis=list(title="value", range=c(NA,NA)),
         xaxis=list(title="Time [h]",range=c(0,8))
         ) 

```
```{R ID: 4 extra PLC plots , include=FALSE, message=FALSE}

dat_ICR_1 %>%#dplyr arbejder indenfor 'dat' data framen
  mutate(TMP=(p_avg0301+p_avg0302)/2-p_avg0501)%>%#Her regner vi TMP, som dplyr husker nu er en del af den data
  mutate(TMP_slid=rollapply(TMP,100,mean,align="right",fill=NA))%>%#Nu tager vi et glidende gennemsnit
  plot_ly(x=~(sek)/3600,
          y=~p_avg0301,
          name="Pressure before membrane",
          color='#1f77b4',
          type='scatter',
          mode='lines')%>%
  add_lines(y=~p_avg0302,
            name='Pressure after membrane',
            color='#E41317')%>%
  add_lines(y=~TMP_slid,
            name='TMP',
            color='#forestgreen')%>%
  layout(title="ICR batch 1 Pressure",
         legend=list(x=0.7,y=0.2),
         yaxis=list(title="Pressure [bar]"),
         xaxis=list(title="Time [h]")) #Her plottet de to tryk på feed siden plus et TMP

dat_ICR_1 %>%#dplyr arbejder indenfor 'dat' data framen
    plot_ly(x=~(sek)/3600,
          y=~con0301,
          name="Feed",
          color='#1f77b4',
          type='scatter',
          mode='lines')%>%
  add_lines(y=~con0501,
            name='Permeate',
            color='#E41317')%>%
  add_lines(y=~(1-(con0501/con0301))*100,
            name='Rejection',
            color='#forestgreen')%>%
  layout(title="Conductivity ICR",
         legend=list(x=0.7,y=0.2),
         yaxis=list(title="Conductivity"),
         xaxis=list(title="Time [h]")) #Her plottet de to tryk på feed siden plus et TMP


fig_pH <- plot_ly(data=dat_ICR_1,x=~sek/3600,
          y=~pH0201,
          type='scatter',mode='lines+markers',
          colors=colors[1], name = "pH ") %>%
    layout( yaxis=list(title="pH",range=c(8.5,10)),
         xaxis=list(title="Time [h]"))
fig_pH  

```
```{r ID: 5 PLC data , echo=FALSE}

ICR_ID_5_raw = read_delim("data/ICR_phase_2_pH_7.7_15-03-2022 000000.csv",delim = ",", escape_double = FALSE, trim_ws = TRUE, skip = 3) #Hente data og få det til passe ned i en tabel

ICR_ID_5 = as.data.frame(ICR_ID_5_raw) #Ændrer strukturen af dataen til noget vi kan arbejde med
old_names=colnames(ICR_ID_5_raw) #Vi finder de gamle navne kolonnerne i dataen har 
new_names=c("Time","con0201","pH0201","con0301","flow0301",
            "p0301","p0302","p0501","con0501",
            "temp0501","p0601","temp0601","CV0301","pmp0301","pmp0501","flow_avg0301",
            "p_avg0301","p_avg0302",
            "p_avg0501","FT0302","weight0302","flow0501","weight0501","pH0301",
            "pH0501") #Vi finder på nogle lidt bedre nogle
ICR_ID_5 = ICR_ID_5 %>% rename_at(vars(old_names),~new_names) #Vi ændrer navnene til de nye
ICR_ID_5$Time = dmy_hms(ICR_ID_5$Time)#Vi ændrer formatet af 'dato' kolonnen til et standard format for tid og datoer istedet for at det bare er noget tekst
ICR_ID_5=ICR_ID_5[-c(1:28860),]

### Finde t=0 (fosøgsstart = der hvor flow er over 16 mL/min)
flow_boolean = ICR_ID_5$flow0501>16&ICR_ID_5$flow0501<30
start_tid = min(which(flow_boolean))
ICR_ID_5=ICR_ID_5[-c(1:start_tid),]
flow_boolean_slut = ICR_ID_5$flow0501<1
slut_tid = min(which(flow_boolean_slut))
ICR_ID_5=ICR_ID_5[-c(slut_tid:(nrow(ICR_ID_5)) ),]
### Tid i s fra forsøgs start
ICR_ID_5 = ICR_ID_5%>%
   mutate(sek=(
           as.numeric(as.POSIXct(ICR_ID_5$Time))-as.numeric(ICR_ID_5$Time[1], format='%Y-%m-%d %H:%M:%S'))
                )  
### TMP ###
ICR_ID_5 = ICR_ID_5 %>% mutate(TMP=(p_avg0301+p_avg0302)/2-p_avg0501)


ICR_ID_5 %>%
  plot_ly(x=~(sek)/3600,
          y=~TMP,
          name="TMP",
          type='scatter',
          mode='lines',
          line=list(color= colors[1]))%>%
  add_lines(x=~sek/3600,
          y=~pH0201,
          name=' pH',
          type='scatter',
          mode='line',
          line=list(color=colors[2]))%>%
add_lines(x=~sek/3600,
          y=~con0301,
          name='Conductivity',
          type='scatter',
          mode='line',
      line=list(color=colors[3]))%>%
  layout(title="PLC data ID: 5 ",
         legend=list(x=0.9,y=0.9),
         yaxis=list(title="value", range=c(NA,NA)),
         xaxis=list(title="Time [h]",range=c(0,8))
         ) 

```
```{r ID: 6 PLC data , echo=FALSE}

ICR_vol2_A_raw = read_delim("data/ICR_volume2_A_16-03-2022 084022.csv",delim = ",", escape_double = FALSE, trim_ws = TRUE, skip = 3) #Hente data og få det til passe ned i en tabel

ICR_vol2_A = as.data.frame(ICR_vol2_A_raw) #Ændrer strukturen af dataen til noget vi kan arbejde med
old_names=colnames(ICR_vol2_A_raw) #Vi finder de gamle navne kolonnerne i dataen har 
new_names=c("Time","con0201","pH0201","con0301","flow0301",
            "p0301","p0302","p0501","con0501",
            "temp0501","p0601","temp0601","CV0301","pmp0301","pmp0501","flow_avg0301",
            "p_avg0301","p_avg0302",
            "p_avg0501","FT0302","weight0302","flow0501","weight0501","pH0301",
            "pH0501") #Vi finder på nogle lidt bedre nogle
ICR_vol2_A = ICR_vol2_A %>% rename_at(vars(old_names),~new_names) #Vi ændrer navnene til de nye
ICR_vol2_A$Time = dmy_hms(ICR_vol2_A$Time)#Vi ændrer formatet af 'dato' kolonnen til et standard format for tid og datoer istedet for at det bare er noget tekst


### Finde t=0 (fosøgsstart = der hvor flow er over 16 mL/min)
flow_boolean = ICR_vol2_A$flow0501>16&ICR_vol2_A$flow0501<25
start_tid = min(which(flow_boolean))
ICR_vol2_A=ICR_vol2_A[-c(1:start_tid),]
flow_boolean_slut = ICR_vol2_A$flow0501<1
slut_tid = min(which(flow_boolean_slut))
ICR_vol2_A=ICR_vol2_A[-c(slut_tid:(nrow(ICR_vol2_A)) ),]
### Tid i s fra forsøgs start
ICR_vol2_A = ICR_vol2_A%>%
   mutate(sek=(
           as.numeric(as.POSIXct(ICR_vol2_A$Time))-as.numeric(ICR_vol2_A$Time[1], format='%Y-%m-%d %H:%M:%S'))
                )  

### TMP ###
ICR_vol2_A = ICR_vol2_A %>% mutate(TMP=(p_avg0301+p_avg0302)/2-p_avg0501)



ICR_vol2_A %>%
  plot_ly(x=~(sek)/3600,
          y=~TMP,
          name="TMP",
          type='scatter',
          mode='lines',
          line=list(color= colors[1]))%>%
  add_lines(x=~sek/3600,
          y=~pH0201,
          name=' pH',
          type='scatter',
          mode='line',
          line=list(color=colors[2]))%>%
add_lines(x=~sek/3600,
          y=~con0301,
          name='Conductivity',
          type='scatter',
          mode='line',
      line=list(color=colors[3]))%>%
  layout(title="PLC data ID: 6 ",
         legend=list(x=0.9,y=0.9),
         yaxis=list(title="value", range=c(NA,NA)),
         xaxis=list(title="Time [h]",range=c(0,8))
         ) 


```
```{r ID: 7 PLC data, echo=FALSE}



ICR_vol2_B_raw = read_delim("data/ICR_volume2_B_17-03-2022 084934.csv",delim = ",", escape_double = FALSE, trim_ws = TRUE, skip = 3) #Hente data og få det til passe ned i en tabel

ICR_vol2_B = as.data.frame(ICR_vol2_B_raw) #Ændrer strukturen af dataen til noget vi kan arbejde med
old_names=colnames(ICR_vol2_B_raw) #Vi finder de gamle navne kolonnerne i dataen har 
new_names=c("Time","con0201","pH0201","con0301","flow0301",
            "p0301","p0302","p0501","con0501",
            "temp0501","p0601","temp0601","CV0301","pmp0301","pmp0501","flow_avg0301",
            "p_avg0301","p_avg0302",
            "p_avg0501","FT0302","weight0302","flow0501","weight0501","pH0301",
            "pH0501") #Vi finder på nogle lidt bedre nogle
ICR_vol2_B = ICR_vol2_B %>% rename_at(vars(old_names),~new_names) #Vi ændrer navnene til de nye
ICR_vol2_B$Time = dmy_hms(ICR_vol2_B$Time)#Vi ændrer formatet af 'dato' kolonnen til et standard format for tid og datoer istedet for at det bare er noget tekst




### Finde t=0 (fosøgsstart = der hvor flow er over 16 mL/min)
 flow_boolean = ICR_vol2_B$flow0501>16&ICR_vol2_B$flow0501<25
 start_tid = min(which(flow_boolean))
 ICR_vol2_B=ICR_vol2_B[-c(1:start_tid),]
 #flow_boolean_slut = ICR_vol2_B$flow0501<1
# slut_tid = min(which(flow_boolean_slut))
 #ICR_vol2_B=ICR_vol2_B[-c(slut_tid:(nrow(ICR_vol2_B)) ),]
### Tid i s fra forsøgs start
ICR_vol2_B = ICR_vol2_B%>%
   mutate(sek=(
           as.numeric(as.POSIXct(ICR_vol2_B$Time))-as.numeric(ICR_vol2_B$Time[1], format='%Y-%m-%d %H:%M:%S'))
                )  
### TMP ###
ICR_vol2_B = ICR_vol2_B %>% mutate(TMP=(p_avg0301+p_avg0302)/2-p_avg0501)


ICR_vol2_B %>%
  plot_ly(x=~Time,
          y=~TMP,
          name="TMP",
          type='scatter',
          mode='lines',
          line=list(color= colors[1]))%>%
  add_lines(x=~Time,
          y=~pH0201,
          name=' pH',
          type='scatter',
          mode='line',
          line=list(color=colors[2]))%>%
add_lines(x=~Time,
          y=~con0301,
          name='Conductivity',
          type='scatter',
          mode='line',
      line=list(color=colors[3]))%>%
  layout(title="PLC data ID: 7",
         legend=list(x=0.9,y=0.9),
         yaxis=list(title="value", range=c(NA,NA)),
         xaxis=list(title="Time [h]",range=c(NA,NA))
         ) 

``` 



### Rejection


```{R ID_4 import IC_data, echo=FALSE, message=FALSE}

Cl_IC_data <- read_excel("data/ICR/IC_data_ICR_udvalgtdata_igen.xlsx")

old_names_IC=colnames(Cl_IC_data) #Vi finder de latterlige navne kolonnerne i dataen har 
new_names_IC=c("time","Stream","Dilution","Cl_1_mg/L","Cl_2_mg/L") #Vi finder på nogle lidt bedre nogle
Cl_IC_data = Cl_IC_data %>% rename_at(vars(old_names_IC),~new_names_IC) #Vi ændrer navnene til de nye
Cl_IC_data <- as.data.frame(Cl_IC_data)
#noget med gennemsnit. 

Cl_IC_data <-Cl_IC_data%>%mutate(avg_mgL=(rowMeans(Cl_IC_data[,c("Cl_1_mg/L","Cl_2_mg/L")],na.rm=TRUE)))%>%
                          mutate(std_mgL=(rowSds(as.matrix(Cl_IC_data[,c("Cl_1_mg/L","Cl_2_mg/L")],na.rm=TRUE))))%>%
                          mutate(Std_p=((std_mgL/avg_mgL)))



SO4_IC_data <- read_excel("data/ICR/IC_data_ICR_udvalgtdata_igen.xlsx",2)

old_names_IC=colnames(SO4_IC_data) #Vi finder de latterlige navne kolonnerne i dataen har 
new_names_IC=c("time","Stream","Dilution","SO4_1_mg/L","SO4_2_mg/L") #Vi finder på nogle lidt bedre nogle
SO4_IC_data = SO4_IC_data %>% rename_at(vars(old_names_IC),~new_names_IC) #Vi ændrer navnene til de nye
SO4_IC_data <- as.data.frame(SO4_IC_data)
#noget med gennemsnit. 

SO4_IC_data <-SO4_IC_data%>%mutate(avg_mgL=(rowMeans(SO4_IC_data[,c("SO4_1_mg/L","SO4_2_mg/L")],na.rm=TRUE)))%>%
                          mutate(std_mgL=(rowSds(as.matrix(SO4_IC_data[,c("SO4_1_mg/L","SO4_2_mg/L")],na.rm=TRUE))))%>%
                          mutate(Std_p=((std_mgL/avg_mgL)))
SO4_IC_data <- SO4_IC_data[c(1:35),]


Na_IC_data <- read_excel("data/ICR/IC_data_ICR_udvalgtdata_igen.xlsx",3)

old_names_IC=colnames(Na_IC_data) #Vi finder de latterlige navne kolonnerne i dataen har 
new_names_IC=c("time","Stream","Dilution","Na_1_mg/L","Na_2_mg/L") #Vi finder på nogle lidt bedre nogle
Na_IC_data = Na_IC_data %>% rename_at(vars(old_names_IC),~new_names_IC) #Vi ændrer navnene til de nye
Na_IC_data <- as.data.frame(Na_IC_data)
#noget med gennemsnit. 

Na_IC_data <-Na_IC_data%>%mutate(avg_mgL=(rowMeans(Na_IC_data[,c("Na_1_mg/L","Na_2_mg/L")],na.rm=TRUE)))%>%
                          mutate(std_mgL=(rowSds(as.matrix(Na_IC_data[,c("Na_1_mg/L","Na_2_mg/L")],na.rm=TRUE))))%>%
                          mutate(Std_p=((std_mgL/avg_mgL)))

Ca_IC_data <- read_excel("data/ICR/IC_data_ICR_udvalgtdata_igen.xlsx",4)

old_names_IC=colnames(Ca_IC_data) #Vi finder de latterlige navne kolonnerne i dataen har 
new_names_IC=c("time","Stream","Dilution","Ca_1_mg/L","Ca_2_mg/L") #Vi finder på nogle lidt bedre nogle
Ca_IC_data = Ca_IC_data %>% rename_at(vars(old_names_IC),~new_names_IC) #Vi ændrer navnene til de nye
Ca_IC_data <- as.data.frame(Ca_IC_data)
#noget med gennemsnit. 

Ca_IC_data <-Ca_IC_data%>%mutate(avg_mgL=(rowMeans(Ca_IC_data[,c("Ca_1_mg/L","Ca_2_mg/L")],na.rm=TRUE)))%>%
                          mutate(std_mgL=(rowSds(as.matrix(Ca_IC_data[,c("Ca_1_mg/L","Ca_2_mg/L")],na.rm=TRUE))))%>%
                          mutate(Std_p=((std_mgL/avg_mgL)))

#data fra SiO2 

SiO2_IC_data <- read_excel("data/ICR/IC_data_ICR_udvalgtdata_igen.xlsx",6)

old_names_IC=colnames(SiO2_IC_data) #Vi finder de latterlige navne kolonnerne i dataen har 
new_names_IC=c("time","Stream","SiO2_mgL") #Vi finder på nogle lidt bedre nogle
SiO2_IC_data = SiO2_IC_data %>% rename_at(vars(old_names_IC),~new_names_IC) #Vi ændrer navnene til de nye
SiO2_IC_data <- as.data.frame(SiO2_IC_data)
#noget med gennemsnit. 
SiO2_IC_data$std=2


```

```{R ID: 4 plot af conc , include=FALSE, message=FALSE}

Mw_Cl=35.45
Mw_Na=22.99
Mw_Ca=40.078
Mw_SO4=96.06
Mw_SiO2=60.08


fig_Cl <- Cl_IC_data %>% filter(Stream %in% c("Feed","Permeate"))%>%  
  plot_ly(x=~time/60,
          y=~avg_mgL/Mw_Cl,
          error_y = list(array = ~std_mgL/Mw_Cl),
          color = ~Stream,
          colors=c(colors[1],colors[2]),
        type='scatter',mode='lines+markers')%>%
layout( yaxis=list(title=" Cl mg/L", range=c(0,6)),
         xaxis=list(title="Time [h]"))
fig_Cl


fig_SO4 <- SO4_IC_data %>% filter(Stream %in% c("Feed","Permeate"))%>%  
  plot_ly(x=~time/60,
          y=~avg_mgL/Mw_SO4,
          error_y = list(array = ~std_mgL/Mw_SO4),
          color = ~Stream,
          colors=c(colors[1],colors[2]),
        type='scatter',mode='lines+markers')%>%
layout( yaxis=list(title=" SO4 mg/L", range=c(0,18)),
         xaxis=list(title="Time [h]"))
fig_SO4

fig_Na <- Na_IC_data %>% filter(Stream %in% c("Feed","Permeate"))%>%  
  plot_ly(x=~time/60,
          y=~avg_mgL/Mw_Na,
          error_y = list(array = ~std_mgL/Mw_Na),
          color = ~Stream,
          colors=c(colors[1],colors[2]),
        type='scatter',mode='lines+markers')%>%
layout( yaxis=list(title=" Na mg/L", range=c(0,60)),
         xaxis=list(title="Time [h]"))
fig_Na

fig_Ca <- Ca_IC_data %>% filter(Stream %in% c("Feed","Permeate"))%>%  
  plot_ly(x=~time/60,
          y=~avg_mgL/Mw_Ca,
          error_y = list(array = ~std_mgL/Mw_Ca),
          color = ~Stream,
          colors=c(colors[1],colors[2]),
        type='scatter',mode='lines+markers')%>%
layout( yaxis=list(title=" Ca mg/L", range=c(0,0.6)),
         xaxis=list(title="Time [h]"))
fig_Ca

fig_SiO2 <- SiO2_IC_data %>% filter(Stream %in% c("Feed","Permeate"))%>%  
        plot_ly(x=~time/60,
          y=~SiO2_mgL/Mw_SiO2,
         # error_y = list(array = ~std_mgL/Mw_SiO2),
          color = ~Stream,
         colors=c(colors[1],colors[2]),
        type='scatter',mode='lines+markers')%>%
layout( yaxis=list(title=" SiO2 mg/L", range=c(0,1.8)),
         xaxis=list(title="Time [h]"))
fig_SiO2

      

```

ID:4 plottet med error bars etc. 

```{R ID: 4 rejection , echo=FALSE, message=FALSE}


#Cl
Cl_feed <- Cl_IC_data%>%filter(Stream=="Feed")
Cl_perm <- Cl_IC_data%>%filter(Stream=="Permeate")
Cl_rej <- (1-(Cl_perm$avg_mgL/Cl_feed$avg_mgL[c(2:16)]))*100
Cl_rej_std_p <- (Cl_perm$Std_p+Cl_feed$Std_p[c(2:16)])
Cl_rej_std <- abs(Cl_rej*Cl_rej_std_p)

#SO4
SO4_feed <- SO4_IC_data%>%filter(Stream=="Feed")
SO4_perm <- SO4_IC_data%>%filter(Stream=="Permeate")
SO4_rej <- (1-(SO4_perm$avg_mgL/SO4_feed$avg_mgL[c(2:16)]))*100
SO4_rej_std_p <- (SO4_perm$Std_p+SO4_feed$Std_p[c(2:16)])
SO4_rej_std <- abs(SO4_rej_std_p*SO4_rej)

#Na
Na_feed <- Na_IC_data%>%filter(Stream=="Feed")
Na_perm <- Na_IC_data%>%filter(Stream=="Permeate")
Na_rej <- (1-(Na_perm$avg_mgL/Na_feed$avg_mgL[c(2:16)]))*100
Na_rej_std_p <- (Na_perm$Std_p+Na_feed$Std_p[c(2:16)])
Na_rej_std <- abs(Na_rej_std_p*Na_rej)



#Ca
Ca_feed <- Ca_IC_data%>%filter(Stream=="Feed")
Ca_perm <- Ca_IC_data%>%filter(Stream=="Permeate")
Ca_rej <- (1-(Ca_perm$avg_mgL/Ca_feed$avg_mgL[c(2:16)]))*100
Ca_rej_std_p <- (Ca_perm$Std_p+Ca_feed$Std_p[c(2:16)])
Ca_rej_std <- abs(Ca_rej_std_p*Ca_rej)
#Ca_rej <- set_na(Ca_rej,na=c(Ca_rej[10]))
#Ca_rej_std <- set_na(Ca_rej_std,na=c(Ca_rej_std[10]))
#Ca_perm <- set_na(Ca_perm$time,na=c(Ca_perm$time[10]))


#SIO2
SiO2_feed <- SiO2_IC_data%>%filter(Stream=="Feed")
SiO2_perm <- SiO2_IC_data%>%filter(Stream=="Permeate")
SiO2_rej <- (1-(SiO2_perm$SiO2_mgL/SiO2_feed$SiO2_mgL[c(2:16)]))*100
SiO2_rej_std <- c(rep(2,15))
SiO2_rej_std_p <- ((2/SiO2_perm$SiO2_mgL)+(2/SiO2_feed$SiO2_mgL[c(2:16)]))


###Data export
ICR_data = read_excel("data/ICR/analyse_ICR_samlet.xlsx",2)
ICR_df = ICR_data[2:16,]
ICR_df$Rej_Cl = Cl_rej
ICR_df$Rej_SO4 = SO4_rej
ICR_df$Rej_Na = Na_rej
ICR_df$Rej_Ca = Ca_rej
ICR_df$Rej_SiO2 = SiO2_rej
ICR_df$state = "Batch"
write.table(ICR_df,file='data/ICR_df.csv',col.names = T,row.names = F,sep="\t")


ICR_df$Rej_Cl_std_p = Cl_rej_std_p
ICR_df$Rej_SO4_std_p = SO4_rej_std_p
ICR_df$Rej_Na_std_p = Na_rej_std_p
ICR_df$Rej_Ca_std_p = Ca_rej_std_p
ICR_df$Rej_SiO2_std_p = SiO2_rej_std_p


ICR_df$Time=c(20,40,60,80,100,120,140,160,180,200,220,240,270,300,360)
ICR_df = ICR_df%>%mutate("perm_vol"=Time/60*1.02)
ICR_df$start_vol=10
ICR_df = ICR_df%>%mutate("Recovery"=100*(1-(start_vol-perm_vol)/start_vol))

ICR_df_rej_std_p=c(ICR_df$Rej_Cl_std_p,ICR_df$Rej_SO4_std_p,ICR_df$Rej_SiO2_std_p,ICR_df$Rej_Ca_std_p,ICR_df$Rej_Na_std_p)

ICR_ID4_rej = ICR_df%>%gather(key,value, Rej_Cl,Rej_SO4,Rej_SiO2,Rej_Ca,Rej_Na)
ICR_ID4_rej=ICR_ID4_rej%>%mutate("rej_std_p"=ICR_df_rej_std_p)


plot_ID_4=ggplot(ICR_ID4_rej, aes(x=Recovery, y=value,color= key))+geom_point()+geom_line()+geom_hline(yintercept=0)+
  scale_color_brewer(palette= "Set1")+
  geom_errorbar(aes(ymin=value-(value*rej_std_p), ymax=value+(value*rej_std_p)), width=5,
                 position=position_dodge(0.05))+
  labs(x="Water Recovery %",y="Rejection %", color="")+  
  scale_y_continuous(limits=c(-25, 110), breaks=c(-20, 0, 20, 40,60,80,100 ))+
  scale_x_continuous(limits=c(0, 90), breaks=c(10, 30,50,70,90 ))+
  #xlim(c(0,90))+ylim(c(-25,110))+
  ggtitle("4A")

plot_ID_4



```
sampling every 20 min for the first 4 hours then every 30 mins 1 hour and 2 hours. 



```{R sammenligning til multi salt pH 9,  include=FALSE}


#import af iC og silica data. 
pH9.2_IC_data <- read_excel("data/Multi_salt_alle_change_pH.xlsx")

old_names_IC=colnames(pH9.2_IC_data) #Vi finder de latterlige navne kolonnerne i dataen har 
new_names_IC=c("Time","Stream","Name","Sodium","Chloride","Sulphate","Calcium","Silica","DIT_M_Cl","Dilution","Cl_total","Conductivity","pH") #Vi finder på nogle lidt bedre nogle
pH9.2_IC_data = pH9.2_IC_data %>% rename_at(vars(old_names_IC),~new_names_IC) #Vi ændrer navnene til de nye
pH9.2_IC_data <- as.data.frame(pH9.2_IC_data)
pH9.2_bi_data <- pH9.2_IC_data[c(17:19),c(1:4)] #bicarbonat data
pH9.2_IC_data <- pH9.2_IC_data[c(1:13),] #IC data 

pH9.2_IC_data$Sodium<- as.numeric(pH9.2_IC_data$Sodium)  # Convert one variable to numeric
pH9.2_Permeate <- filter(pH9.2_IC_data, Stream=="Permeate")
pH9.2_Feed <- filter(pH9.2_IC_data, Stream=="Feed")
pH9.2_Permeate$Sulphate = c(5,5,5,5,5,5)
pH9.2_rejection <- ((1-(pH9.2_Permeate[,c(4:8)]/pH9.2_Feed[-c(1),c(4:8)]))*100)
pH9.2_rejection$Time <- pH9.2_Permeate$Time

fig_pH9.2 <- plot_ly(data=pH9.2_rejection, x=~Time,
          y=~Chloride,
        type='scatter',mode='lines+markers',
          colors=colors[1], name = "Cl pH9.2")%>%
  add_trace(x=~pH9.2_Permeate$Time,
          y=~pH9.2_rejection$Sulphate,
          type='scatter',mode='lines+markers',
          colors=colors[2], name = "SO4 pH9.2")%>%
add_trace(x=~pH9.2_Permeate$Time,
          y=~pH9.2_rejection$Silica,
        type='scatter',mode='lines+markers',
          colors=colors[3], name = "SiO2 pH9.2")%>%
add_trace(x=~pH9.2_Permeate$Time,
          y=~pH9.2_rejection$Calcium, 
          type='scatter',mode='lines+markers',
                 colors=colors[4], name = "Ca pH9.2")%>%
add_trace(x=~pH9.2_Permeate$Time,
          y=~pH9.2_rejection$Sodium,
        type='scatter',mode='lines+markers',
          colors=colors[5], name = "Na pH9.2")%>%
  layout( yaxis=list(title=" Rejection",range=c(-35,105)),
        xaxis=list(title="Time [h]",range=c(0,9)))


fig_ICR <- plot_ly(x=~Cl_perm$time/60,
          y=~Cl_rej,
         error_y = list(array = ~Cl_rej_std),
        type='scatter',mode='lines+markers',
          colors=colors[1], name = "Cl")%>%
  add_trace(x=~SO4_perm$time/60,
          y=~SO4_rej,
          error_y = list(array = ~SO4_rej_std),
        type='scatter',mode='lines+markers',
          colors=colors[2], name = "SO4")%>%
add_trace(x=~SiO2_perm$time/60,
          y=~SiO2_rej,
          error_y = list(array = ~SiO2_rej_std),
        type='scatter',mode='lines+markers',
          colors=colors[3], name = "SiO2")%>%
add_trace(x=~Ca_perm$time[-c(10)]/60,
          y=~Ca_rej[-c(10)], 
          type='scatter',mode='lines+markers',
          error_y = list(array = ~Ca_rej_std[-c(10)]),
                 colors=colors[4], name = "Ca")%>%
add_trace(x=~Na_perm$time/60,
          y=~Na_rej,
          error_y = list(array = ~Na_rej_std),
        type='scatter',
        mode='lines+markers',
          colors=colors[5], name = "Na")%>%
  layout( yaxis=list(title=" Rejection",range=c(-35,105)),
        xaxis=list(title="Time [h]",range=c(0,9)))


pH10_IC_data <- read_excel("data/Multi_salt_alle_change_pH.xlsx",2)

old_names_IC=colnames(pH10_IC_data) #Vi finder de latterlige navne kolonnerne i dataen har 
new_names_IC=c("Time","Stream","Name","Sodium","Chloride","Sulphate","Calcium","Silica","DIT_M_Cl") #Vi finder på nogle lidt bedre nogle
pH10_IC_data = pH10_IC_data %>% rename_at(vars(old_names_IC),~new_names_IC) #Vi ændrer navnene til de nye
pH10_IC_data <- as.data.frame(pH10_IC_data)
pH10_bi_data <- pH10_IC_data[c(17:19),c(1:4)] #bicarbonat data
pH10_IC_data <- pH10_IC_data[c(1:15),] #IC data 
pH10_IC_data <- pH10_IC_data[-c(2:3),]
pH10_IC_data$Sodium<- as.numeric(pH10_IC_data$Sodium)  # Convert one variable to numeric
pH10_IC_data$Time<- as.numeric(pH10_IC_data$Time)

pH10_Permeate <- filter(pH10_IC_data, Stream=="Permeate")
pH10_Feed <- filter(pH10_IC_data, Stream=="Feed")
pH10_Permeate$Sulphate = c(5,5,5,5,5,5)
pH10_rejection <- ((1-(pH10_Permeate[,c(4:8)]/pH10_Feed[-c(1),c(4:8)]))*100)
pH10_rejection$Time <- pH10_Permeate$Time


 

fig_pH10 <- plot_ly(x=~pH10_Permeate$Time,
          y=~pH10_rejection$Chloride,
        type='scatter',mode='lines+markers',
          colors=colors[1], name = "Cl pH10")%>%
  add_trace(x=~pH10_Permeate$Time,
          y=~pH10_rejection$Sulphate,
          type='scatter',mode='lines+markers',
          colors=colors[2], name = "SO4 pH10")%>%
add_trace(x=~pH10_Permeate$Time,
          y=~pH10_rejection$Silica,
        type='scatter',mode='lines+markers',
          colors=colors[3], name = "SiO2 pH10")%>%
add_trace(x=~pH10_Permeate$Time,
          y=~pH10_rejection$Calcium, 
          type='scatter',mode='lines+markers',
                 colors=colors[4], name = "Ca pH10")%>%
add_trace(x=~pH10_Permeate$Time,
          y=~pH10_rejection$Sodium,
        type='scatter',mode='lines+markers',
          colors=colors[5], name = "Na pH10")%>%
  layout( yaxis=list(title=" Rejection",range=c(-35,105)),
        xaxis=list(title="Time [h]",range=c(0,9)))

fig_pH10


fig_pH9.2 

fig_ICR
```


```{R Sammenligning, eval=FALSE, message=FALSE, include=FALSE}



fig <- subplot(fig_pH9.2,fig_ICR,fig_pH10,nrows=1,titleY=TRUE,titleX=TRUE,margin=0.1)
fig
# Update title
annotations = list( 
  list( 
    x = 0.15,  
    y = 1.0,  
    text = "Silica 75 mg/L, pH 9,25",  
    xref = "paper",  
    yref = "paper",  
    xanchor = "center",  
    yanchor = "bottom",  
    showarrow = FALSE 
  ),  
  list( 
    x = 0.5,  
    y = 1,  
    text = "Silica 75 mg/L, pH 9,5",  
    xref = "paper",  
    yref = "paper",  
    xanchor = "center",  
    yanchor = "bottom",  
    showarrow = FALSE 
  ),  
  list( 
    x = 0.85,  
    y = 1,  
    text = "Silica 75 mg/L, pH 9,75",  
    xref = "paper",  
    yref = "paper",  
    xanchor = "center",  
    yanchor = "bottom",  
    showarrow = FALSE 
  ),
  list( 
    x = 0.15,  
    y = 0.4,  
    text = "Silica 125 mg/L, pH 9,25",  
    xref = "paper",  
    yref = "paper",  
    xanchor = "center",  
    yanchor = "bottom",  
    showarrow = FALSE 
  ),  
  list( 
    x = 0.5,  
    y = 0.4,  
    text = "Silica 125 mg/L, pH 9,5",  
    xref = "paper",  
    yref = "paper",  
    xanchor = "center",  
    yanchor = "bottom",  
    showarrow = FALSE 
  ),  
  list( 
    x = 0.85,  
    y = 0.4,  
    text = "Silica 125 mg/L, pH 9,75",  
    xref = "paper",  
    yref = "paper",  
    xanchor = "center",  
    yanchor = "bottom",  
    showarrow = FALSE 
  ))


```

```{R ID:5-7 import IC_data, echo=FALSE, message=FALSE}

#Imort af CL_IC data. 
ID_5_6_7_Cl_IC_data <- read_excel("data/ICR/ICR_2.xlsx")

old_names_IC=colnames(ID_5_6_7_Cl_IC_data) #Vi finder de latterlige navne kolonnerne i dataen har 
new_names_IC=c("Name", "Time","Stream","Dilution","Cl_1_mg_L","Cl_2_mg_L") #Vi finder på nogle lidt bedre nogle
ID_5_6_7_Cl_IC_data = ID_5_6_7_Cl_IC_data %>% rename_at(vars(old_names_IC),~new_names_IC) #Vi ændrer navnene til de nye
ID_5_6_7_Cl_IC_data <- as.data.frame(ID_5_6_7_Cl_IC_data)
#noget med gennemsnit. 


ID_5_6_7_Cl_IC_data$Cl_1_mg_L=ID_5_6_7_Cl_IC_data$Cl_1_mg_L*ID_5_6_7_Cl_IC_data$Dilution
ID_5_6_7_Cl_IC_data$Cl_2_mg_L=ID_5_6_7_Cl_IC_data$Cl_2_mg_L*ID_5_6_7_Cl_IC_data$Dilution
  
ID_5_6_7_Cl_IC_data <-ID_5_6_7_Cl_IC_data%>%mutate(Cl_mgL=(rowMeans(ID_5_6_7_Cl_IC_data[,c("Cl_1_mg_L","Cl_2_mg_L")],na.rm=TRUE)))%>%
                          mutate(Cl_std_mgL=(rowSds(as.matrix(ID_5_6_7_Cl_IC_data[,c("Cl_1_mg_L","Cl_2_mg_L")],na.rm=TRUE))))%>%
                          mutate(CL_Std_p=((Cl_std_mgL/Cl_mgL)))



#Imort af SO4_IC data. 
ID_5_6_7_SO4_IC_data <- read_excel("data/ICR/ICR_2.xlsx",2)

old_names_IC=colnames(ID_5_6_7_SO4_IC_data) #Vi finder de latterlige navne kolonnerne i dataen har 
new_names_IC=c("Name", "Time","Stream","Dilution","SO4_1_mg_L","SO4_2_mg_L") #Vi finder på nogle lidt bedre nogle
ID_5_6_7_SO4_IC_data = ID_5_6_7_SO4_IC_data %>% rename_at(vars(old_names_IC),~new_names_IC) #Vi ændrer navnene til de nye
ID_5_6_7_SO4_IC_data <- as.data.frame(ID_5_6_7_SO4_IC_data)
#noget med gennemsnit. 


ID_5_6_7_SO4_IC_data$SO4_1_mg_L=ID_5_6_7_SO4_IC_data$SO4_1_mg_L*ID_5_6_7_SO4_IC_data$Dilution
ID_5_6_7_SO4_IC_data$SO4_2_mg_L=ID_5_6_7_SO4_IC_data$SO4_2_mg_L*ID_5_6_7_SO4_IC_data$Dilution
  
ID_5_6_7_SO4_IC_data <-ID_5_6_7_SO4_IC_data%>%mutate(SO4_mgL=(rowMeans(ID_5_6_7_SO4_IC_data[,c("SO4_1_mg_L","SO4_2_mg_L")],na.rm=TRUE)))%>%
                          mutate(SO4_std_mgL=(rowSds(as.matrix(ID_5_6_7_SO4_IC_data[,c("SO4_1_mg_L","SO4_2_mg_L")],na.rm=TRUE))))%>%
                          mutate(SO4_Std_p=((SO4_std_mgL/SO4_mgL)))


#data fra SiO2 

ID_5_6_7_SiO2_IC_data <- read_excel("data/ICR/ICR_2.xlsx",3)

old_names_IC=colnames(ID_5_6_7_SiO2_IC_data) #Vi finder de latterlige navne kolonnerne i dataen har 
new_names_IC=c("Name","Time","Stream","Dilution","SiO2_mgL") #Vi finder på nogle lidt bedre nogle
ID_5_6_7_SiO2_IC_data = ID_5_6_7_SiO2_IC_data %>% rename_at(vars(old_names_IC),~new_names_IC) #Vi ændrer navnene til de nye
ID_5_6_7_SiO2_IC_data <- as.data.frame(ID_5_6_7_SiO2_IC_data)



#Imort af Ca_IC data. 
ID_5_6_7_Ca_IC_data <- read_excel("data/ICR/ICR_2.xlsx",4)

old_names_IC=colnames(ID_5_6_7_Ca_IC_data) #Vi finder de latterlige navne kolonnerne i dataen har 
new_names_IC=c("Name", "Time","Stream","Dilution","Ca_1_mg_L","Ca_2_mg_L") #Vi finder på nogle lidt bedre nogle
ID_5_6_7_Ca_IC_data = ID_5_6_7_Ca_IC_data %>% rename_at(vars(old_names_IC),~new_names_IC) #Vi ændrer navnene til de nye
ID_5_6_7_Ca_IC_data <- as.data.frame(ID_5_6_7_Ca_IC_data)
#noget med gennemsnit. 


ID_5_6_7_Ca_IC_data$Ca_1_mg_L=ID_5_6_7_Ca_IC_data$Ca_1_mg_L*ID_5_6_7_Ca_IC_data$Dilution
ID_5_6_7_Ca_IC_data$Ca_2_mg_L=ID_5_6_7_Ca_IC_data$Ca_2_mg_L*ID_5_6_7_Ca_IC_data$Dilution
  
ID_5_6_7_Ca_IC_data <-ID_5_6_7_Ca_IC_data%>%mutate(Ca_mgL=(rowMeans(ID_5_6_7_Ca_IC_data[,c("Ca_1_mg_L","Ca_2_mg_L")],na.rm=TRUE)))%>%
                          mutate(Ca_std_mgL=(rowSds(as.matrix(ID_5_6_7_Ca_IC_data[,c("Ca_1_mg_L","Ca_2_mg_L")],na.rm=TRUE))))%>%
                          mutate(Ca_Std_p=((Ca_std_mgL/Ca_mgL)))



#Imort af Na_IC data. 
ID_5_6_7_Na_IC_data <- read_excel("data/ICR/ICR_2.xlsx",5)

old_names_IC=colnames(ID_5_6_7_Na_IC_data) #Vi finder de latterlige navne kolonnerne i dataen har 
new_names_IC=c("Name", "Time","Stream","Dilution","Na_1_mg_L","Na_2_mg_L") #Vi finder på nogle lidt bedre nogle
ID_5_6_7_Na_IC_data = ID_5_6_7_Na_IC_data %>% rename_at(vars(old_names_IC),~new_names_IC) #Vi ændrer navnene til de nye
ID_5_6_7_Na_IC_data <- as.data.frame(ID_5_6_7_Na_IC_data)
#noget med gennemsnit. 


ID_5_6_7_Na_IC_data$Na_1_mg_L=ID_5_6_7_Na_IC_data$Na_1_mg_L*ID_5_6_7_Na_IC_data$Dilution
ID_5_6_7_Na_IC_data$Na_2_mg_L=ID_5_6_7_Na_IC_data$Na_2_mg_L*ID_5_6_7_Na_IC_data$Dilution
  
ID_5_6_7_Na_IC_data <-ID_5_6_7_Na_IC_data%>%mutate(Na_mgL=(rowMeans(ID_5_6_7_Na_IC_data[,c("Na_1_mg_L","Na_2_mg_L")],na.rm=TRUE)))%>%
                          mutate(Na_std_mgL=(rowSds(as.matrix(ID_5_6_7_Na_IC_data[,c("Na_1_mg_L","Na_2_mg_L")],na.rm=TRUE))))%>%
                          mutate(Na_Std_p=((Na_std_mgL/Na_mgL)))

```


```{R ID: 5-7 Rejection IC, echo=FALSE, message=FALSE}

Mw_Cl=35.45
Mw_Na=22.99
Mw_Ca=40.078
Mw_SO4=96.06
Mw_SiO2=60.08

#klip i shit
ID_5_Feed_Cl = ID_5_6_7_Cl_IC_data %>% filter(Name == "ID:5")%>%filter(Stream %in%"Feed")
ID_5_perm_Cl = ID_5_6_7_Cl_IC_data %>% filter(Name == "ID:5")%>%filter(Stream %in%"Permeate")
ID_5_Feed_SO4 = ID_5_6_7_SO4_IC_data %>% filter(Name == "ID:5")%>%filter(Stream %in%"Feed")
ID_5_perm_SO4 = ID_5_6_7_SO4_IC_data %>% filter(Name == "ID:5")%>%filter(Stream %in%"Permeate")
ID_5_Feed_SiO2 = ID_5_6_7_SiO2_IC_data %>% filter(Name == "ID:5")%>%filter(Stream %in%"Feed")
ID_5_perm_SiO2 = ID_5_6_7_SiO2_IC_data %>% filter(Name == "ID:5")%>%filter(Stream %in%"Permeate")
ID_5_Feed_Ca = ID_5_6_7_Ca_IC_data %>% filter(Name == "ID:5")%>%filter(Stream %in%"Feed")
ID_5_perm_Ca = ID_5_6_7_Ca_IC_data %>% filter(Name == "ID:5")%>%filter(Stream %in%"Permeate")
ID_5_Feed_Na = ID_5_6_7_Na_IC_data %>% filter(Name == "ID:5")%>%filter(Stream %in%"Feed")
ID_5_perm_Na = ID_5_6_7_Na_IC_data %>% filter(Name == "ID:5")%>%filter(Stream %in%"Permeate")
#sammel resterne 
ID_5=cbind(ID_5_Feed_Cl[-1,c(1:2,7,9)],ID_5_perm_Cl[,c(7,9)],ID_5_Feed_SO4[-1,c(7,9)],ID_5_perm_SO4[,c(7,9)], ID_5_Feed_SiO2[-1,5],ID_5_perm_SiO2[5],ID_5_Feed_Ca[-1,c(7,9)],ID_5_perm_Ca[,c(7,9)],ID_5_Feed_Na[-1,c(7,9)],ID_5_perm_Na[,c(7,9)])
#giver ting de rigtige navne. 
colnames(ID_5) <- c('Name','Time','Cl_Feed','Cl_Feed_Std_p','Cl_perm','Cl_perm_std_p','SO4_Feed','SO4_Feed_Std_p','SO4_perm','SO4_perm_std_p','SiO2_Feed','SiO2_perm','Ca_Feed','Ca_Feed_Std_p','Ca_perm','Ca_perm_std_p','Na_Feed','Na_Feed_Std_p','Na_perm','Na_perm_std_p')


#klip i shit
ID_6_Feed_Cl = ID_5_6_7_Cl_IC_data %>% filter(Name == "ID:6")%>%filter(Stream %in%"Feed")
ID_6_perm_Cl = ID_5_6_7_Cl_IC_data %>% filter(Name == "ID:6")%>%filter(Stream %in%"Permeate")
ID_6_Feed_SO4 = ID_5_6_7_SO4_IC_data %>% filter(Name == "ID:6")%>%filter(Stream %in%"Feed")
ID_6_perm_SO4 = ID_5_6_7_SO4_IC_data %>% filter(Name == "ID:6")%>%filter(Stream %in%"Permeate")
ID_6_Feed_SiO2 = ID_5_6_7_SiO2_IC_data %>% filter(Name == "ID:6")%>%filter(Stream %in%"Feed")
ID_6_perm_SiO2 = ID_5_6_7_SiO2_IC_data %>% filter(Name == "ID:6")%>%filter(Stream %in%"Permeate")
ID_6_Feed_Ca = ID_5_6_7_Ca_IC_data %>% filter(Name == "ID:6")%>%filter(Stream %in%"Feed")
ID_6_perm_Ca = ID_5_6_7_Ca_IC_data %>% filter(Name == "ID:6")%>%filter(Stream %in%"Permeate")
ID_6_Feed_Na = ID_5_6_7_Na_IC_data %>% filter(Name == "ID:6")%>%filter(Stream %in%"Feed")
ID_6_perm_Na = ID_5_6_7_Na_IC_data %>% filter(Name == "ID:6")%>%filter(Stream %in%"Permeate")
#sammel resterne 
ID_6=cbind(ID_6_Feed_Cl[-c(1,6),c(1:2,7,9)],ID_6_perm_Cl[,c(7,9)],ID_6_Feed_SO4[-c(1,6),c(7,9)],ID_6_perm_SO4[,c(7,9)], ID_6_Feed_SiO2[-c(1,6),5],ID_6_perm_SiO2[5],ID_6_Feed_Ca[-c(1,6),c(7,9)],ID_6_perm_Ca[,c(7,9)],ID_6_Feed_Na[-c(1,6),c(7,9)],ID_6_perm_Na[,c(7,9)])
#giver ting de rigtige navne. 
colnames(ID_6) <- c('Name','Time','Cl_Feed','Cl_Feed_Std_p','Cl_perm','Cl_perm_std_p','SO4_Feed','SO4_Feed_Std_p','SO4_perm','SO4_perm_std_p','SiO2_Feed','SiO2_perm','Ca_Feed','Ca_Feed_Std_p','Ca_perm','Ca_perm_std_p','Na_Feed','Na_Feed_Std_p','Na_perm','Na_perm_std_p')

ICR_2_df = rbind(ID_5,ID_6)
ICR_2_df = ICR_2_df%>%mutate("perm_vol"=Time*1.02)
ICR_2_df$start_vol=10
ICR_2_df = ICR_2_df%>%mutate("Recovery"=100*(1-(start_vol-perm_vol)/start_vol))
ICR_2_df$rej_Cl=((1-(ICR_2_df$Cl_perm/ICR_2_df$Cl_Feed))*100)
ICR_2_df$rej_SO4=((1-(ICR_2_df$SO4_perm/ICR_2_df$SO4_Feed))*100)
ICR_2_df$rej_SiO2=((1-(ICR_2_df$SiO2_perm/ICR_2_df$SiO2_Feed))*100)
ICR_2_df$rej_Ca=((1-(ICR_2_df$Ca_perm/ICR_2_df$Ca_Feed))*100)
ICR_2_df$rej_Na=((1-(ICR_2_df$Na_perm/ICR_2_df$Na_Feed))*100)

ICR_2_df$Rej_Cl_std_p=(ICR_2_df$Cl_perm_std_p+ICR_2_df$Cl_Feed_Std_p)
ICR_2_df$Rej_SO4_std_p=(ICR_2_df$SO4_perm_std_p+ICR_2_df$SO4_Feed_Std_p)
ICR_2_df$Rej_SiO2_std_p=((2/ICR_2_df$SiO2_perm)+(2/ICR_2_df$SiO2_Feed))
ICR_2_df$Rej_Ca_std_p=(ICR_2_df$Ca_perm_std_p+ICR_2_df$Ca_Feed_Std_p)
ICR_2_df$Rej_Na_std_p=(ICR_2_df$Na_perm_std_p+ICR_2_df$Na_Feed_Std_p)


ICR_2_rej = ICR_2_df%>%gather(key,value, rej_Cl,rej_SO4,rej_SiO2,rej_Ca,rej_Na)
ICR_2_rej_std_p=c(ICR_2_df$Rej_Cl_std_p,ICR_2_df$Rej_SO4_std_p,ICR_2_df$Rej_SiO2_std_p,ICR_2_df$Rej_Ca_std_p,ICR_2_df$Rej_Na_std_p)

ICR_2_rej=ICR_2_rej%>%mutate("rej_std_p"=ICR_2_rej_std_p)



plot_ID_5=ggplot(ICR_2_rej%>%filter(Name=="ID:5"), aes(x=Recovery, y=value,color= key))+geom_point()+geom_line()+geom_hline(yintercept=0)+
  scale_color_brewer(palette= "Set1")+
  geom_errorbar(aes(ymin=value-(value*rej_std_p), ymax=value+(value*rej_std_p)), width=5,
                 position=position_dodge(0.05))+
    labs(x="Water Recovery %",y="Rejection %", color="")+  
  scale_y_continuous(limits=c(-25, 110), breaks=c(-20, 0, 20, 40,60,80,100 ))+
  scale_x_continuous(limits=c(0, 90), breaks=c(10, 30,50,70,90 ))+
  #xlim(c(0,90))+ylim(c(-25,110))+
  ggtitle("5A")



plot_ID_6=ggplot(ICR_2_rej%>%filter(Name=="ID:6"), aes(x=Recovery, y=value,color= key))+geom_point()+geom_line()+geom_hline(yintercept=0)+
  scale_color_brewer(palette= "Set1")+
  geom_errorbar(aes(ymin=value-(value*rej_std_p), ymax=value+(value*rej_std_p)), width=5,
                 position=position_dodge(0.05))+
  labs(x="Water Recovery %",y="Rejection %", color="")+ 
  scale_y_continuous(limits=c(-25, 110), breaks=c(-20, 0, 20, 40,60,80,100 ))+
  scale_x_continuous(limits=c(0, 90), breaks=c(10, 30,50,70,90 ))+
  #xlim(c(0,90))+ylim(c(-25,110))+
  ggtitle("5B")

ggarrange(plot_ID_5,plot_ID_6, ncol=2, nrow=1, common.legend = TRUE, legend="bottom")#,align = "v")
ggarrange(plot_ID_4,plot_ID_5,plot_ID_6, ncol=3, nrow=1, common.legend = TRUE, legend="bottom")#,align = "v")

plotly_ID_4=ggplotly(plot_ID_4)
plotly_ID_5=ggplotly(plot_ID_5)
plotly_ID_6=ggplotly(plot_ID_6)

#plotly grafer hvis man foretrækker det. 
hejmeddig_1 = subplot(plotly_ID_4,plotly_ID_5,plotly_ID_6,nrows=1)
hejmeddig_1

```

### Concentration
```{r Concetration}

ID4Na=Na_IC_data%>%select(-c(3,4,5))%>%mutate(Name="ID4")%>%mutate(ion="Na")
ID4Cl=Cl_IC_data%>%select(-c(3,4,5))%>%mutate(Name="ID4")%>%mutate(ion="Cl")
ID4so4=SO4_IC_data%>%select(-c(3,4,5))%>%mutate(Name="ID4")%>%mutate(ion="SO4")
ID4Ca=Ca_IC_data%>%select(-c(3,4,5))%>%mutate(Name="ID4")%>%mutate(ion="Ca")
ID4sio2=SiO2_IC_data%>%mutate(Name="ID4")%>%mutate(ion="sio2")%>%mutate(Std_p=NA)
colnames(ID4sio2) = c("time","Stream","avg_mgL","std_mgL","Name","ion","Std_p")

col_order <- c("Name","time","Stream","avg_mgL","std_mgL","Std_p","ion")
ID4Na = ID4Na[,col_order]
ID4Cl = ID4Cl[,col_order]
ID4Ca = ID4Ca[,col_order]
ID4so4 = ID4so4[,col_order]
ID4sio2 = ID4sio2[,col_order]

ID4=rbind(ID4Na,ID4Cl,ID4so4,ID4Ca,ID4sio2)
ID4$time=ID4$time/60
ID4$time[c(33,34,35,68,69,70,103,104,105,138,139,140,173,174,175)]=ID4$time[c(33,34,35,68,69,70,103,104,105,138,139,140,173,174,175)]*60
ID_5_6_7_Na=ID_5_6_7_Na_IC_data%>%select(-c(4,5,6))%>%mutate(ion="Na")
ID_5_6_7_Cl=ID_5_6_7_Cl_IC_data%>%select(-c(4,5,6))%>%mutate(ion="Cl")
ID_5_6_7_Ca=ID_5_6_7_Ca_IC_data%>%select(-c(4,5,6))%>%mutate(ion="Ca")
ID_5_6_7_SO4=ID_5_6_7_SO4_IC_data%>%select(-c(4,5,6))%>%mutate(ion="SO4")

ID_5_6_7_sio2=ID_5_6_7_SiO2_IC_data%>%select(-4)%>%mutate(std_mgL=2,Std_p=NA,ion="sio2")
ID4$time[1]

colnames(ID_5_6_7_sio2) = c("Name","time","Stream","avg_mgL","std_mgL","Std_p","ion")
ID_5_6_7_sio2= ID_5_6_7_sio2[,col_order]

colnames(ID_5_6_7_Na) = c("Name","time","Stream","avg_mgL","std_mgL","Std_p","ion")
colnames(ID_5_6_7_Cl) = c("Name","time","Stream","avg_mgL","std_mgL","Std_p","ion")
colnames(ID_5_6_7_Ca) = c("Name","time","Stream","avg_mgL","std_mgL","Std_p","ion")
colnames(ID_5_6_7_SO4) = c("Name","time","Stream","avg_mgL","std_mgL","Std_p","ion")
ID_5_6_7=rbind(ID_5_6_7_Na,ID_5_6_7_Cl,ID_5_6_7_Ca,ID_5_6_7_SO4,ID_5_6_7_sio2)
ICR_all=rbind(ID4,ID_5_6_7)
ICR_all=ICR_all%>%mutate(Name=replace(Name,Name=="ID4","4A"))%>%mutate(Name=replace(Name,Name=="ID:5","4B"))%>%mutate(Name=replace(Name,Name=="ID:6","5A"))%>%mutate(Name=replace(Name,Name=="ID:7","5B"))

molw=data.frame(Cl=35.45,
Na=22.99,
Ca=40.078,
SO4=96.06,
sio2=60.08)
ioner=c("Cl","Na","Ca","SO4","sio2")


for (i in 1:nrow(ICR_all)) {
  d=match(ICR_all$ion[i],ioner)
  ICR_all$mw[i]=as.double(molw[d])
  i=i+1
}

ICR_all$avg_mgL=as.double(ICR_all$avg_mgL)
ICR_all=ICR_all%>%mutate(mM=avg_mgL/mw)


ICR_plot=rbind(
ICR_all%>%filter(Stream=="Feed"&Name=="4A"&time==0)%>%mutate(plads="4A Feed")%>%mutate(pos=1),
ICR_all%>%filter(Stream=="Perm spand"&Name=="4A"&time==4)%>%mutate(plads="4A Permeate")%>%mutate(pos=2),
ICR_all%>%filter(Stream=="Feed"&Name=="4B"&time==0)%>%mutate(plads="4B Feed")%>%mutate(pos=3),
ICR_all%>%filter(Stream=="Perm spand"&Name=="4B"&time==4)%>%mutate(plads="4B Permeate")%>%mutate(pos=4)
)

ggplotly(
  ggplot(ICR_plot,aes(x=pos, y=mM,color= ion))+geom_point(aes(shape=Name))+geom_hline(yintercept=0)+
  scale_color_brewer(palette= "Set1")+
  labs(x="",y="Concentration", color="Ion",linetype="Experiment")+xlim(c(0,NA))+
  ggtitle("ICR 4A + 4B")
)

ion_plot=ggplot(ICR_plot, aes(fill=plads, y=mM, x=ion)) + 
    geom_bar(position="dodge", stat="identity")
ggplotly(ion_plot)

ICR_4=ICR_plot[c(1:12,14,13,15:17,19,18,20),]
R_filtration1=1-(ICR_4[6:10,]$mM/ICR_4[1:5,]$mM)
R_filtration2=1-(ICR_4[16:20,]$mM/ICR_4[1:5,]$mM)
df=data.frame(ICR_plot[1:5,]$ion,R_filtration1,R_filtration2)
df

print(xtable(df, type = "latex"))

ion_plot2=ggplot(ICR_plot%>%filter(ion!="Ca"&ion!="sio2"), aes(fill=ion, y=mM, x=plads)) + 
    geom_bar(position="dodge", stat="identity")
ggplotly(ion_plot2)

ion_plot3=ggplot(ICR_plot%>%filter(ion=="Ca"|ion=="sio2"), aes(fill=ion, y=mM, x=plads)) + 
    geom_bar(position="dodge", stat="identity")


  p <- ggplot(ICR_plot%>%filter(ion=="Ca"|ion=="sio2"), aes(fill=ion, y=mM, x=plads)) + 
    geom_bar(position="dodge", stat="identity") + 
    scale_x_discrete( drop=FALSE) + 
    guides(fill=FALSE) +
    theme_bw(base_size=9) +  ## makes everything smaller
    theme(panel.background = element_rect(fill="white"),  ## white plot background 
          axis.title.y = element_blank(),
          axis.title.x = element_blank(),
          axis.text.x = element_text(size=rel(0.7)), ## tiny axis text
          panel.grid.major = element_blank(),
          panel.grid.minor = element_blank(),
          plot.background = element_blank())
  
ion_plot2 + 
  annotation_custom(grob=ggplotGrob(p), 
    xmin = -4, xmax = 10, ymin = 1, ymax = 100
  )


```











