---
title: "Multi_salt_summary"
author: "Lærke"
date: "19/10/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
#Loading af pakker 
library(dplyr)
library(tidyr)
library(ggplot2)
library(visdat)
library(GGally)
library(Hmisc)
library(DMwR2)
library(data.table)
library(mltools)
library(ggfortify)
library(ggiraphExtra)
library(coronavirus)
library(lubridate)
library(plotly)
library(readxl)
require(readr)
library(zoo)
library(latex2exp)
library(fs)
```

Summary of Multi salt experiments.

All experiments were performed with:

Flux 20 LMH (permeate flow 17 mL/min)

Crossflow of 0.5 m/s (feed flow 1160 mL/min) 

The concentraiton of the various salts were selected based on concentration of authentic CT reservior water. 

<h3> pH 9.2 </h3>

The pH was ajusted to pH 9.2 which is the lower end of the capacity for the bicarboante-carbonate buffer. 
The pressure started at 2.5 bar where it increased to about 2.8 bar over the course of the experiment. The osmotic pressure will be calculated to determine if the increase in pressure is due to increase in the osmotic pressure on the feed side of the membrane or if it is due to fouling of the membrane. 




```{R Flow before experiment 9.2, include=FALSE, echo=FALSE, message=FALSE}
CWF_Multi_9.2 = read_delim("data/Multi_9.2_18-10-2021_del1.csv",delim = "\t", escape_double = FALSE, 
                  trim_ws = TRUE, skip = 5) #Hente data og få det til passe ned i en tabel
#str(CWF)
dat_M_9.2 = as.data.frame(CWF_Multi_9.2) #Ændrer strukturen af dataen til noget vi kan arbejde med
old_names=colnames(CWF_Multi_9.2) #Vi finder de latterlige navne kolonnerne i dataen har 
new_names=c("time","level","con0201","pH0201","con0301","flow0301",
            "p0301","p0302","p0401","flow0401","p0501","con0501",
            "temp0501","p0601","temp0601","16","17","18","19","20",
            "21","pmp0201","pmp0301","pmp0401","pmp0501","flow_avg0301",
            "p_avg0301","p_avg0302","p_avg0401","flow_avg0401",
            "p_avg0501","FT0302","weight0302","flow0501","weight0501","36","pH0301",
            "pH0501","con0302","40") #Vi finder på nogle lidt bedre nogle
dat_M_9.2 = dat_M_9.2 %>% rename_at(vars(old_names),~new_names) #Vi ændrer navnene til de nye
dat_M_9.2$time = dmy_hms(dat_M_9.2$time)#Vi ændrer formatet af 'dato' kolonnen til et standard format for tid og datoer istedet for at det bare er noget tekst
#str(dat)


ggplot()+
  geom_point(data=dat_M_9.2, aes(x=time, y=flow0301), shape= 16)+
  labs(x="Time (18 okt 2021)",y=" Flow mL/min")+
  ylim(1000,1500)+
  ggtitle("Flow during flush") 









```

```{R pH 9.2 import data plot pressure, echo=FALSE, message=FALSE}
CWF_Multi_9.2 = read_delim("data/Multi_9.2_19-10-2021_del2.csv",delim = "\t", escape_double = FALSE, 
                  trim_ws = TRUE, skip = 5) #Hente data og få det til passe ned i en tabel
#str(CWF)
dat_M_9.2 = as.data.frame(CWF_Multi_9.2) #Ændrer strukturen af dataen til noget vi kan arbejde med
old_names=colnames(CWF_Multi_9.2) #Vi finder de latterlige navne kolonnerne i dataen har 
new_names=c("time","level","con0201","pH0201","con0301","flow0301",
            "p0301","p0302","p0401","flow0401","p0501","con0501",
            "temp0501","p0601","temp0601","16","17","18","19","20",
            "21","pmp0201","pmp0301","pmp0401","pmp0501","flow_avg0301",
            "p_avg0301","p_avg0302","p_avg0401","flow_avg0401",
            "p_avg0501","FT0302","weight0302","flow0501","weight0501","36","pH0301",
            "pH0501","con0302","40") #Vi finder på nogle lidt bedre nogle
dat_M_9.2 = dat_M_9.2 %>% rename_at(vars(old_names),~new_names) #Vi ændrer navnene til de nye
dat_M_9.2$time = dmy_hms(dat_M_9.2$time)#Vi ændrer formatet af 'dato' kolonnen til et standard format for tid og datoer istedet for at det bare er noget tekst
#str(dat)



### Finde t=0 (fosøgsstart = der hvor flow er over 16 mL/min)
flow_boolean = dat_M_9.2$flow0501>16&dat_M_9.2$flow0501<25
start_tid = min(which(flow_boolean))
dat_M_9.2=dat_M_9.2[-c(1:start_tid),]
flow_boolean_slut = dat_M_9.2$flow0501<1
slut_tid = min(which(flow_boolean_slut))
dat_M_9.2=dat_M_9.2[-c(slut_tid:(nrow(dat_M_9.2)) ),]
### Tid i s fra forsøgs start
dat_M_9.2 = dat_M_9.2%>%
   mutate(sek=(
           as.numeric(as.POSIXct(dat_M_9.2$time))-as.numeric(dat_M_9.2$time[1], format='%Y-%m-%d %H:%M:%S'))
                )  

dat_M_9.2 %>%#dplyr arbejder indenfor 'dat' data framen
  mutate(TMP=(p_avg0301+p_avg0302)/2-p_avg0501)%>%#Her regner vi TMP, som dplyr husker nu er en del af den data
  mutate(TMP_slid=rollapply(TMP,100,mean,align="right",fill=NA))%>%#Nu tager vi et glidende gennemsnit
  plot_ly(x=~(sek)/3600,
          y=~TMP_slid,
          name="TMP",
          color='#forestgreen',
          type='scatter',
          mode='lines')%>%
  #add_lines(y=~p_avg0302,
   #         name='Pressure after membrane',
   #         color='#E41317')%>%
 # add_lines(y=~TMP_slid,
  #          name='TMP',
  #          color='#forestgreen')%>%
  layout(title="TMP Multi salt pH 9.2",
         legend=list(x=0.7,y=0.2),
         yaxis=list(title="Pressure [bar]"),
         xaxis=list(title="Time [h]")) #Her plottet TMP




```
The conductivity was initially 1320 microS/cm in the feed stream where it increased to about 2500 microS/cm. The permeate stream was initially 550 microS/cm, and the conductivity of the permeate surpassed the maximum of the conductivity sensor at 1000 microS/cm after about 7.5 hours. 
The rejection of 

```{R pH 9.2 plot conductivity, echo=FALSE, message=FALSE}
ay <- list(
  tickfont = list(color = "red"),
  overlaying = "y",
  side = "right",
  title = "Rejection") #Her noget hokus-pokus for at kunne lave 2 y akser


dat_M_9.2 %>%
  mutate(rejection=(1-(con0501/con0301))*100)%>%
  mutate(feed_slid=rollapplyr(con0301,30,mean,fill=NA))%>%
  mutate(rej_slid=rollapplyr(rejection,30,mean,fill=NA))%>%
  plot_ly(x=~sek/3600,
          y=~feed_slid,
          name="Feed",
          color="red",
          type='scatter',
          mode='lines',
          line=list(color=('#1f77b4')))%>%
  add_trace(y=~con0501,
            name='Permeate',
            line=list(color="#E41317"))%>%
  add_trace(y=~rej_slid,
            name='Rejection',
            yaxis="y2",
            line=list(color="#forestgreen"))%>%
  # Set figure title, x and y-axes titles
  layout(title="Conductivity and rejection Multi salt pH 9.2",yaxis2=ay,
         legend=list(x=0.6,y=0.5),
         yaxis=list(title= "Conductivity \U03BC S/cm")) #Her conductivity over tid + en form for rejection, 
#læg gerne mærke til farverne der nægter at se


```

The average permeate flow was 16.995 mL/min, the plot show rooling average of the permeate flow indicating only minor flucturations during the experiment. 

The initial feed volume of 10.54 L, where 540 mL was taken out as samples.
The experiment was set to run for 9 h and 5 min, bus as the feed tank ran out around 8 h 40 min, the experiment was stopped. This also mean there was no feed left when the experiment was ended. 
It was suspected that the feed thank ran out before time due to some water being "used"/supressed into the dampener, this volume was estimated to 250 mL. 
As the permeate flow is fluctuating this might also cause the faster time to use all feed water. 

```{R Multi pH 9.2, permeate flow , echo=FALSE, message=FALSE}

print(mean(dat_M_9.2$flow0501))

flow0501_slid=dat_M_9.2$flow0501=rollapply(dat_M_9.2$flow0501,100,mean,align="right",fill=NA)

ggplot()+
  geom_point(data=dat_M_9.2, aes(x=sek/3600, y=flow0501_slid), shape= 16)+
  labs(x="Time [h]",y=" Permeate Flow mL/min")+
  ylim(15,20)+
  ggtitle("Multi salt pH 9.2 Permeate flow ") 

```