---
title: "Phasediagrams"
author: "Steffen"
date: "28/3/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(include = FALSE)
library(plyr)
library(dplyr)
library(tidyr)
library(ggplot2)
library(visdat)
library(GGally)
library(Hmisc)
library(DMwR2)
library(data.table)
library(mltools)
library(ggfortify)
library(ggiraphExtra)
library(coronavirus)
library(lubridate)
library(plotly)
#library(naniar)
library(readxl)
require(readr)
library(zoo)
library(latex2exp)
library(fs)
library(plyr)
library(matrixStats)
library(haven)
library(sjmisc)
require(gridExtra)
require(ggpubr)

colors = c(
  '#1f77b4',  # muted blue
  '#ff7f0e',  # safety orange
  '#2ca02c',  # cooked asparagus green
  '#d62728',  # brick red
  '#9467bd',  # muted purple
  '#8c564b',  # chestnut brown
  '#e377c2',  # raspberry yogurt pink
  '#7f7f7f',  # middle gray
  '#bcbd22',  # curry yellow-green
  '#17becf'   # blue-teal
)
```


```{r data}
silica =  read_excel("data/minteq/pH_pC_silica.xlsx", 
    range = "A1:E121")
silica = silica %>% mutate(Ct=H4SiO4+`H3SiO4-`+`H2SiO4-2`)
silica = silica %>% mutate(`pH2SiO4-2` = `H2SiO4-2`/Ct)%>%mutate(pH4SiO4 = H4SiO4/Ct)%>%mutate(`pH3SiO4-` = `H3SiO4-`/Ct)%>%mutate(ladet=`pH3SiO4-`+`pH2SiO4-2`)

### Noget Silica ladning model
x=silica$pH
y1=silica$ladet
plot(y1~x)
a=1.00016
b=2.314233
c=9.831689
silica = silica%>%mutate(frac_ladet_model =  a/(1+exp(-b*(pH-c))))
names(silica)[7:9]=c("H_2SiO_4^2-","H_3SiO_4^-","H_4SiO4")  
y2=silica$frac_ladet_model

ladning_plot=data.frame(x,y1,y2)
ggplot(ladning_plot,aes(x = x,y=y1))+geom_point()+geom_line(aes(x=x,y=y2))


plot(y~x)

carbonat = read_excel("data/minteq/pH_pC_carbonat.xlsx")
carbonat = carbonat%>%mutate(Ct=`CO3-2`+`HCO3-`+`H2CO3* (aq)`)


```


```{r plots, echo=FALSE}
carbonat.long = carbonat %>% gather(key = "key",value="value",`CO3-2`,`HCO3-`,`H2CO3* (aq)` )
ggplotly(ggplot(carbonat.long, aes(x=pH, y=value,color= key))+geom_line()+ylab("Fraction Present")+scale_x_continuous(breaks = (seq(2,13, by = 1)))+labs(color="Species"))


silica.long = silica%>%gather(key="key",value = "value",`H_2SiO_4^2-`,`H_3SiO_4^-`,`H_4SiO4`)
ggplotly(ggplot(silica.long, aes(x=pH, y=value,color= key))+geom_line()+ylab("Fraction Present")+scale_x_continuous(breaks = (seq(2,14, by = 1)))+labs(color="Species"))


ggplotly(ggplot(silica, aes(x=pH, y=ladet))+geom_line())
```

