---
title: "Pilot_scale"
author: "Lærke"
date: "2/5/2022"
output: 
  html_document:
    toc: true
    toc_depth: 3
editor_options: 
  markdown: 
    wrap: sentence
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,warning=F,message=F)
library(plyr)
library(dplyr)
library(tidyr)
library(ggplot2)
library(visdat)
library(GGally)
library(Hmisc)
library(DMwR2)
library(data.table)
library(mltools)
library(ggfortify)
library(ggiraphExtra)
library(coronavirus)
library(lubridate)
library(plotly)
#library(naniar)
library(readxl)
require(readr)
library(zoo)
library(latex2exp)
library(fs)
library(plyr)
library(matrixStats)
library(haven)
library(sjmisc)
require(gridExtra)
require(ggpubr)

colors = c(
  '#1f77b4',  # muted blue
  '#ff7f0e',  # safety orange
  '#2ca02c',  # cooked asparagus green
  '#d62728',  # brick red
  '#9467bd',  # muted purple
  '#8c564b',  # chestnut brown
  '#e377c2',  # raspberry yogurt pink
  '#7f7f7f',  # middle gray
  '#bcbd22',  # curry yellow-green
  '#17becf'   # blue-teal
)
```
## Summary of Pilot scale experiments. {.tabset}
### PLC Data 

```{r pilot PLC 8A, echo=FALSE}



Pilot_8A_raw = read_delim("data/Pilot_scale/_25-04-2022 091802.csv",delim = "\t", escape_double = FALSE, trim_ws = TRUE, skip = 5) #Hente data og få det til passe ned i en tabel

Pilot_8A = as.data.frame(Pilot_8A_raw) #Ændrer strukturen af dataen til noget vi kan arbejde med
old_names=colnames(Pilot_8A_raw) #Vi finder de gamle navne kolonnerne i dataen har 
new_names=c("Time","TimeStamp1","LT0101","FT0101","PT0101","TT0101","ConT0101","PT0102","FT0102",
            "PT0103","PT0104","FT0201","LT0201","PT0202","ConT0202","PT0301","LT0401","TT0401","PHT0401",
            "PT0501","CV0302","PMP0101","PMP0102","PMP0103","PMP010","PMP0201","PMP0301","PMP0402","PMP0403",
            "PMP0404","sequence","PowerTotal_kW","Power_kW","PHT0101" ) #Vi finder på nogle lidt bedre nogle

Pilot_8A = Pilot_8A %>% rename_at(vars(old_names),~new_names) #Vi ændrer navnene til de nye
Pilot_8A$Time = dmy_hms(Pilot_8A$Time)#Vi ændrer formatet af 'dato' kolonnen til et standard format for tid og datoer istedet for at det bare er noget tekst



### TMP ###
Pilot_8A = Pilot_8A %>% mutate(TMP=(PT0104+PT0301)/2-PT0202)

### Finde t=0 (fosøgsstart = der hvor flow er over 16 mL/min)
flow_boolean = Pilot_8A$FT0201>0.150&Pilot_8A$FT0201<0.450
start_tid = min(which(flow_boolean))
Pilot_8A=Pilot_8A[-c(1:start_tid),]
flow_boolean_slut = Pilot_8A$FT0201<0.05
slut_tid = min(which(flow_boolean_slut))
Pilot_8A=Pilot_8A[-c(slut_tid:(nrow(Pilot_8A)) ),]
### Tid i s fra forsøgs start

Pilot_8A = Pilot_8A%>%
   mutate(sek=(
           as.numeric(as.POSIXct(Pilot_8A$Time))-as.numeric(Pilot_8A$Time[1], format='%Y-%m-%d %H:%M:%S'))
                )  

plc_8A = Pilot_8A %>%
  plot_ly(x=~(sek)/3600,
          y=~TMP,
          name="TMP",
          type='scatter',
          mode='lines',
          line=list(color= colors[1]))%>%
  add_lines(x=~sek/3600,
          y=~PHT0101,
          name=' pH',
          type='scatter',
          mode='line',
          line=list(color=colors[2]))%>%
add_lines(x=~sek/3600,
          y=~ConT0101,
          name='Conductivity',
          type='scatter',
          mode='line',
      line=list(color=colors[3]))%>%
  layout(title="Pilot-scale ID: 8A",
         legend=list(x=0.9,y=0.9),
         yaxis=list(title="value", range=c(NA,NA)),
         xaxis=list(title="Time [h]",range=c(0,3))
         ) 


plc_8A




```

```{r pilot PLC 8B, echo=FALSE}



Pilot_8B_raw = read_delim("data/Pilot_scale/_26-04-2022 000002.csv",delim = "\t", escape_double = FALSE, trim_ws = TRUE, skip = 5) #Hente data og få det til passe ned i en tabel

Pilot_8B = as.data.frame(Pilot_8B_raw) #Ændrer strukturen af dataen til noget vi kan arbejde med
old_names=colnames(Pilot_8B_raw) #Vi finder de gamle navne kolonnerne i dataen har 
new_names=c("Time","TimeStamp1","LT0101","FT0101","PT0101","TT0101","ConT0101","PT0102","FT0102",
            "PT0103","PT0104","FT0201","LT0201","PT0202","ConT0202","PT0301","LT0401","TT0401","PHT0401",
            "PT0501","CV0302","PMP0101","PMP0102","PMP0103","PMP010","PMP0201","PMP0301","PMP0402","PMP0403",
            "PMP0404","sequence","PowerTotal_kW","Power_kW","PHT0101" ) #Vi finder på nogle lidt bedre nogle

Pilot_8B = Pilot_8B %>% rename_at(vars(old_names),~new_names) #Vi ændrer navnene til de nye
Pilot_8B$Time = dmy_hms(Pilot_8B$Time)#Vi ændrer formatet af 'dato' kolonnen til et standard format for tid og datoer istedet for at det bare er noget tekst



### TMP ###
Pilot_8B = Pilot_8B %>% mutate(TMP=(PT0104+PT0301)/2-PT0202)

### Finde t=0 (fosøgsstart = der hvor flow er over 16 mL/min)
flow_boolean = Pilot_8B$FT0201>0.150&Pilot_8B$FT0201<0.450
start_tid = min(which(flow_boolean))
Pilot_8B=Pilot_8B[-c(1:start_tid),]
flow_boolean_slut = Pilot_8B$FT0201<0.140
slut_tid = min(which(flow_boolean_slut))
Pilot_8B=Pilot_8B[-c(slut_tid:(nrow(Pilot_8B)) ),]
### Tid i s fra forsøgs start

Pilot_8B = Pilot_8B%>%
   mutate(sek=(
           as.numeric(as.POSIXct(Pilot_8B$Time))-as.numeric(Pilot_8B$Time[1], format='%Y-%m-%d %H:%M:%S'))
                )  
plc_8B = Pilot_8B %>%
  plot_ly(x=~(sek)/3600,
          y=~TMP,
          name="TMP",
          type='scatter',
          mode='lines',
          line=list(color= colors[1]))%>%
  add_lines(x=~sek/3600,
          y=~PHT0101,
          name=' pH',
          type='scatter',
          mode='line',
          line=list(color=colors[2]))%>%
add_lines(x=~sek/3600,
          y=~ConT0101,
          name='Conductivity',
          type='scatter',
          mode='line',
      line=list(color=colors[3]))%>%
  layout(title="Pilot-scale ID: 8B",
         legend=list(x=0.9,y=0.9),
         yaxis=list(title="value", range=c(NA,NA)),
         xaxis=list(title="Time [h]",range=c(0,3))
         ) 


plc_8B




```
### IC data 
 

```{R import IC data, echo=FALSE, message=FALSE}

#Imort af CL_IC data. 
Cl_ID8A_8B_IC_data <- read_excel("data/Pilot_scale/IC_data_pilot.xlsx")

old_names_IC=colnames(Cl_ID8A_8B_IC_data) #Vi finder de latterlige navne kolonnerne i dataen har 
new_names_IC=c("Name", "Time","Stream","Dilution","Cl_1_mg_L","Cl_2_mg_L") #Vi finder på nogle lidt bedre nogle
Cl_ID8A_8B_IC_data = Cl_ID8A_8B_IC_data %>% rename_at(vars(old_names_IC),~new_names_IC) #Vi ændrer navnene til de nye
Cl_ID8A_8B_IC_data <- as.data.frame(Cl_ID8A_8B_IC_data)
#noget med gennemsnit. 


Cl_ID8A_8B_IC_data$Cl_1_mg_L=Cl_ID8A_8B_IC_data$Cl_1_mg_L*Cl_ID8A_8B_IC_data$Dilution
Cl_ID8A_8B_IC_data$Cl_2_mg_L=Cl_ID8A_8B_IC_data$Cl_2_mg_L*Cl_ID8A_8B_IC_data$Dilution
  
Cl_ID8A_8B_IC_data <-Cl_ID8A_8B_IC_data%>%mutate(Cl_mgL=(rowMeans(Cl_ID8A_8B_IC_data[,c("Cl_1_mg_L","Cl_2_mg_L")],na.rm=TRUE)))%>%
                          mutate(Cl_std_mgL=(rowSds(as.matrix(Cl_ID8A_8B_IC_data[,c("Cl_1_mg_L","Cl_2_mg_L")],na.rm=TRUE))))%>%
                          mutate(CL_Std_p=((Cl_std_mgL/Cl_mgL)))

#Imort af SO4_IC data. 
SO4_ID8A_8B_IC_data <- read_excel("data/Pilot_scale/IC_data_pilot.xlsx",2)

old_names_IC=colnames(SO4_ID8A_8B_IC_data) #Vi finder de latterlige navne kolonnerne i dataen har 
new_names_IC=c("Name", "Time","Stream","Dilution","SO4_1_mg_L","SO4_2_mg_L") #Vi finder på nogle lidt bedre nogle
SO4_ID8A_8B_IC_data = SO4_ID8A_8B_IC_data %>% rename_at(vars(old_names_IC),~new_names_IC) #Vi ændrer navnene til de nye
SO4_ID8A_8B_IC_data <- as.data.frame(SO4_ID8A_8B_IC_data)
#noget med gennemsnit. 


SO4_ID8A_8B_IC_data$SO4_1_mg_L=SO4_ID8A_8B_IC_data$SO4_1_mg_L*SO4_ID8A_8B_IC_data$Dilution
SO4_ID8A_8B_IC_data$SO4_2_mg_L=SO4_ID8A_8B_IC_data$SO4_2_mg_L*SO4_ID8A_8B_IC_data$Dilution
  
SO4_ID8A_8B_IC_data <-SO4_ID8A_8B_IC_data%>%mutate(SO4_mgL=(rowMeans(SO4_ID8A_8B_IC_data[,c("SO4_1_mg_L","SO4_2_mg_L")],na.rm=TRUE)))%>%
                          mutate(SO4_std_mgL=(rowSds(as.matrix(SO4_ID8A_8B_IC_data[,c("SO4_1_mg_L","SO4_2_mg_L")],na.rm=TRUE))))%>%
                          mutate(SO4_Std_p=((SO4_std_mgL/SO4_mgL)))

#Imort af Na_IC data. 
Na_ID8A_8B_IC_data <- read_excel("data/Pilot_scale/IC_data_pilot.xlsx",3)

old_names_IC=colnames(Na_ID8A_8B_IC_data) #Vi finder de latterlige navne kolonnerne i dataen har 
new_names_IC=c("Name", "Time","Stream","Dilution","Na_1_mg_L","Na_2_mg_L") #Vi finder på nogle lidt bedre nogle
Na_ID8A_8B_IC_data = Na_ID8A_8B_IC_data %>% rename_at(vars(old_names_IC),~new_names_IC) #Vi ændrer navnene til de nye
Na_ID8A_8B_IC_data <- as.data.frame(Na_ID8A_8B_IC_data)
#noget med gennemsnit. 


Na_ID8A_8B_IC_data$Na_1_mg_L=Na_ID8A_8B_IC_data$Na_1_mg_L*Na_ID8A_8B_IC_data$Dilution
Na_ID8A_8B_IC_data$Na_2_mg_L=Na_ID8A_8B_IC_data$Na_2_mg_L*Na_ID8A_8B_IC_data$Dilution
  
Na_ID8A_8B_IC_data <-Na_ID8A_8B_IC_data%>%mutate(Na_mgL=(rowMeans(Na_ID8A_8B_IC_data[,c("Na_1_mg_L","Na_2_mg_L")],na.rm=TRUE)))%>%
                          mutate(Na_std_mgL=(rowSds(as.matrix(Na_ID8A_8B_IC_data[,c("Na_1_mg_L","Na_2_mg_L")],na.rm=TRUE))))%>%
                          mutate(Na_Std_p=((Na_std_mgL/Na_mgL)))

#Imort af Ca_IC data. 
Ca_ID8A_8B_IC_data <- read_excel("data/Pilot_scale/IC_data_pilot.xlsx",4)

old_names_IC=colnames(Ca_ID8A_8B_IC_data) #Vi finder de latterlige navne kolonnerne i dataen har 
new_names_IC=c("Name", "Time","Stream","Dilution","Ca_1_mg_L","Ca_2_mg_L") #Vi finder på nogle lidt bedre nogle
Ca_ID8A_8B_IC_data = Ca_ID8A_8B_IC_data %>% rename_at(vars(old_names_IC),~new_names_IC) #Vi ændrer navnene til de nye
Ca_ID8A_8B_IC_data <- as.data.frame(Ca_ID8A_8B_IC_data)
#noget med gennemsnit. 


Ca_ID8A_8B_IC_data$Ca_1_mg_L=Ca_ID8A_8B_IC_data$Ca_1_mg_L*Ca_ID8A_8B_IC_data$Dilution
Ca_ID8A_8B_IC_data$Ca_2_mg_L=Ca_ID8A_8B_IC_data$Ca_2_mg_L*Ca_ID8A_8B_IC_data$Dilution
  
Ca_ID8A_8B_IC_data <-Ca_ID8A_8B_IC_data%>%mutate(Ca_mgL=(rowMeans(Ca_ID8A_8B_IC_data[,c("Ca_1_mg_L","Ca_2_mg_L")],na.rm=TRUE)))%>%
                          mutate(Ca_std_mgL=(rowSds(as.matrix(Ca_ID8A_8B_IC_data[,c("Ca_1_mg_L","Ca_2_mg_L")],na.rm=TRUE))))%>%
                          mutate(Ca_Std_p=((Ca_std_mgL/Ca_mgL)))


#Imort af Mg_IC data. 
Mg_ID8A_8B_IC_data <- read_excel("data/Pilot_scale/IC_data_pilot.xlsx",5)

old_names_IC=colnames(Mg_ID8A_8B_IC_data) #Vi finder de latterlige navne kolonnerne i dataen har 
new_names_IC=c("Name", "Time","Stream","Dilution","Mg_1_mg_L","Mg_2_mg_L") #Vi finder på nogle lidt bedre nogle
Mg_ID8A_8B_IC_data = Mg_ID8A_8B_IC_data %>% rename_at(vars(old_names_IC),~new_names_IC) #Vi ændrer navnene til de nye
Mg_ID8A_8B_IC_data <- as.data.frame(Mg_ID8A_8B_IC_data)
#noget med gennemsnit. 


Mg_ID8A_8B_IC_data$Mg_1_mg_L=Mg_ID8A_8B_IC_data$Mg_1_mg_L*Mg_ID8A_8B_IC_data$Dilution
Mg_ID8A_8B_IC_data$Mg_2_mg_L=Mg_ID8A_8B_IC_data$Mg_2_mg_L*Mg_ID8A_8B_IC_data$Dilution
  
Mg_ID8A_8B_IC_data <-Mg_ID8A_8B_IC_data%>%mutate(Mg_mgL=(rowMeans(Mg_ID8A_8B_IC_data[,c("Mg_1_mg_L","Mg_2_mg_L")],na.rm=TRUE)))%>%
                          mutate(Mg_std_mgL=(rowSds(as.matrix(Mg_ID8A_8B_IC_data[,c("Mg_1_mg_L","Mg_2_mg_L")],na.rm=TRUE))))%>%
                          mutate(Mg_Std_p=((Mg_std_mgL/Mg_mgL)))

#Imort af K_IC data. 
K_ID8A_8B_IC_data <- read_excel("data/Pilot_scale/IC_data_pilot.xlsx",6)

old_names_IC=colnames(K_ID8A_8B_IC_data) #Vi finder de latterlige navne kolonnerne i dataen har 
new_names_IC=c("Name", "Time","Stream","Dilution","K_1_mg_L","K_2_mg_L") #Vi finder på nogle lidt bedre nogle
K_ID8A_8B_IC_data = K_ID8A_8B_IC_data %>% rename_at(vars(old_names_IC),~new_names_IC) #Vi ændrer navnene til de nye
K_ID8A_8B_IC_data <- as.data.frame(K_ID8A_8B_IC_data)
#noget med gennemsnit. 


K_ID8A_8B_IC_data$K_1_mg_L=K_ID8A_8B_IC_data$K_1_mg_L*K_ID8A_8B_IC_data$Dilution
K_ID8A_8B_IC_data$K_2_mg_L=K_ID8A_8B_IC_data$K_2_mg_L*K_ID8A_8B_IC_data$Dilution
  
K_ID8A_8B_IC_data <-K_ID8A_8B_IC_data%>%mutate(K_mgL=(rowMeans(K_ID8A_8B_IC_data[,c("K_1_mg_L","K_2_mg_L")],na.rm=TRUE)))%>%
                          mutate(K_std_mgL=(rowSds(as.matrix(K_ID8A_8B_IC_data[,c("K_1_mg_L","K_2_mg_L")],na.rm=TRUE))))%>%
                          mutate(K_Std_p=((K_std_mgL/K_mgL)))
#Imort af NO3_IC data. 
NO3_ID8A_8B_IC_data <- read_excel("data/Pilot_scale/IC_data_pilot.xlsx",7)

old_names_IC=colnames(NO3_ID8A_8B_IC_data) #Vi finder de latterlige navne kolonnerne i dataen har 
new_names_IC=c("Name", "Time","Stream","Dilution","NO3_1_mg_L","NO3_2_mg_L") #Vi finder på nogle lidt bedre nogle
NO3_ID8A_8B_IC_data = NO3_ID8A_8B_IC_data %>% rename_at(vars(old_names_IC),~new_names_IC) #Vi ændrer navnene til de nye
NO3_ID8A_8B_IC_data <- as.data.frame(NO3_ID8A_8B_IC_data)
#noget med gennemsnit. 


NO3_ID8A_8B_IC_data$NO3_1_mg_L=NO3_ID8A_8B_IC_data$NO3_1_mg_L*NO3_ID8A_8B_IC_data$Dilution
NO3_ID8A_8B_IC_data$NO3_2_mg_L=NO3_ID8A_8B_IC_data$NO3_2_mg_L*NO3_ID8A_8B_IC_data$Dilution
  
NO3_ID8A_8B_IC_data <-NO3_ID8A_8B_IC_data%>%mutate(NO3_mgL=(rowMeans(NO3_ID8A_8B_IC_data[,c("NO3_1_mg_L","NO3_2_mg_L")],na.rm=TRUE)))%>%
                          mutate(NO3_std_mgL=(rowSds(as.matrix(NO3_ID8A_8B_IC_data[,c("NO3_1_mg_L","NO3_2_mg_L")],na.rm=TRUE))))%>%
                          mutate(NO3_Std_p=((NO3_std_mgL/NO3_mgL)))

#Imort af SiO2 data. 
SiO2_ID8A_8B_IC_data <- read_excel("data/Pilot_scale/IC_data_pilot.xlsx",8)

old_names_IC=colnames(SiO2_ID8A_8B_IC_data) #Vi finder de latterlige navne kolonnerne i dataen har 
new_names_IC=c("Name", "Time","Stream","Dilution","SiO2_mgL") #Vi finder på nogle lidt bedre nogle
SiO2_ID8A_8B_IC_data = SiO2_ID8A_8B_IC_data %>% rename_at(vars(old_names_IC),~new_names_IC) #Vi ændrer navnene til de nye
SiO2_ID8A_8B_IC_data <- as.data.frame(SiO2_ID8A_8B_IC_data)
#noget med gennemsnit. 

SiO2_ID8A_8B_IC_data$SiO2_std <- c(rep(2,34))
SiO2_ID8A_8B_IC_data$SiO2_Std_p <- (SiO2_ID8A_8B_IC_data$SiO2_std/SiO2_ID8A_8B_IC_data$SiO2_mgL)

```

plot of concentraiton in mM 8A

```{R plot conc 8A, echo=FALSE, message=FALSE}


Mw_Cl=35.45
Mw_SO4=96.06
Mw_Ca=40.078
Mw_Na=22.99
Mw_Br=79.904
Mw_Mg=24.305
Mw_K=39.0983
Mw_SiO2=60.08
Mw_NO3=62.0049

ID_8A_8B_data = cbind(Cl_ID8A_8B_IC_data[,c(1:3,7,9)],
                      SO4_ID8A_8B_IC_data[,c(7,9)],
                      Na_ID8A_8B_IC_data[,c(7,9)],
                      Ca_ID8A_8B_IC_data[,c(7,9)],
                      Mg_ID8A_8B_IC_data[,c(7,9)],
                      K_ID8A_8B_IC_data[,c(7,9)],
                      NO3_ID8A_8B_IC_data[,c(7,9)],
                      SiO2_ID8A_8B_IC_data[,c(5,7)])
                      
ID_8A_8B_data$start_vol=c(rep(900,21),rep(800,13))                       
ID_8A_8B_data$perm_vol = ID_8A_8B_data$Time*280
ID_8A_8B_data$Recovery = 100*(1-(ID_8A_8B_data$start_vol-ID_8A_8B_data$perm_vol)/ID_8A_8B_data$start_vol)   

ID_8A_8B_mM=ID_8A_8B_data
ID_8A_8B_mM$Cl_mgL=ID_8A_8B_mM$Cl_mgL/Mw_Cl
ID_8A_8B_mM$SO4_mgL=ID_8A_8B_mM$SO4_mgL/Mw_SO4
ID_8A_8B_mM$Na_mgL=ID_8A_8B_mM$Na_mgL/Mw_Na
ID_8A_8B_mM$Ca_mgL=ID_8A_8B_mM$Ca_mgL/Mw_Ca
ID_8A_8B_mM$Mg_mgL=ID_8A_8B_mM$Mg_mgL/Mw_Mg
ID_8A_8B_mM$K_mgL=ID_8A_8B_mM$K_mgL/Mw_K
ID_8A_8B_mM$NO3_mgL=ID_8A_8B_mM$NO3_mgL/Mw_NO3
ID_8A_8B_mM$SiO2_mgL=ID_8A_8B_mM$SiO2_mgL/Mw_SiO2


plot_8A_Cl=ggplot(ID_8A_8B_mM%>%filter(Name=="ID:8A"), aes(x=Recovery, y=Cl_mgL,color= Stream))+geom_point()+geom_line()+geom_hline(yintercept=0)+
  scale_color_brewer(palette= "Set1")+
geom_errorbar(aes(ymin=Cl_mgL-(Cl_mgL*CL_Std_p), ymax=Cl_mgL+(Cl_mgL*CL_Std_p)), width=5,
                 position=position_dodge(0.05))+
    labs(x="Water Recovery %",y="Concentration [mM]", color="")+ 
  # scale_y_continuous(limits=c(0, 3.5))+
  scale_x_continuous(limits=c(0, 110))+
 ggtitle("ID:8A, Cl")

plot_8A_SO4=ggplot(ID_8A_8B_mM%>%filter(Name=="ID:8A"), aes(x=Recovery, y=SO4_mgL,color= Stream))+geom_point()+geom_line()+geom_hline(yintercept=0)+
  scale_color_brewer(palette= "Set1")+
geom_errorbar(aes(ymin=SO4_mgL-(SO4_mgL*SO4_Std_p), ymax=SO4_mgL+(SO4_mgL*SO4_Std_p)), width=5,
                 position=position_dodge(0.05))+
    labs(x="Water Recovery %",y="Concentration [mM]", color="")+ 
  # scale_y_continuous(limits=c(0, 3.5))+
  scale_x_continuous(limits=c(0, 110))+
 ggtitle("ID:8A, SO4")

plot_8A_Na=ggplot(ID_8A_8B_mM%>%filter(Name=="ID:8A"), aes(x=Recovery, y=Na_mgL,color= Stream))+geom_point()+geom_line()+geom_hline(yintercept=0)+
  scale_color_brewer(palette= "Set1")+
geom_errorbar(aes(ymin=Na_mgL-(Na_mgL*Na_Std_p), ymax=Na_mgL+(Na_mgL*Na_Std_p)), width=5,
                 position=position_dodge(0.05))+
    labs(x="Water Recovery %",y="Concentration [mM]", color="")+ 
  # scale_y_continuous(limits=c(0, 3.5))+
  scale_x_continuous(limits=c(0, 110))+
 ggtitle("ID:8A, Na")

plot_8A_Ca=ggplot(ID_8A_8B_mM%>%filter(Name=="ID:8A"), aes(x=Recovery, y=Ca_mgL,color= Stream))+geom_point()+geom_line()+geom_hline(yintercept=0)+
  scale_color_brewer(palette= "Set1")+
geom_errorbar(aes(ymin=Ca_mgL-(Ca_mgL*Ca_Std_p), ymax=Ca_mgL+(Ca_mgL*Ca_Std_p)), width=5,
                 position=position_dodge(0.05))+
    labs(x="Water Recovery %",y="Concentration [mM]", color="")+ 
  # scale_y_continuous(limits=c(0, 3.5))+
  scale_x_continuous(limits=c(0, 110))+
 ggtitle("ID:8A, Ca")

plot_8A_Mg=ggplot(ID_8A_8B_mM%>%filter(Name=="ID:8A"), aes(x=Recovery, y=Mg_mgL,color= Stream))+geom_point()+geom_line()+geom_hline(yintercept=0)+
  scale_color_brewer(palette= "Set1")+
geom_errorbar(aes(ymin=Mg_mgL-(Mg_mgL*Mg_Std_p), ymax=Mg_mgL+(Mg_mgL*Mg_Std_p)), width=5,
                 position=position_dodge(0.05))+
    labs(x="Water Recovery %",y="Concentration [mM]", color="")+ 
  # scale_y_continuous(limits=c(0, 3.5))+
  scale_x_continuous(limits=c(0, 110))+
 ggtitle("ID:8A, Mg")

plot_8A_K=ggplot(ID_8A_8B_mM%>%filter(Name=="ID:8A"), aes(x=Recovery, y=K_mgL,color= Stream))+geom_point()+geom_line()+geom_hline(yintercept=0)+
  scale_color_brewer(palette= "Set1")+
geom_errorbar(aes(ymin=K_mgL-(K_mgL*K_Std_p), ymax=K_mgL+(K_mgL*K_Std_p)), width=5,
                 position=position_dodge(0.05))+
    labs(x="Water Recovery %",y="Concentration [mM]", color="")+ 
  # scale_y_continuous(limits=c(0, 3.5))+
  scale_x_continuous(limits=c(0, 110))+
 ggtitle("ID:8A, K")

plot_8A_NO3=ggplot(ID_8A_8B_mM%>%filter(Name=="ID:8A"), aes(x=Recovery, y=NO3_mgL,color= Stream))+geom_point()+geom_line()+geom_hline(yintercept=0)+
  scale_color_brewer(palette= "Set1")+
geom_errorbar(aes(ymin=NO3_mgL-(NO3_mgL*NO3_Std_p), ymax=NO3_mgL+(NO3_mgL*NO3_Std_p)), width=5,
                 position=position_dodge(0.05))+
    labs(x="Water Recovery %",y="Concentration [mM]", color="")+ 
  # scale_y_continuous(limits=c(0, 3.5))+
  scale_x_continuous(limits=c(0, 110))+
 ggtitle("ID:8A, NO3")

plot_8A_SiO2=ggplot(ID_8A_8B_mM%>%filter(Name=="ID:8A"), aes(x=Recovery, y=SiO2_mgL,color= Stream))+geom_point()+geom_line()+geom_hline(yintercept=0)+
  scale_color_brewer(palette= "Set1")+
geom_errorbar(aes(ymin=SiO2_mgL-(SiO2_mgL*SiO2_Std_p), ymax=SiO2_mgL+(SiO2_mgL*SiO2_Std_p)), width=5,
                 position=position_dodge(0.05))+
    labs(x="Water Recovery %",y="Concentration [mM]", color="")+ 
  # scale_y_continuous(limits=c(0, 3.5))+
  scale_x_continuous(limits=c(0, 110))+
 ggtitle("ID:8A, SiO2")


ggarrange(plot_8A_Cl, plot_8A_SO4,plot_8A_Na,plot_8A_Ca ,ncol=2, nrow=2, common.legend = TRUE, legend="bottom")#,align = "v")
ggarrange(plot_8A_SiO2, plot_8A_Mg, plot_8A_K,plot_8A_NO3 ,ncol=2, nrow=2, common.legend = TRUE, legend="bottom")#,align = "v")
``` 


```{R plot conc 8B , echo=FALSE, message=FALSE}



plot_8B_Cl=ggplot(ID_8A_8B_mM%>%filter(Name=="ID:8B"), aes(x=Recovery, y=Cl_mgL,color= Stream))+geom_point()+geom_line()+geom_hline(yintercept=0)+
  scale_color_brewer(palette= "Set1")+
geom_errorbar(aes(ymin=Cl_mgL-(Cl_mgL*CL_Std_p), ymax=Cl_mgL+(Cl_mgL*CL_Std_p)), width=5,
                 position=position_dodge(0.05))+
    labs(x="Water Recovery %",y="Concentration [mM]", color="")+ 
  # scale_y_continuous(limits=c(0, 3.5))+
  scale_x_continuous(limits=c(0, 120))+
 ggtitle("ID:8B, Cl")

plot_8B_SO4=ggplot(ID_8A_8B_mM%>%filter(Name=="ID:8B"), aes(x=Recovery, y=SO4_mgL,color= Stream))+geom_point()+geom_line()+geom_hline(yintercept=0)+
  scale_color_brewer(palette= "Set1")+
geom_errorbar(aes(ymin=SO4_mgL-(SO4_mgL*SO4_Std_p), ymax=SO4_mgL+(SO4_mgL*SO4_Std_p)), width=5,
                 position=position_dodge(0.05))+
    labs(x="Water Recovery %",y="Concentration [mM]", color="")+ 
  # scale_y_continuous(limits=c(0, 3.5))+
  scale_x_continuous(limits=c(0, 120))+
 ggtitle("ID:8B, SO4")

plot_8B_Na=ggplot(ID_8A_8B_mM%>%filter(Name=="ID:8B"), aes(x=Recovery, y=Na_mgL,color= Stream))+geom_point()+geom_line()+geom_hline(yintercept=0)+
  scale_color_brewer(palette= "Set1")+
geom_errorbar(aes(ymin=Na_mgL-(Na_mgL*Na_Std_p), ymax=Na_mgL+(Na_mgL*Na_Std_p)), width=5,
                 position=position_dodge(0.05))+
    labs(x="Water Recovery %",y="Concentration [mM]", color="")+ 
  # scale_y_continuous(limits=c(0, 3.5))+
  scale_x_continuous(limits=c(0, 120))+
 ggtitle("ID:8B, Na")

plot_8B_Ca=ggplot(ID_8A_8B_mM%>%filter(Name=="ID:8B"), aes(x=Recovery, y=Ca_mgL,color= Stream))+geom_point()+geom_line()+geom_hline(yintercept=0)+
  scale_color_brewer(palette= "Set1")+
geom_errorbar(aes(ymin=Ca_mgL-(Ca_mgL*Ca_Std_p), ymax=Ca_mgL+(Ca_mgL*Ca_Std_p)), width=5,
                 position=position_dodge(0.05))+
    labs(x="Water Recovery %",y="Concentration [mM]", color="")+ 
  # scale_y_continuous(limits=c(0, 3.5))+
  scale_x_continuous(limits=c(0, 120))+
 ggtitle("ID:8B, Ca")

plot_8B_Mg=ggplot(ID_8A_8B_mM%>%filter(Name=="ID:8B"), aes(x=Recovery, y=Mg_mgL,color= Stream))+geom_point()+geom_line()+geom_hline(yintercept=0)+
  scale_color_brewer(palette= "Set1")+
geom_errorbar(aes(ymin=Mg_mgL-(Mg_mgL*Mg_Std_p), ymax=Mg_mgL+(Mg_mgL*Mg_Std_p)), width=5,
                 position=position_dodge(0.05))+
    labs(x="Water Recovery %",y="Concentration [mM]", color="")+ 
  # scale_y_continuous(limits=c(0, 3.5))+
  scale_x_continuous(limits=c(0, 120))+
 ggtitle("ID:8B, Mg")

plot_8B_K=ggplot(ID_8A_8B_mM%>%filter(Name=="ID:8B"), aes(x=Recovery, y=K_mgL,color= Stream))+geom_point()+geom_line()+geom_hline(yintercept=0)+
  scale_color_brewer(palette= "Set1")+
geom_errorbar(aes(ymin=K_mgL-(K_mgL*K_Std_p), ymax=K_mgL+(K_mgL*K_Std_p)), width=5,
                 position=position_dodge(0.05))+
    labs(x="Water Recovery %",y="Concentration [mM]", color="")+ 
  # scale_y_continuous(limits=c(0, 3.5))+
  scale_x_continuous(limits=c(0, 120))+
 ggtitle("ID:8B, K")

plot_8B_NO3=ggplot(ID_8A_8B_mM%>%filter(Name=="ID:8B"), aes(x=Recovery, y=NO3_mgL,color= Stream))+geom_point()+geom_line()+geom_hline(yintercept=0)+
  scale_color_brewer(palette= "Set1")+
geom_errorbar(aes(ymin=NO3_mgL-(NO3_mgL*NO3_Std_p), ymax=NO3_mgL+(NO3_mgL*NO3_Std_p)), width=5,
                 position=position_dodge(0.05))+
    labs(x="Water Recovery %",y="Concentration [mM]", color="")+ 
  # scale_y_continuous(limits=c(0, 3.5))+
  scale_x_continuous(limits=c(0, 120))+
 ggtitle("ID:8B, NO3")

plot_8B_SiO2=ggplot(ID_8A_8B_mM%>%filter(Name=="ID:8B"), aes(x=Recovery, y=SiO2_mgL,color= Stream))+geom_point()+geom_line()+geom_hline(yintercept=0)+
  scale_color_brewer(palette= "Set1")+
geom_errorbar(aes(ymin=SiO2_mgL-(SiO2_mgL*SiO2_Std_p), ymax=SiO2_mgL+(SiO2_mgL*SiO2_Std_p)), width=5,
                 position=position_dodge(0.05))+
    labs(x="Water Recovery %",y="Concentration [mM]", color="")+ 
  # scale_y_continuous(limits=c(0, 3.5))+
  scale_x_continuous(limits=c(0, 120))+
 ggtitle("ID:8B, SiO2")

ggarrange(plot_8B_Cl, plot_8B_SO4,plot_8B_Na,plot_8B_Ca ,ncol=2, nrow=2, common.legend = TRUE, legend="bottom")#,align = "v")
ggarrange(plot_8B_SiO2, plot_8B_Mg, plot_8B_K,plot_8B_NO3 ,ncol=2, nrow=2, common.legend = TRUE, legend="bottom")#,align = "v")

``` 
Det ligner der er byttet rundt på en perm of feed prøve for 8B 1 h, dem vælger jeg at bytte rundt. 


```{R plot conc 8B ny, echo=FALSE, message=FALSE}
ID_8A_8B_mM_ny=ID_8A_8B_mM
ID_8A_8B_mM_ny[25,-3]=ID_8A_8B_mM[26,-3]
ID_8A_8B_mM_ny[26,-3]=ID_8A_8B_mM[25,-3]

plot_8B_Cl=ggplot(ID_8A_8B_mM_ny%>%filter(Name=="ID:8B"), aes(x=Recovery, y=Cl_mgL,color= Stream))+geom_point()+geom_line()+geom_hline(yintercept=0)+
  scale_color_brewer(palette= "Set1")+
geom_errorbar(aes(ymin=Cl_mgL-(Cl_mgL*CL_Std_p), ymax=Cl_mgL+(Cl_mgL*CL_Std_p)), width=5,
                 position=position_dodge(0.05))+
    labs(x="Water Recovery %",y="Concentration [mM]", color="")+ 
  # scale_y_continuous(limits=c(0, 3.5))+
  scale_x_continuous(limits=c(0, 120))+
 ggtitle("ID:8B, Cl")

plot_8B_SO4=ggplot(ID_8A_8B_mM_ny%>%filter(Name=="ID:8B"), aes(x=Recovery, y=SO4_mgL,color= Stream))+geom_point()+geom_line()+geom_hline(yintercept=0)+
  scale_color_brewer(palette= "Set1")+
geom_errorbar(aes(ymin=SO4_mgL-(SO4_mgL*SO4_Std_p), ymax=SO4_mgL+(SO4_mgL*SO4_Std_p)), width=5,
                 position=position_dodge(0.05))+
    labs(x="Water Recovery %",y="Concentration [mM]", color="")+ 
  # scale_y_continuous(limits=c(0, 3.5))+
  scale_x_continuous(limits=c(0, 120))+
 ggtitle("ID:8B, SO4")

plot_8B_Na=ggplot(ID_8A_8B_mM_ny%>%filter(Name=="ID:8B"), aes(x=Recovery, y=Na_mgL,color= Stream))+geom_point()+geom_line()+geom_hline(yintercept=0)+
  scale_color_brewer(palette= "Set1")+
geom_errorbar(aes(ymin=Na_mgL-(Na_mgL*Na_Std_p), ymax=Na_mgL+(Na_mgL*Na_Std_p)), width=5,
                 position=position_dodge(0.05))+
    labs(x="Water Recovery %",y="Concentration [mM]", color="")+ 
  # scale_y_continuous(limits=c(0, 3.5))+
  scale_x_continuous(limits=c(0, 120))+
 ggtitle("ID:8B, Na")

plot_8B_Ca=ggplot(ID_8A_8B_mM_ny%>%filter(Name=="ID:8B"), aes(x=Recovery, y=Ca_mgL,color= Stream))+geom_point()+geom_line()+geom_hline(yintercept=0)+
  scale_color_brewer(palette= "Set1")+
geom_errorbar(aes(ymin=Ca_mgL-(Ca_mgL*Ca_Std_p), ymax=Ca_mgL+(Ca_mgL*Ca_Std_p)), width=5,
                 position=position_dodge(0.05))+
    labs(x="Water Recovery %",y="Concentration [mM]", color="")+ 
  # scale_y_continuous(limits=c(0, 3.5))+
  scale_x_continuous(limits=c(0, 120))+
 ggtitle("ID:8B, Ca")

plot_8B_Mg=ggplot(ID_8A_8B_mM_ny%>%filter(Name=="ID:8B"), aes(x=Recovery, y=Mg_mgL,color= Stream))+geom_point()+geom_line()+geom_hline(yintercept=0)+
  scale_color_brewer(palette= "Set1")+
geom_errorbar(aes(ymin=Mg_mgL-(Mg_mgL*Mg_Std_p), ymax=Mg_mgL+(Mg_mgL*Mg_Std_p)), width=5,
                 position=position_dodge(0.05))+
    labs(x="Water Recovery %",y="Concentration [mM]", color="")+ 
  # scale_y_continuous(limits=c(0, 3.5))+
  scale_x_continuous(limits=c(0, 120))+
 ggtitle("ID:8B, Mg")

plot_8B_K=ggplot(ID_8A_8B_mM_ny%>%filter(Name=="ID:8B"), aes(x=Recovery, y=K_mgL,color= Stream))+geom_point()+geom_line()+geom_hline(yintercept=0)+
  scale_color_brewer(palette= "Set1")+
geom_errorbar(aes(ymin=K_mgL-(K_mgL*K_Std_p), ymax=K_mgL+(K_mgL*K_Std_p)), width=5,
                 position=position_dodge(0.05))+
    labs(x="Water Recovery %",y="Concentration [mM]", color="")+ 
  # scale_y_continuous(limits=c(0, 3.5))+
  scale_x_continuous(limits=c(0, 120))+
 ggtitle("ID:8B, K")

plot_8B_NO3=ggplot(ID_8A_8B_mM_ny%>%filter(Name=="ID:8B"), aes(x=Recovery, y=NO3_mgL,color= Stream))+geom_point()+geom_line()+geom_hline(yintercept=0)+
  scale_color_brewer(palette= "Set1")+
geom_errorbar(aes(ymin=NO3_mgL-(NO3_mgL*NO3_Std_p), ymax=NO3_mgL+(NO3_mgL*NO3_Std_p)), width=5,
                 position=position_dodge(0.05))+
    labs(x="Water Recovery %",y="Concentration [mM]", color="")+ 
  # scale_y_continuous(limits=c(0, 3.5))+
  scale_x_continuous(limits=c(0, 120))+
 ggtitle("ID:8B, NO3")


plot_8B_SiO2=ggplot(ID_8A_8B_mM_ny%>%filter(Name=="ID:8B"), aes(x=Recovery, y=SiO2_mgL,color= Stream))+geom_point()+geom_line()+geom_hline(yintercept=0)+
  scale_color_brewer(palette= "Set1")+
geom_errorbar(aes(ymin=SiO2_mgL-(SiO2_mgL*SiO2_Std_p), ymax=SiO2_mgL+(SiO2_mgL*SiO2_Std_p)), width=5,
                 position=position_dodge(0.05))+
    labs(x="Water Recovery %",y="Concentration [mM]", color="")+ 
  # scale_y_continuous(limits=c(0, 3.5))+
  scale_x_continuous(limits=c(0, 120))+
 ggtitle("ID:8B, SiO2")

ggarrange(plot_8B_Cl, plot_8B_SO4,plot_8B_Na,plot_8B_Ca ,ncol=2, nrow=2, common.legend = TRUE, legend="bottom")#,align = "v")
ggarrange(plot_8B_SiO2, plot_8B_Mg, plot_8B_K,plot_8B_NO3 ,ncol=2, nrow=2, common.legend = TRUE, legend="bottom")#,align = "v")


``` 
### Rejection

```{R rejection_calc, message=FALSE, include=FALSE}


ID_8A_mM = ID_8A_8B_mM_ny %>% filter(Name == "ID:8A")
ID_8B_mM = ID_8A_8B_mM_ny %>% filter(Name == "ID:8B")

#kun 8A fordi den er nedern. 
ID_8A_feed_1= ID_8A_mM %>% filter(Stream %in%"Feed")
ID_8A_feed=ID_8A_feed_1[-c(1,7,8),]
ID_8A_retentate= ID_8A_mM %>% filter(Stream %in%"Retentate")
ID_8A_retentate=ID_8A_retentate[-c(6),]


ID_8A_Inlet  =  ID_8A_retentate
ID_8A_Inlet$Cl_mgL=(ID_8A_retentate$Cl_mgL[1]+ID_8A_feed$Cl_mgL)/2
ID_8A_Inlet$CL_Std_p=(ID_8A_retentate$CL_Std_p[1]+ID_8A_feed$CL_Std_p)
ID_8A_Inlet$SO4_mgL=(ID_8A_retentate$SO4_mgL[1]+ID_8A_feed$SO4_mgL)/2
ID_8A_Inlet$SO4_Std_p=(ID_8A_retentate$SO4_Std_p[1]+ID_8A_feed$SO4_Std_p)
ID_8A_Inlet$Na_mgL=(ID_8A_retentate$Na_mgL[1]+ID_8A_feed$Na_mgL)/2
ID_8A_Inlet$Na_Std_p=(ID_8A_retentate$Na_Std_p[1]+ID_8A_feed$Na_Std_p)
ID_8A_Inlet$Ca_mgL=(ID_8A_retentate$Ca_mgL[1]+ID_8A_feed$Ca_mgL)/2
ID_8A_Inlet$Ca_Std_p=(ID_8A_retentate$Ca_Std_p[1]+ID_8A_feed$Ca_Std_p)
ID_8A_Inlet$Mg_mgL=(ID_8A_retentate$Mg_mgL[1]+ID_8A_feed$Mg_mgL)/2
ID_8A_Inlet$Mg_Std_p=(ID_8A_retentate$Mg_Std_p[1]+ID_8A_feed$Mg_Std_p)
ID_8A_Inlet$K_mgL=(ID_8A_retentate$K_mgL[1]+ID_8A_feed$K_mgL)/2
ID_8A_Inlet$K_Std_p=(ID_8A_retentate$K_Std_p[1]+ID_8A_feed$K_Std_p)
ID_8A_Inlet$NO3_mgL=(ID_8A_retentate$NO3_mgL[1]+ID_8A_feed$NO3_mgL)/2
ID_8A_Inlet$NO3_Std_p=(ID_8A_retentate$NO3_Std_p[1]+ID_8A_feed$NO3_Std_p)
ID_8A_Inlet$SiO2_mgL=(ID_8A_retentate$SiO2_mgL[1]+ID_8A_feed$SiO2_mgL)/2
ID_8A_Inlet$SiO2_Std_p=(ID_8A_retentate$SiO2_Std_p[1]+ID_8A_feed$SiO2_Std_p)


ID_8A_Inlet=rbind(ID_8A_Inlet,ID_8A_feed_1[7,])
#men så er SIO2 blevet glemt for 3H så den regner vi lige og sætter ind. 
ID_8A_Inlet$SiO2_mgL[6]= (ID_8A_mM$SiO2_mgL[17]+ID_8A_mM$SiO2_mgL[18])/2
ID_8A_Inlet$SiO2_Std_p[6]= (ID_8A_mM$SiO2_Std_p[17]+ID_8A_mM$SiO2_Std_p[18])/2

ID_8A_perm= ID_8A_mM %>% filter(Stream %in%"Permeate")

#kun 8B
ID_8A_8B_Feed=rbind(ID_8A_Inlet,ID_8B_mM[-c(1,12,13),]%>%filter(Stream== "Feed" ))
ID_8A_8B_perm=rbind(ID_8A_mM[-21,]%>%filter(Stream== "Permeate" ),
                    ID_8B_mM[-13,]%>%filter(Stream== "Permeate" ))


ID_8A_8B_rej=cbind(ID_8A_8B_Feed[,-3],ID_8A_8B_perm[,-c(1:3,20:23)])
colnames(ID_8A_8B_rej) <- c('Name','Time','Cl_Feed','Cl_Feed_Std_p','SO4_Feed','SO4_Feed_Std_p','Na_Feed','Na_Feed_Std_p','Ca_Feed','Ca_Feed_Std_p','Mg_Feed','Mg_Feed_Std_p','K_Feed','K_Feed_Std_p','NO3_Feed','NO3_Feed_Std_p','SiO2_Feed','SiO2_Feed_Std_p','start_vol', 'perm_vol','Recovery',
                       'Cl_perm','Cl_perm_std_p','SO4_perm','SO4_perm_std_p','Na_perm','Na_perm_std_p','Ca_perm','Ca_perm_std_p','Mg_perm','Mg_perm_std_p','K_perm','K_perm_std_p','NO3_perm','NO3_perm_std_p','SiO2_perm','SiO2_perm_std_p')


ID_8A_8B_rej=ID_8A_8B_rej%>%mutate("rej_Cl"=((1-(Cl_perm/Cl_Feed))*100))
ID_8A_8B_rej=ID_8A_8B_rej%>%mutate("rej_SO4"=((1-(SO4_perm/SO4_Feed))*100))
ID_8A_8B_rej=ID_8A_8B_rej%>%mutate("rej_Na"=((1-(Na_perm/Na_Feed))*100))
ID_8A_8B_rej=ID_8A_8B_rej%>%mutate("rej_Ca"=((1-(Ca_perm/Ca_Feed))*100))
ID_8A_8B_rej=ID_8A_8B_rej%>%mutate("rej_Mg"=((1-(Mg_perm/Mg_Feed))*100))
ID_8A_8B_rej=ID_8A_8B_rej%>%mutate("rej_K"=((1-(K_perm/K_Feed))*100))
ID_8A_8B_rej=ID_8A_8B_rej%>%mutate("rej_NO3"=((1-(NO3_perm/NO3_Feed))*100))
ID_8A_8B_rej=ID_8A_8B_rej%>%mutate("rej_SiO2"=((1-(SiO2_perm/SiO2_Feed))*100))

ID_8A_8B_rej=ID_8A_8B_rej%>%mutate("rej_Cl_std"=(Cl_Feed_Std_p+Cl_perm_std_p))
ID_8A_8B_rej=ID_8A_8B_rej%>%mutate("rej_SO4_std"=(SO4_Feed_Std_p+SO4_perm_std_p))
ID_8A_8B_rej=ID_8A_8B_rej%>%mutate("rej_Na_std"=(Na_Feed_Std_p+Na_perm_std_p))
ID_8A_8B_rej=ID_8A_8B_rej%>%mutate("rej_Ca_std"=(Ca_Feed_Std_p+Ca_perm_std_p))
ID_8A_8B_rej=ID_8A_8B_rej%>%mutate("rej_Mg_std"=(Mg_Feed_Std_p+Mg_perm_std_p))
ID_8A_8B_rej=ID_8A_8B_rej%>%mutate("rej_K_std"=(K_Feed_Std_p+K_perm_std_p)    )                               
ID_8A_8B_rej=ID_8A_8B_rej%>%mutate("rej_NO3_std"=(NO3_Feed_Std_p+NO3_perm_std_p))
ID_8A_8B_rej=ID_8A_8B_rej%>%mutate("rej_SiO2_std"=(SiO2_Feed_Std_p+SiO2_perm_std_p))
                                                             
 

ID_8A_8B_rej_plot = ID_8A_8B_rej%>%gather(key,value, rej_Cl,rej_SO4,rej_Na,rej_Ca,rej_Mg,rej_K, rej_NO3,rej_SiO2)
ID_8A_8B_rej_plot_std_p=c(ID_8A_8B_rej$rej_Cl_std,
                   ID_8A_8B_rej$rej_SO4_std,
                   ID_8A_8B_rej$rej_Na_std,
                   ID_8A_8B_rej$rej_Ca_std,
                   ID_8A_8B_rej$rej_Mg_std,
                   ID_8A_8B_rej$rej_K_std,
                   ID_8A_8B_rej$rej_NO3_std, 
                   ID_8A_8B_rej$rej_SiO2_std)
                   

ID_8A_8B_rej_plot$rej_std_p=ID_8A_8B_rej_plot_std_p

```


ALLE IONER, når punkter mangler er det fordi de ikke kunnes måles på IC. 

```{R plot alle ioner, echo=FALSE, message=FALSE}


plot_8A= ggplot()+
  geom_line(data=ID_8A_8B_rej_plot%>%filter(Name=="ID:8A"), aes(x=Recovery, y=value,color= key))+
  geom_point(data=ID_8A_8B_rej_plot%>%filter(Name=="ID:8A"), aes(x=Recovery, y=value,color= key))+
  geom_hline(yintercept=0)+
  scale_color_brewer(palette= "Set1")+
 geom_errorbar(data=ID_8A_8B_rej_plot%>%filter(Name=="ID:8A"),aes(x=Recovery, ymin=value-(value*rej_std_p), ymax=value+(value*rej_std_p),color= key), width=4,
                 position=position_dodge(0.05))+
      labs(x="Water Recovery %",y="Rejection %", color="")+  
  scale_y_continuous(limits=c(-60, 110), breaks=c(-60,-40,-20, 0, 20, 40,60,80,100 ))+
  scale_x_continuous(limits=c(0, 95), breaks=c(20, 40,60,80 ))+
  ggtitle("ID:8A")

plot_8B= ggplot()+
  geom_line(data=ID_8A_8B_rej_plot%>%filter(Name=="ID:8B"), aes(x=Recovery, y=value,color= key))+
  geom_point(data=ID_8A_8B_rej_plot%>%filter(Name=="ID:8B"), aes(x=Recovery, y=value,color= key))+
  geom_hline(yintercept=0)+
  scale_color_brewer(palette= "Set1")+
 geom_errorbar(data=ID_8A_8B_rej_plot%>%filter(Name=="ID:8B"),aes(x=Recovery, ymin=value-(value*rej_std_p), ymax=value+(value*rej_std_p),color= key), width=4,
                 position=position_dodge(0.05))+
      labs(x="Water Recovery %",y="Rejection %", color="")+  
  scale_y_continuous(limits=c(-60, 110), breaks=c(-60,-40,-20, 0, 20, 40,60,80,100 ))+
  scale_x_continuous(limits=c(0, 95), breaks=c(20, 40,60,80 ))+
  ggtitle("ID:8B")


ggarrange(plot_8A, plot_8B, ncol=2, nrow=1, common.legend = TRUE, legend="bottom")#,align = "v")

``` 

vigtige IONER 

```{R plot nice ioner, echo=FALSE, message=FALSE}

ID_8A_8B_rej_plot_2 = ID_8A_8B_rej%>%gather(key,value, rej_Cl,rej_SO4,rej_Na,rej_Ca,rej_SiO2)
plot_2_std_p=c(ID_8A_8B_rej$rej_Cl_std,
                   ID_8A_8B_rej$rej_SO4_std,
                   ID_8A_8B_rej$rej_Na_std,
                   ID_8A_8B_rej$rej_Ca_std, 
               ID_8A_8B_rej$rej_SiO2_std)
                   

ID_8A_8B_rej_plot_2$rej_std_p=plot_2_std_p

plot_8A= ggplot()+
  geom_line(data=ID_8A_8B_rej_plot_2%>%filter(Name=="ID:8A"), aes(x=Recovery, y=value,color= key))+
  geom_point(data=ID_8A_8B_rej_plot_2%>%filter(Name=="ID:8A"), aes(x=Recovery, y=value,color= key))+
  geom_hline(yintercept=0)+
  scale_color_brewer(palette= "Set1")+
 geom_errorbar(data=ID_8A_8B_rej_plot_2%>%filter(Name=="ID:8A"),aes(x=Recovery, ymin=value-(value*rej_std_p), ymax=value+(value*rej_std_p),color= key), width=4,
                 position=position_dodge(0.05))+
  #geom_point(data=rej_SiO2%>%filter(name=="ID:1"), aes(x=Recovery, y=rej_SiO2,color='rej_SiO2'))+
 #geom_line(data=rej_SiO2%>%filter(name=="ID:1"), aes(x=Recovery, y=rej_SiO2,color='rej_SiO2'))+
  #geom_errorbar(data=rej_SiO2%>%filter(name=="ID:1"),aes(x=Recovery,ymin=rej_SiO2-(rej_SiO2*SiO2_rej_std_p), ymax=rej_SiO2+(rej_SiO2*SiO2_rej_std_p),color='rej_SiO2'), width=1,
    #             position=position_dodge(0.05))+
      labs(x="Water Recovery %",y="Rejection %", color="")+  
  scale_y_continuous(limits=c(-50, 100), breaks=c(-40,-20, 0, 20, 40,60,80,100 ))+
  scale_x_continuous(limits=c(0, 95), breaks=c(20, 40,60,80 ))+
  ggtitle("ID:8A")

plot_8B= ggplot()+
  geom_line(data=ID_8A_8B_rej_plot_2%>%filter(Name=="ID:8B"), aes(x=Recovery, y=value,color= key))+
  geom_point(data=ID_8A_8B_rej_plot_2%>%filter(Name=="ID:8B"), aes(x=Recovery, y=value,color= key))+
  geom_hline(yintercept=0)+
  scale_color_brewer(palette= "Set1")+
 geom_errorbar(data=ID_8A_8B_rej_plot_2%>%filter(Name=="ID:8B"),aes(x=Recovery, ymin=value-(value*rej_std_p), ymax=value+(value*rej_std_p),color= key), width=4,
                 position=position_dodge(0.05))+
  #geom_point(data=rej_SiO2%>%filter(name=="ID:1"), aes(x=Recovery, y=rej_SiO2,color='rej_SiO2'))+
 #geom_line(data=rej_SiO2%>%filter(name=="ID:1"), aes(x=Recovery, y=rej_SiO2,color='rej_SiO2'))+
  #geom_errorbar(data=rej_SiO2%>%filter(name=="ID:1"),aes(x=Recovery,ymin=rej_SiO2-(rej_SiO2*SiO2_rej_std_p), ymax=rej_SiO2+(rej_SiO2*SiO2_rej_std_p),color='rej_SiO2'), width=1,
    #             position=position_dodge(0.05))+
      labs(x="Water Recovery %",y="Rejection %", color="")+  
  scale_y_continuous(limits=c(-50, 100), breaks=c(-40,-20, 0, 20, 40,60,80,100 ))+
  scale_x_continuous(limits=c(0, 95), breaks=c(20, 40,60,80 ))+
  ggtitle("ID:8B")


ggarrange(plot_8A, plot_8B, ncol=2, nrow=1, common.legend = TRUE, legend="bottom")#,align = "v")

subplot(ggplotly(plot_8A),ggplotly(plot_8B),nrows = 1)

``` 
```{R Concentration mM, echo=FALSE, message=FALSE}


ID_8A_mM = ID_8A_8B_mM_ny %>% filter(Name == "ID:8A")
ID_8B_mM = ID_8A_8B_mM_ny %>% filter(Name == "ID:8B")

Rejection_total_8A = (1-(ID_8A_mM[21,c(4,6,8,10,12,14,16,18)]/ID_8A_mM[1,c(4,6,8,10,12,14,16,18)]))*100
Rejection_total_8B = (1-(ID_8B_mM[13,c(4,6,8,10,12,14,16,18)]/ID_8B_mM[1,c(4,6,8,10,12,14,16,18)]))*100

Rejection_total=(1-(ID_8B_mM[13,c(4,6,8,10,12,14,16,18)]/ID_8A_mM[1,c(4,6,8,10,12,14,16,18)]))*100

Rejection_total_g=(1-(ID_8B_mM[13,c(4,6,8,10,12,14,16,18)]/ID_8A_mM[1,c(4,6,8,10,12,14,16,18)]))*100

Cl_g_rej=(1-((ID_8B_mM$Cl_mgL[13]/1000*Mw_Cl*800*0.875)
             /(ID_8A_mM$Cl_mgL[1]/1000*Mw_Cl*900)))*100

Mw_row=c(Mw_Cl, Mw_SO4, Mw_Na, Mw_Ca, Mw_Mg, Mw_K, Mw_NO3, Mw_SiO2)

Rejection_total_g=(1-((ID_8B_mM[13,c(4,6,8,10,12,14,16,18)]/1000*Mw_row*800*0.875)/(ID_8A_mM[1,c(4,6,8,10,12,14,16,18)]/1000*Mw_row*900)))*100


mol_udvikling= rbind(ID_8A_mM[1,c(4,6,8,10,12,14,16,18)]/1000*900, ID_8A_mM[21,c(4,6,8,10,12,14,16,18)]/1000*800,ID_8B_mM[1,c(4,6,8,10,12,14,16,18)]/1000*800, ID_8B_mM[13,c(4,6,8,10,12,14,16,18)]/1000*800*0.875 )
colnames(mol_udvikling) <- c("Cl", "SO4", "Na", "Ca", "Mg","K","NO3", "SiO2")

mol_udvikling$Stream=c("8A Feed","8A Permeat","8B Feed","8B Permeat")

mol_udvikling_plot = mol_udvikling%>%gather(key,value, Cl, SO4, Na, Ca, SiO2)
                                            
                                            

ion_plot=ggplot(mol_udvikling_plot, aes(x=Stream, y=value, color=key)) +geom_bar()


ion_plot_bar=ggplot(mol_udvikling_plot, aes(x=key, y=value, fill=Stream, )) +geom_bar(stat="identity",width = 0.5, position=position_dodge())+ labs(x="Ion",y="mol")+  
  #scale_y_continuous(limits=c(-50, 100), breaks=c(-40,-20, 0, 20, 40,60,80,100 ))+
  #scale_x_continuous(limits=c(0, 95), breaks=c(20, 40,60,80 ))+
  ggtitle("ID:8A/8B")

ion_plot_bar

```


