---
title: "Single_salt:IC"
author: "lærke"
date: "14/01/2022"
output: html_document
editor_options: 
  markdown: 
    wrap: 72
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
#Loading af pakker 
library(plyr)
library(dplyr)
library(tidyr)
library(ggplot2)
library(visdat)
library(GGally)
library(Hmisc)
library(DMwR2)
library(data.table)
library(mltools)
library(ggfortify)
library(ggiraphExtra)
library(coronavirus)
library(lubridate)
library(plotly)
library(readxl)
require(readr)
library(zoo)
library(latex2exp)
library(fs)
library(plyr)
library(matrixStats)
library(haven)
library(sjmisc)

colors = c(
    '#1f77b4',  # muted blue
    '#ff7f0e',  # safety orange
    '#2ca02c',  # cooked asparagus green
    '#d62728',  # brick red
    '#9467bd',  # muted purple
    '#8c564b',  # chestnut brown
    '#e377c2',  # raspberry yogurt pink
    '#7f7f7f',  # middle gray
    '#bcbd22',  # curry yellow-green
    '#17becf'   # blue-teal
)

```
### Salt data
#### NaCl
```{R NaCl plot IC data, echo=FALSE, message=FALSE}

NaCl_IC_data <- read_excel("data/NaCl_IC_analyse_test.xlsx")
str(NaCl_IC_data)


old_names_IC=colnames(NaCl_IC_data) #Vi finder de latterlige navne kolonnerne i dataen har 
new_names_IC=c("time","Sodium","Chloride","Stream") #Vi finder på nogle lidt bedre nogle
NaCl_IC_data = NaCl_IC_data %>% rename_at(vars(old_names_IC),~new_names_IC) #Vi ændrer navnene til de nye
NaCl_IC_data <- as.data.frame(NaCl_IC_data)


NaCl_Permeate <- filter(NaCl_IC_data, Stream=="Permeate")
NaCl_Feed <- filter(NaCl_IC_data, Stream=="Feed")
NaCl_Retentate <- filter(NaCl_IC_data, Stream=="Retentate")   

NaCl_rej_Cl <- (1-(NaCl_Permeate$Chloride[-6]/((NaCl_Feed$Chloride[-1]+NaCl_Retentate$Chloride)/2)))*100
NaCl_rej_Na <- (1-(NaCl_Permeate$Sodium[-6]/((NaCl_Feed$Sodium[-1]+NaCl_Retentate$Sodium)/2)))*100

fig_NaCl_Cl <- plot_ly(data=NaCl_IC_data[1:16,], x=~time/6*100,
          y=~(Chloride/35.45),
         color=~Stream,
          type='scatter',mode='lines+markers',
          colors=c(colors[1],colors[2],colors[3]),
         showlegend=FALSE)  %>%
      layout(
         yaxis=list(title="Concentration Chloride [mM]", range=c(0,4)),
         xaxis=list(title="Water Recovery [%]")) 

fig_NaCl_Na <- plot_ly(data=NaCl_IC_data[1:16,], x=~time/6*100,
          y=~(Sodium/22.99),
         color=~Stream,
          type='scatter',mode='lines+markers',
          colors=c(colors[1],colors[2],colors[3]))  %>%
      layout(
         yaxis=list(title="Concentration Sodium [mM]",range=c(0,4)),
         xaxis=list(title="Water Recovery [%]")) 

fig_NaCl_conc <- subplot(fig_NaCl_Cl, fig_NaCl_Na, nrows=1,titleY=TRUE,titleX=TRUE,margin=0.1)
fig_NaCl_conc


fig_NaCl <- plot_ly(x=~NaCl_Feed$time[-1]/6*100,
          y=~NaCl_rej_Na,
          type='scatter',mode='lines+markers',
          colors=colors[1], name = "NaCl Na")  %>%
  add_trace(x=~NaCl_Feed$time[-1]/6*100,
          y=~NaCl_rej_Cl,
        type='scatter',mode='lines+markers',
          colors=colors[2], name = "NaCl Cl")  %>%
     layout(
       #title="Rejection NaCl",
         yaxis=list(title="Rejection %",range=c(0,100)),
         xaxis=list(title="Water Recovery [%]")) 
#fig_NaCl


Data=cbind(NaCl_IC_data%>%filter(Stream=="Feed"),NaCl_IC_data%>%filter(Stream=="Permeate")%>%select(c(2,3)))
colnames(Data)=c("time","f_Na","f_Cl","exp","p_Na","p_Cl")
Data[7,]=NA
Data$time[7]=4.5
Data$p_Na[2:7]=Data$p_Na[1:6]
Data$p_Cl[2:7]=Data$p_Cl[1:6]
Data$p_Cl[1]=Data$p_Na[1]=NA
Data$exp="NaCl"
Data$Rej_Na=c(NA,NaCl_rej_Na,NA)
Data$Rej_Cl=c(NA,NaCl_rej_Cl,NA)
Data$f_Ca=NA
Data$p_Ca=NA
Data$f_SiO2=NA
Data$p_SiO2=NA
Data$Rej_Ca=NA
Data$Rej_SiO2=NA
```

#### CaCl2
```{R CaCl2 plot IC data, echo=FALSE, message=FALSE}

CaCl2_IC_data <- read_excel("data/NaCl_IC_analyse_test.xlsx",2)
str(CaCl2_IC_data)


old_names_IC_CaCl2=colnames(CaCl2_IC_data) #Vi finder de latterlige navne kolonnerne i dataen har 
new_names_IC_CaCl2=c("time","Calcium","Chloride","Stream") #Vi finder på nogle lidt bedre nogle
CaCl2_IC_data = CaCl2_IC_data %>% rename_at(vars(old_names_IC_CaCl2),~new_names_IC_CaCl2) #Vi ændrer navnene til de nye
CaCl2_IC_data <- as.data.frame(CaCl2_IC_data)

CaCl2_Permeate <- filter(CaCl2_IC_data, Stream=="Permeate")
CaCl2_Feed <- filter(CaCl2_IC_data, Stream=="Feed")
CaCl2_Retentate <- filter(CaCl2_IC_data, Stream=="Retentate")   

CaCl2_rej_Cl <- (1-(CaCl2_Permeate$Chloride[-6]/((CaCl2_Feed$Chloride[-1]+CaCl2_Retentate$Chloride)/2)))*100

CaCl2_rej_Ca <- (1-(CaCl2_Permeate$Calcium[-6]/((CaCl2_Feed$Calcium[-1]+CaCl2_Retentate$Calcium)/2)))*100

fig_CaCl2_Cl <- plot_ly(data=CaCl2_IC_data[1:16,], x=~time/6*100,
          y=~(Chloride/35.45),
         color=~Stream,
          type='scatter',mode='lines+markers',
          colors=c(colors[1],colors[2],colors[3]),
         showlegend=FALSE)  %>%
      layout(yaxis=list(title="Concentration Chloride [mM]", range=c(0,10)),
         xaxis=list(title="Water Recovery [%]")) 

fig_CaCl2_Ca <- plot_ly(data=CaCl2_IC_data[1:16,], x=~time/6*100,
          y=~(Calcium/40.078),
         color=~Stream,
          type='scatter',mode='lines+markers',
          colors=c(colors[1],colors[2],colors[3]))  %>%
      layout(
         yaxis=list(title="Concentration Calcium [mM]",range=c(0,10)),
         xaxis=list(title="Water Recovery [%]")) 

fig_CaCl2_conc <- subplot(fig_CaCl2_Cl, fig_CaCl2_Ca, nrows=1,titleY=TRUE,titleX=TRUE,margin=0.1)
fig_CaCl2_conc

fig_CaCL2 <- plot_ly(x=~CaCl2_Feed$time[-1]/6*100,
          y=~CaCl2_rej_Ca,
          type='scatter',mode='lines+markers',
          colors=colors[1], name = "CaCl2 Ca")  %>%
  add_trace(x=~CaCl2_Feed$time[-1]/6*100,
          y=~CaCl2_rej_Cl,
        type='scatter',mode='lines+markers',
          colors=colors[2], name = "CaCl2 Cl")  %>%
     layout(
       #title="Rejection CaCl2",
         yaxis=list(title="Rejection %",range=c(0,100)),
         xaxis=list(title="Water Recovery [%]")) 
#fig_CaCL2

cacl2=cbind(CaCl2_IC_data%>%filter(Stream=="Feed"),CaCl2_IC_data%>%filter(Stream=="Permeate"))
cacl2=cacl2[,c(1,2,3,4,6,7)]
colnames(cacl2)=c("time","f_Ca","f_Cl","exp","p_Ca","p_Cl")

tst=Data
tst[,]=NA

tst$time=c(cacl2$time,4.5)


tst$exp="CaCl2"
tst$f_Cl=c(cacl2$f_Cl,NA)
tst$p_Cl=c(NA,cacl2$p_Cl)
tst$f_Ca=c(cacl2$f_Ca,NA)
tst$p_Ca=c(NA,cacl2$p_Ca)
tst$Rej_Ca=c(NA,CaCl2_rej_Ca,NA)
tst$Rej_Cl=c(NA,CaCl2_rej_Cl,NA)

SS=rbind(Data,tst)






```
#### SiO2
```{R SIO2 plot IC data, echo=FALSE, message=FALSE}

SiO2_IC_data <- read_excel("data/NaCl_IC_analyse_test.xlsx",3)
str(SiO2_IC_data)


old_names_IC_SiO2=colnames(SiO2_IC_data) #Vi finder de latterlige navne kolonnerne i dataen har 
new_names_IC_SiO2=c("time","Silica","Sodium","Stream") #Vi finder på nogle lidt bedre nogle
SiO2_IC_data = SiO2_IC_data %>% rename_at(vars(old_names_IC_SiO2),~new_names_IC_SiO2) #Vi ændrer navnene til de nye
SiO2_IC_data <- as.data.frame(SiO2_IC_data)

SiO2_Permeate <- filter(SiO2_IC_data, Stream=="Permeate")
SiO2_Feed <- filter(SiO2_IC_data, Stream=="Feed")
SiO2_Retentate <- filter(SiO2_IC_data, Stream=="Retentate")   

SiO2_rej_Si<- (1-(SiO2_Permeate$Silica[-6]/((SiO2_Feed$Silica[-1]+SiO2_Retentate$Silica)/2)))*100

SiO2_rej_Na <- (1-(SiO2_Permeate$Sodium[-6]/((SiO2_Feed$Sodium[-1]+SiO2_Retentate$Sodium)/2)))*100

fig_SiO2_Si <- plot_ly(data=SiO2_IC_data[1:16,], x=~time/6*100,
          y=~(Silica/60.08),
         color=~Stream,
          type='scatter',mode='lines+markers',
          colors=c(colors[1],colors[2],colors[3]),
         showlegend=FALSE)  %>%
      layout(yaxis=list(title="Concentration Silica [mM]",range=c(0,3)),
         xaxis=list(title="Water Recovery [%]")) 

fig_SiO2_Na <- plot_ly(data=SiO2_IC_data[1:16,], x=~time/6*100,
          y=~(Sodium/22.99),
         color=~Stream,
          type='scatter',mode='lines+markers',
          colors=c(colors[1],colors[2],colors[3]))  %>%
      layout(
         yaxis=list(title="Concentration Sodium [mM]",range=c(0,3)),
         xaxis=list(title="Water Recovery [%]")) 

fig_SiO2_conc <- subplot(fig_SiO2_Si, fig_SiO2_Na, nrows=1,titleY=TRUE,titleX=TRUE,margin=0.1)
fig_SiO2_conc


fig_SiO2 <- plot_ly(x=~SiO2_Feed$time[-1]/6*100,
          y=~SiO2_rej_Na,
          type='scatter',mode='lines+markers',
          colors=colors[1], name = "SiO2 Na")  %>%
  add_trace(x=~SiO2_Feed$time[-1]/6*100,
          y=~SiO2_rej_Si,
        type='scatter',mode='lines+markers',
          colors=colors[2], name = "SiO2")  %>%
     layout(
       #title="Rejection Na2OSIO2",
         yaxis=list(title="Rejection %",range=c(0,100)),
         xaxis=list(title="Water Recovery [%]")) 

#fig_SiO2
sio2=cbind(SiO2_IC_data%>%filter(Stream=="Feed"),SiO2_IC_data%>%filter(Stream=="Permeate"))
sio2=sio2[,c(1,2,3,4,6,7)]
colnames(sio2)=c("time","f_SiO2","f_Na","exp","p_SiO2","p_Na")

tst2=Data
tst2[,]=NA

tst2$time=c(sio2$time,4.5)
tst2$exp="SiO2"
tst2$f_SiO2=c(sio2$f_SiO2,NA)
tst2$p_SiO2=c(NA,sio2$p_SiO2)
tst2$f_Na=c(sio2$f_Na,NA)
tst2$p_Na=c(NA,sio2$p_Na)
tst2$Rej_SiO2=c(NA,SiO2_rej_Si,NA)
tst2$Rej_Na=c(NA,SiO2_rej_Na,NA)



```
#### MgSO4

```{r MgSO4, echo=FALSE, warning=FALSE}

#data fra MgSO4 forsøg ikke ICR. 

Mg_IC_data <- read_excel("data/ICR/IC_data_ICR_udvalgtdata_igen.xlsx",5)

old_names_IC=colnames(Mg_IC_data) #Vi finder de latterlige navne kolonnerne i dataen har 
new_names_IC=c("time","Stream","Dilution","Mg_1_mg/L","Mg_2_mg/L") #Vi finder på nogle lidt bedre nogle
Mg_IC_data = Mg_IC_data %>% rename_at(vars(old_names_IC),~new_names_IC) #Vi ændrer navnene til de nye
Mg_IC_data <- as.data.frame(Mg_IC_data)
#noget med gennemsnit. 

Mg_IC_data <-Mg_IC_data%>%mutate(avg_mgL=(rowMeans(Mg_IC_data[,c("Mg_1_mg/L","Mg_2_mg/L")],na.rm=TRUE)))%>%
mutate(std_mgL=(rowSds(as.matrix(Mg_IC_data[,c("Mg_1_mg/L","Mg_2_mg/L")],na.rm=TRUE))))


SO4_IC_data <- read_excel("data/ICR/IC_data_ICR_udvalgtdata_igen.xlsx",2)

old_names_IC=colnames(SO4_IC_data) #Vi finder de latterlige navne kolonnerne i dataen har 
new_names_IC=c("time","Stream","Dilution","SO4_1_mg/L","SO4_2_mg/L") #Vi finder på nogle lidt bedre nogle
SO4_IC_data = SO4_IC_data %>% rename_at(vars(old_names_IC),~new_names_IC) #Vi ændrer navnene til de nye
SO4_IC_data <- as.data.frame(SO4_IC_data)
#noget med gennemsnit. 

SO4_IC_data <-SO4_IC_data%>%mutate(avg_mgL=(rowMeans(SO4_IC_data[,c("SO4_1_mg/L","SO4_2_mg/L")],na.rm=TRUE)))%>%
                          mutate(std_mgL=(rowSds(as.matrix(SO4_IC_data[,c("SO4_1_mg/L","SO4_2_mg/L")],na.rm=TRUE))))%>%mutate(Std_p=((std_mgL/avg_mgL)*100))
SO4_IC_data <- SO4_IC_data[-c(1:36),]
SO4_IC_data[is.na(SO4_IC_data)]=0
SO4_IC_data$Stream[1:3] = c("Feed","Feed","Feed")
SO4_IC_data$Stream[4:6] = "Permeate"

MgSO4 = Mg_IC_data[,c(1,2,6,7)]
MgSO4 = cbind(MgSO4,SO4_IC_data[,6:8])
colnames(MgSO4)=c("time","stream","Mg_avg","Mg_std","SO4_avg","SO4_std","SO4_std%")
MgSO4 = MgSO4%>%mutate("Mg_std%" = Mg_std/Mg_avg*100)
MgSO4_feed = MgSO4%>%filter(stream=="Feed")%>%select(c(1,2,3,5,7,8))
MgSO4_perm = MgSO4%>%filter(stream=="Permeate")%>%select(c(1,2,3,5,7,8))
MgSO4_rej = 1-(MgSO4_perm[,c(3:4)]/MgSO4_feed[,c(3:4)])
MgSO4_rej = cbind(MgSO4[1:3,c(1,2)],MgSO4_rej)

#Standardafvigelser



MgSO4_rej$Mg_std_p = (MgSO4_perm$`Mg_std%`+MgSO4_feed$`Mg_std%`)/100
MgSO4_rej$SO4_std_p = (MgSO4_perm$`SO4_std%`+MgSO4_feed$`SO4_std%`)/100
MgSO4_rej = MgSO4_rej%>%mutate(Mg_std = abs(`Mg_std_p`*Mg_avg*100))
MgSO4_rej = MgSO4_rej%>%mutate(SO4_std = abs(SO4_std_p*SO4_avg*100))

#Ca_rej_std_p <- (Ca_perm$Std_p+Ca_feed$Std_p[c(2:16)])/100
#Ca_rej_std <- abs(Ca_rej_std_p*Ca_rej)



fig_MgSO4 <- plot_ly(x=~MgSO4_rej$time/60,
          y=~MgSO4_rej$Mg_avg*100,
          type='scatter',mode='lines+markers',
          colors=colors[1], name = "MgSO4 Mg",
        error_y = list(array = MgSO4_rej$Mg_std))%>%
  add_trace(x=~MgSO4_rej$time/60,
          y=~MgSO4_rej$SO4_avg*100,
        type='scatter',mode='lines+markers',
          colors=colors[2], name = "MgSO4 SO4",
        error_y = list(array = MgSO4_rej$SO4_std))  %>%
     layout(
       #title="Rejection CaCl2",
         yaxis=list(title="Rejection %",range=c(0,100)),
         xaxis=list(title="Time [h]")) 
fig_MgSO4


```



### Samlet Rejection
```{R Summary Rjection, echo=FALSE, message=FALSE}

fig_cations <- plot_ly(x=~NaCl_Feed$time[-1],
          y=~NaCl_rej_Na,
          type='scatter',mode='lines+markers',
          colors=colors[1], name = "NaCl Na") %>%
      add_trace(x=~CaCl2_Feed$time[-1],
          y=~CaCl2_rej_Ca,
          type='scatter',mode='lines+markers',
          colors=colors[2], name = "CaCl2 Ca") %>%
      add_trace(x=~SiO2_Feed$time[-1],
          y=~SiO2_rej_Na,
          type='scatter',mode='lines+markers',
          colors=colors[3], name = "SiO2 Na") %>%
    layout( yaxis=list(title="Rejection Cations %",range=c(0,100)),
         xaxis=list(title="Time [h]"))
#fig_cations  

 

      
fig_anions <- plot_ly(x=~NaCl_Feed$time[-1],
          y=~NaCl_rej_Cl,
          type='scatter',mode='lines+markers',
          colors=colors[1], name = "NaCl Cl") %>%
      add_trace(x=~CaCl2_Feed$time[-1],
          y=~CaCl2_rej_Cl,
          type='scatter',mode='lines+markers',
          colors=colors[2], name = "CaCl2 Cl") %>%
      add_trace(x=~SiO2_Feed$time[-1],
          y=~SiO2_rej_Si,
          type='scatter',mode='lines+markers',
          colors=colors[3], name = "SiO2 Si") %>%
    layout( yaxis=list(title="Rejection Anions%",range=c(0,100)),
         xaxis=list(title="Time [h]"))
#fig_anions     


  plot_ly(x=~"time",
          y=~"avg_mg/L",
          type='scatter',mode='lines+markers') %>%
      layout(
        #title="silica, pH 9.25, silica 75 mg/L",
         yaxis=list(title="Rejection silica",range=c(0,50)),
        xaxis=list(title="Chloride content %") )


fig <- subplot(fig_cations,fig_anions,nrows=1,titleY=TRUE,titleX=TRUE,margin=0.1)

fig

fig_2 <- subplot(fig_NaCl,fig_CaCL2, fig_SiO2,nrows=1,titleY=TRUE,titleX=TRUE)
# Update title
annotations = list( 
  list( 
    x = 0.15,  
    y = 1.0,  
    text = "NaCl",  
    xref = "paper",  
    yref = "paper",  
    xanchor = "center",  
    yanchor = "bottom",  
    showarrow = FALSE 
  ),  
  list( 
    x = 0.5,  
    y = 1,  
    text = "CaCl2",  
    xref = "paper",  
    yref = "paper",  
    xanchor = "center",  
    yanchor = "bottom",  
    showarrow = FALSE 
  ),  
  list( 
    x = 0.85,  
    y = 1,  
    text = "SiO2",  
    xref = "paper",  
    yref = "paper",  
    xanchor = "center",  
    yanchor = "bottom",  
    showarrow = FALSE 
  )
)
  

fig_2 <- fig_2 %>%layout(annotations = annotations) 

fig_2


```

```{R import PCL data NaCl, echo=FALSE, message=FALSE}
### NaCl 3 mM
CWF_NaCl = read_delim("data/singlesalt_NaCl3mM_14-09-2021.csv",delim = "\t", escape_double = FALSE, 
                  trim_ws = TRUE, skip = 5) #Hente data og få det til passe ned i en tabel
#str(CWF)
dat_NaCl = as.data.frame(CWF_NaCl) #Ændrer strukturen af dataen til noget vi kan arbejde med
old_names=colnames(CWF_NaCl) #Vi finder de latterlige navne kolonnerne i dataen har 
new_names=c("time","level","con0201","pH0201","con0301","flow0301",
            "p0301","p0302","p0401","flow0401","p0501","con0501",
            "temp0501","p0601","temp0601","16","17","18","19","20",
            "21","pmp0201","pmp0301","pmp0401","pmp0501","flow_avg0301",
            "p_avg0301","p_avg0302","p_avg0401","flow_avg0401",
            "p_avg0501","FT0302","weight0302","flow0501","weight0501","36","pH0301",
            "pH0501","con0302","40") #Vi finder på nogle lidt bedre nogle
dat_NaCl = dat_NaCl %>% rename_at(vars(old_names),~new_names) #Vi ændrer navnene til de nye
dat_NaCl$time = dmy_hms(dat_NaCl$time)#Vi ændrer formatet af 'dato' kolonnen til et standard format for tid og datoer istedet for at det bare er noget tekst
#str(dat)


#tid_sec <- as.numeric(as.POSIXct(dat_NaCl$time))-as.numeric(as.POSIXct("2021-09-14 11:16:26", format='%Y-%m-%d %H:%M:%S')) #den regner 2 timer for meget, tag højde for det manuelt checket hvornår flow rammer 17 ml/min. 
#dat_NaCl <- data.frame(dat_NaCl,tid_sec) #tilføjer tid til data.frame

### Finde t=0 (fosøgsstart = der hvor flow er over 16 mL/min)
flow_boolean = dat_NaCl$flow0501>16&dat_NaCl$flow0501<25
start_tid = min(which(flow_boolean))
dat_NaCl=dat_NaCl[-c(1:start_tid),]
flow_boolean_slut = dat_NaCl$flow0501<1
slut_tid = min(which(flow_boolean_slut))
dat_NaCl=dat_NaCl[-c(slut_tid:(nrow(dat_NaCl)) ),]
### Tid i s fra forsøgs start
dat_NaCl = dat_NaCl%>%
   mutate(sek=(
           as.numeric(as.POSIXct(dat_NaCl$time))-as.numeric(dat_NaCl$time[1], format='%Y-%m-%d %H:%M:%S'))
                )  

dat_NaCl %>%#dplyr arbejder indenfor 'dat' data framen
  mutate(TMP=(p_avg0301+p_avg0302)/2-p_avg0501)%>%#Her regner vi TMP, som dplyr husker nu er en del af den data
  mutate(TMP_slid=rollapply(TMP,100,mean,align="right",fill=NA))%>%#Nu tager vi et glidende gennemsnit
  plot_ly(x=~(sek)/3600,
          y=~p_avg0301,
          name="Pressure before membrane",
          color='#1f77b4',
          type='scatter',
          mode='lines')%>%
  add_lines(y=~p_avg0302,
            name='Pressure after membrane',
            color='#E41317')%>%
  add_lines(y=~TMP_slid,
            name='TMP',
            color='#forestgreen')%>%
  layout(title="NaCl Pressure",
         legend=list(x=0.7,y=0.2),
         yaxis=list(title="Pressure [bar]"),
         xaxis=list(title="Time [h]")) #Her plottet de to tryk på feed siden plus et TMP





```

```{R import PCL data CaCl2 , echo=FALSE, message=FALSE}
###CaCl2 3 mM 
CWF_CaCl2 = read_delim("data/singlesalt_CaCl2_3mM_15-09-2021.csv",delim = "\t", escape_double = FALSE, 
                  trim_ws = TRUE, skip = 5) #Hente data og få det til passe ned i en tabel
#str(CWF)
dat_CaCl2 = as.data.frame(CWF_CaCl2) #Ændrer strukturen af dataen til noget vi kan arbejde med
old_names=colnames(CWF_CaCl2) #Vi finder de latterlige navne kolonnerne i dataen har 
new_names=c("time","level","con0201","pH0201","con0301","flow0301",
            "p0301","p0302","p0401","flow0401","p0501","con0501",
            "temp0501","p0601","temp0601","16","17","18","19","20",
            "21","pmp0201","pmp0301","pmp0401","pmp0501","flow_avg0301",
            "p_avg0301","p_avg0302","p_avg0401","flow_avg0401",
            "p_avg0501","FT0302","weight0302","flow0501","weight0501","36","pH0301",
            "pH0501","con0302","40") #Vi finder på nogle lidt bedre nogle
dat_CaCl2 = dat_CaCl2 %>% rename_at(vars(old_names),~new_names) #Vi ændrer navnene til de nye
dat_CaCl2$time = dmy_hms(dat_CaCl2$time)#Vi ændrer formatet af 'dato' kolonnen til et standard format for tid og datoer istedet for at det bare er noget tekst
#str(dat)


#tid_sec <- as.numeric(as.POSIXct(dat_CaCl2$time))-as.numeric(as.POSIXct("2021-09-14 11:16:26", #format='%Y-%m-%d %H:%M:%S')) #den regner 2 timer for meget, tag højde for det manuelt checket hvornår flow #rammer 17 ml/min. 
#dat_CaCl2 <- data.frame(dat_CaCl2,tid_sec) #tilføjer tid til data.frame

### Finde t=0 (fosøgsstart = der hvor flow er over 16 mL/min)
flow_boolean = dat_CaCl2$flow0501>16&dat_CaCl2$flow0501<25
start_tid = min(which(flow_boolean))
dat_CaCl2=dat_CaCl2[-c(1:start_tid),]
flow_boolean_slut = dat_CaCl2$flow0501<1
slut_tid = min(which(flow_boolean_slut))
dat_CaCl2=dat_CaCl2[-c(slut_tid:(nrow(dat_CaCl2)) ),]
### Tid i s fra forsøgs start
dat_CaCl2 = dat_CaCl2%>%
   mutate(sek=(
           as.numeric(as.POSIXct(dat_CaCl2$time))-as.numeric(dat_CaCl2$time[1], format='%Y-%m-%d %H:%M:%S'))
                )  

dat_CaCl2 %>%#dplyr arbejder indenfor 'dat' data framen
  mutate(TMP=(p_avg0301+p_avg0302)/2-p_avg0501)%>%#Her regner vi TMP, som dplyr husker nu er en del af den data
  mutate(TMP_slid=rollapply(TMP,100,mean,align="right",fill=NA))%>%#Nu tager vi et glidende gennemsnit
  plot_ly(x=~sek/3600,
          y=~p_avg0301,
          name="Pressure before membrane",
          color='#1f77b4',
          type='scatter',
          mode='lines')%>%
  add_lines(y=~p_avg0302,
            name='Pressure after membrane',
            color='#E41317')%>%
  add_lines(y=~TMP_slid,
            name='TMP',
            color='#forestgreen')%>%
  layout(title="CaCl2 Pressure",
         legend=list(x=0.7,y=0.2),
         yaxis=list(title="Pressure [bar]", range=c(0,3.5)),
         xaxis=list(title="Time [h]", range=c(0,4)))#Her plottet de to tryk på feed siden plus et TMP

```

```{R import data PLC Na2OSiO2, echo=FALSE, message=FALSE}
###Na2OSiO2 1 mM 
CWF <- read_delim("data/singlesalt_Na2OSiO2_1mM_22-09-2021.csv", 
                    delim = "\t", escape_double = FALSE, 
                    trim_ws = TRUE, skip = 5) #Hente data og få det til passe ned i en tabel
#str(CWF)
dat_SiO2 = as.data.frame(CWF) #Ændrer strukturen af dataen til noget vi kan arbejde med
old_names=colnames(CWF) #Vi finder de latterlige navne kolonnerne i dataen har 
new_names=c("time","level","con0201","pH0201","con0301","flow0301",
            "p0301","p0302","p0401","flow0401","p0501","con0501",
            "temp0501","p0601","temp0601","16","17","18","19","20",
            "21","pmp0201","pmp0301","pmp0401","pmp0501","flow_avg0301",
            "p_avg0301","p_avg0302","p_avg0401","flow_avg0401",
            "p_avg0501","FT0302","weight0302","flow0501","weight0501","36","pH0301",
            "pH0501","con0302","40") #Vi finder på nogle lidt bedre nogle
dat_SiO2 = dat_SiO2 %>% rename_at(vars(old_names),~new_names) #Vi ændrer navnene til de nye
dat_SiO2$time = dmy_hms(dat_SiO2$time)#Vi ændrer formatet af 'dato' kolonnen til et standard format for tid og datoer istedet for at det bare er noget tekst


### Finde t=0 (fosøgsstart = der hvor flow er over 16 mL/min)
flow_boolean_SiO2 = dat_SiO2$flow0501>16&dat_SiO2$flow0501<25
start_tid_SiO2 = min(which(flow_boolean_SiO2))
dat_SiO2=dat_SiO2[-c(1:start_tid_SiO2),]
flow_boolean_slut_SiO2 = dat_SiO2$flow0501<5
slut_tid_SiO2 = min(which(flow_boolean_slut_SiO2))
dat_SiO2=dat_SiO2[-c(slut_tid_SiO2:(nrow(dat_SiO2)) ),]
### Tid i s fra forsøgs start
dat_SiO2 = dat_SiO2%>%
   mutate(sek=(
           as.numeric(as.POSIXct(dat_SiO2$time))-as.numeric(dat_SiO2$time[1], format='%Y-%m-%d %H:%M:%S'))
                )  

dat_SiO2 %>%#dplyr arbejder indenfor 'dat' data framen
  mutate(TMP=(p_avg0301+p_avg0302)/2-p_avg0501)%>%#Her regner vi TMP, som dplyr husker nu er en del af den data
  mutate(TMP_slid=rollapply(TMP,100,mean,align="right",fill=NA))%>%#Nu tager vi et glidende gennemsnit
  plot_ly(x=~sek/3600,
          y=~p_avg0301,
          name="Pressure before membrane",
          color='#1f77b4',
          type='scatter',
          mode='lines')%>%
  add_lines(y=~p_avg0302,
            name='Pressure after membrane',
            color='#E41317')%>%
  add_lines(y=~TMP_slid,
            name='TMP',
            color='#forestgreen')%>%
  layout(title="SiO2 Pressure",
         legend=list(x=0.7,y=0.2),
         yaxis=list(title="Pressure [bar]", range=c(0,3.5)),
         xaxis=list(title="Time [h]", range=c(0,4)))#Her plottet de to tryk på feed siden plus et TMP

```
### Osmotic Pressure
```{R NaCl osmotisk tryk, echo=FALSE, message=FALSE}

plot_ly(data=dat_NaCl, x=~sek/3600, y=~temp0501)%>%
  layout(yaxis=list(title="Temperature", range=c(0,27)),
         xaxis=list(title="Time [h]")) 
#temperaturen ved prøve udtagning. er det vand eller luft?
dat_NaCl$temp0501[sek=1*60*60]
dat_NaCl$temp0501[sek=2*60*60]
dat_NaCl$temp0501[sek=3*60*60]
dat_NaCl$temp0501[sek=3.5*60*60]
dat_NaCl$temp0501[sek=4*60*60]

#constants
R=0.08314 #(L*bar)/(mol*K)
Temp=(23+272)
Mw_Cl=35.45
Mw_Na=22.99
Mw_Ca=40.078
Mw_SiO2=60.08
#antaget ideal solutions og i sat til antal ioner. silica er tricky
NaCl_IC_data <- NaCl_IC_data %>% mutate(os_tryk_bar=(2*(((Chloride/1000)/Mw_Cl)+((Sodium/1000)/Mw_Na))*R*Temp))
CaCl2_IC_data <- CaCl2_IC_data %>% mutate(os_tryk_bar=(3*(((Chloride/1000)/Mw_Cl)+((Calcium/1000)/Mw_Ca))*R*Temp))
SiO2_IC_data <- SiO2_IC_data %>% mutate(os_tryk_bar=(3*(((Silica/1000)/Mw_SiO2)+((Sodium/1000)/Mw_Na))*R*Temp))


fig_os_tryk <- NaCl_IC_data %>% filter(Stream=="Feed")%>%
plot_ly(x=~time,
          y=~os_tryk_bar,
          type='scatter',mode='lines+markers',
          colors=colors[1], name = "NaCl")%>%
add_trace(data=CaCl2_IC_data %>% filter(Stream=="Feed"),x=~time,
          y=~os_tryk_bar,
          type='scatter',mode='lines+markers',
          colors=colors[1], name = "CaCl2") %>%
add_trace(data=SiO2_IC_data %>% filter(Stream=="Feed"),x=~time,
          y=~os_tryk_bar,
          type='scatter',mode='lines+markers',
          colors=colors[1], name = "Na2OSiO2") %>%
  layout( yaxis=list(title="osmotic pressure [bar]",range=c(0,1)),
         xaxis=list(title="Time [h]")) 
  
  fig_os_tryk
  
  #evt. normaliser i forhold til start værdien. 
 

``` 

```{R pH, echo=FALSE, message=FALSE}


fig_pH <- plot_ly(data=dat_NaCl,x=~sek/3600/6*100,
          y=~pH0201,
          type='scatter',mode='lines+markers',
          colors=colors[1], name = "pH NaCl") %>%
      add_trace(data=dat_CaCl2,x=~sek/3600/6*100,
          y=~pH0201,
          type='scatter',mode='lines+markers',
          colors=colors[2], name = "pH CaCl2") %>%
      add_trace(data=dat_SiO2,x=~sek/3600/6*100,
          y=~pH0201,
          type='scatter',mode='lines+markers',
          colors=colors[3], name = "pH Na2OSiO2") %>%
    layout( yaxis=list(title="pH",range=c(7,9)),
         xaxis=list(title="Water Recovery [%]"))
fig_pH  


ggplot()+geom_line(data=dat_NaCl,aes(x=100*(1-(6-sek/60/60*1.02)/6),y=pH0201,color="NaCl"))+
  geom_line(data=dat_CaCl2,aes(x=100*(1-(6-sek/60/60*1.02)/6),y=pH0201,color="CaCl"))+
  geom_line(data=dat_SiO2,aes(x=100*(1-(6-sek/60/60*1.02)/6),y=pH0201,color="Na2OSiO2"))+
scale_color_brewer(palette= "Set1")+
  scale_x_continuous(limits=c(0, 70), breaks=c(0,20, 40,60 ))+
  scale_y_continuous(limits=c(7.0, 8.75), breaks=c(7,7.5,8,8.5))+
    labs(x="Water Recovery [%]",y="pH", color="Filtration")

```

```{r Summary bicarbonat, echo=FALSE, message=FALSE}


B_NaCl <- c(8.4,NA,31,42,43)
B_CaCl2 <- c(6,NA,15,18,20)
B_Na2OSiO2 <- c(128,141,157,196,205)

tid <- (c(0,1,2,3.5,4))/6*100



SingleSalt <- data.frame(tid,B_NaCl, B_CaCl2,B_Na2OSiO2)
#SingleSalt = SingleSalt%>%gather(key,value,B_NaCl,B_CaCl2,B_Na2OSiO2)
SS = na.omit(SingleSalt)


fig_B <- plot_ly(data=SingleSalt,x=~tid[-2],
          y=~B_NaCl[-2]/61.0618,
          #color=~key,
          type='scatter',mode='lines+markers',
          colors=colors[1],name="NaCl") %>%
      add_trace(data=SingleSalt,x=~tid[-2],
          y=~B_CaCl2[-2]/61.0618,
          #color=~key,
          type='scatter',mode='lines+markers',
          colors=colors[2],name="CaCl2") %>%
      add_trace(data=SingleSalt,x=~tid,
          y=~B_Na2OSiO2/61.0618,
          #color=~key,
          type='scatter',mode='lines+markers',
          colors=colors[1], name = "Na2OSiO2") %>%
    layout( yaxis=list(title="Bicarbonate [mM]"),
         xaxis=list(title="Water Recovery [%]"))
fig_B  



```

### We back in single salt databehandling
```{r We out here}
SS=rbind(Data,tst,tst2)
SS$recovery=SS$time/6
Mw_Cl=35.45
Mw_Na=22.99
Mw_Ca=40.078
Mw_SO4=96.06
Mw_SiO2=60.08
SS = SS%>%mutate("f_Na_mmol"=f_Na/Mw_Na)
SS = SS%>%mutate("f_Ca_mmol"=f_Ca/Mw_Ca)
SS = SS%>%mutate("f_Cl_mmol"=f_Cl/Mw_Cl)
SS = SS%>%mutate("f_SiO2_mmol"=f_SiO2/Mw_SiO2)

SS = SS%>%mutate("p_Na_mmol"=p_Na/Mw_Na)
SS = SS%>%mutate("p_Ca_mmol"=p_Ca/Mw_Ca)
SS = SS%>%mutate("p_Cl_mmol"=p_Cl/Mw_Cl)
SS = SS%>%mutate("p_SiO2_mmol"=p_SiO2/Mw_SiO2)

SS_plot=SS%>%gather(key="key",value="value",f_Na_mmol,f_Cl_mmol,f_SiO2_mmol,f_Ca_mmol)
SS_plot$ion=c(rep("Na",21),rep("Cl",21),rep("SiO2",21),rep("Ca",21))
SS_plot$var="Concentration"

ggplot(SS_plot,aes(x=recovery,y=value,color=ion))+geom_point()+geom_line()+facet_grid(cols=vars(exp))

SS_rej=SS%>%gather(key="key",value="value",Rej_Na,Rej_Cl,Rej_SiO2,Rej_Ca)
SS_rej$ion=c(rep("Na",21),rep("Cl",21),rep("SiO2",21),rep("Ca",21))
SS_rej$var="Rejection [%]"

ggplot(SS_rej,aes(x=recovery,y=value,color=ion))+geom_point()+geom_line()+facet_grid(cols=vars(exp))

SS_tot_plot=SS%>%gather(key="key",value="value",f_Na_mmol,f_Cl_mmol,f_SiO2_mmol,f_Ca_mmol,Rej_Na,Rej_Cl,Rej_SiO2,Rej_Ca)
SS_tot_plot$ion=rep(c(rep("Na",21),rep("Cl",21),rep("SiO2",21),rep("Ca",21)),2)
SS_tot_plot$var=c(rep("Feed Concentration [mM]",84),rep("Rejection [%]",84))
SS_tot_plot$exp[SS_tot_plot$exp == "SiO2"] <- "Na2OSiO2"

ggplotly(ggplot(SS_tot_plot,aes(x=recovery,y=value,color=ion))+geom_point()+geom_line()+ylim(0,NA)+
           facet_grid(cols=vars(exp),row =vars(var),scale="free",switch=NULL))

ioner=c(expression(Ca^{textstyle("2+")}),expression(Cl^{textstyle("-")}),expression(Na^{textstyle("+")}),expression(SiO[2]),expression(SO[4]^{textstyle("2-")}))
colors2=c( 
  '#d62728',  # brick red
  '#1f77b4',  # muted blue 
  '#2ca02c',  # cooked asparagus green
  '#9467bd',  # muted purple  
  '#ff7f0e',  # safety orange
  '#8c564b',  # chestnut brown
  '#e377c2',  # raspberry yogurt pink
  '#7f7f7f',  # middle gray
  '#bcbd22',  # curry yellow-green
  '#17becf'   # blue-teal
)

ggplot(SS_tot_plot,aes(x=recovery*100,y=value,color=ion))+geom_point()+geom_line()+ylim(0,NA)+
  xlab("Water Recovery [%]")+ylab(" ")+
           scale_color_manual(labels = ioner, values =colors2)+labs(colour = "Species")+
  theme(legend.text.align=0)+facet_grid(cols=vars(exp),row=vars(var),scale="free")
  

#bud på at lave den pæn, no worky
#ggplotly(ggplot(SS_tot_plot,aes(x=recovery,y=value,color=ion))+geom_point()+geom_line()+ylim(0,NA)+
#           facet_grid(cols=vars(exp),row =vars(var),scale="free"))+
#scale_color_brewer(palette= "Set1")

#ggplot()+geom_line(data=dat_M_9.2,aes(x=100*(1-(10-sek/60/60*1.02)/10),y=pH0201,color="ID:1 - pH 9.3"))+
#  geom_line(data=dat_M_10,aes(x=100*(1-(8.5-sek/60/60*1.02)/8.5),y=pH0201,color="ID:2 - pH 10.1"))+
#  geom_line(data=dat_M_10.5,aes(x=100*(1-(10-sek/60/60*1.02)/10),y=pH0201,color="ID:3 - pH 10.5"))+
#+
#  scale_x_continuous(limits=c(0, 90), breaks=c(0,20, 40,60,80 ))+
#  scale_y_continuous(limits=c(9, 10.75), breaks=c(9,9.5,10,10.5 ))+
    



```


