---
title: "SPRR_Bikarbonat"
author: "Lærke"
date: "1/12/2021"
output: html_document
editor_options: 
  markdown: 
    wrap: 72
---

```{r setup, include=FALSE}

library(dplyr)
library(tidyr)
library(ggplot2)
library(visdat)
library(GGally)
library(Hmisc)
library(DMwR2)
library(data.table)
library(mltools)
library(ggfortify)
library(ggiraphExtra)
library(coronavirus)
library(lubridate)
library(plotly)
library(readxl)
require(readr)
library(zoo)
library(latex2exp)
library(fs)
library(fcuk)
colors = c(
    '#1f77b4',  # muted blue
    '#ff7f0e',  # safety orange
    '#2ca02c',  # cooked asparagus green
    '#d62728',  # brick red
    '#9467bd',  # muted purple
    '#8c564b',  # chestnut brown
    '#e377c2',  # raspberry yogurt pink
    '#7f7f7f',  # middle gray
    '#bcbd22',  # curry yellow-green
    '#17becf'   # blue-teal
)
```


```{R import af data, eval=FALSE, message=FALSE, include=FALSE}


SPRR_data <- read_excel("data/SPRR/SPRR_analysesvar_samlet.xlsx",2,
                        col_types="numeric")
                        #row_types=c("character","numeric","numeric","numeric","numeric","numeric","numeric"))
SPRR_data <- as.data.frame(SPRR_data[-1,-1])

row.names(SPRR_data) <- c("Calcium","Sodium","Chloride","Sulphate","Silica","Bicarbonate")
colnames(SPRR_data) <- c("Feed_1","Permeate_1",
                 "Feed_2","Permeate_2",
                 "Feed_3","Permeate_3",
                 "Feed_4","Permeate_4",
                 "Feed_5","Permeate_5",
                 "Feed_6","Permeate_6",
                 "Feed_7","Permeate_7",
                 "Feed_8","Permeate_8",
                 "Feed_9","Permeate_9",
                 "Feed_10","Permeate_10",
                 "Feed_11","Permeate_11",
                 "Feed_12","Permeate_12",
                 "Feed_13","Permeate_13",
                 "Feed_14","Permeate_14",
                 "Feed_15","Permeate_15",
                 "Feed_16","Permeate_16",
                 "Feed_17","Permeate_17",
                 "Feed_18","Permeate_18")

SPRR_data_raw=SPRR_data                 
               

Rej_function = function(feed,permeate){
  res = (1-(permeate/feed))*100
    return(res)
} 
rej_1=Rej_function(SPRR_data[,1],SPRR_data[,2])
rej_2=Rej_function(SPRR_data[,3],SPRR_data[,4])
rej_3=Rej_function(SPRR_data[,5],SPRR_data[,6])
rej_4=Rej_function(SPRR_data[,7],SPRR_data[,8])
rej_5=Rej_function(SPRR_data[,9],SPRR_data[,10])
rej_6=Rej_function(SPRR_data[,11],SPRR_data[,12])
rej_7=Rej_function(SPRR_data[,13],SPRR_data[,14])
rej_8=Rej_function(SPRR_data[,15],SPRR_data[,16])
rej_9=Rej_function(SPRR_data[,17],SPRR_data[,18])
rej_10=Rej_function(SPRR_data[,19],SPRR_data[,20])
rej_11=Rej_function(SPRR_data[,21],SPRR_data[,22])
rej_12=Rej_function(SPRR_data[,23],SPRR_data[,24])
rej_13=Rej_function(SPRR_data[,25],SPRR_data[,26])
rej_14=Rej_function(SPRR_data[,27],SPRR_data[,28])
rej_15=Rej_function(SPRR_data[,29],SPRR_data[,30])
rej_16=Rej_function(SPRR_data[,31],SPRR_data[,32])
rej_17=Rej_function(SPRR_data[,33],SPRR_data[,34])
rej_18=Rej_function(SPRR_data[,35],SPRR_data[,36])

Rej_total <- cbind.data.frame(rej_1,rej_2,rej_3,rej_4,rej_5,rej_6,rej_7,rej_8,rej_9,rej_10,rej_11,rej_12,rej_13,rej_14,rej_15,rej_16,rej_17,rej_18)
row.names(Rej_total) <- c("Calcium","Sodium","Chloride","Sulphate","Silica","Bicarbonate")




#plot af bicarbonat

  plot_ly(data=SPRR_data, x=~No,
          y=~Bicarbonate,
         color=~Stream,
          type='scatter',mode='lines+markers',
          colors=c(colors[1],colors[2]))  %>%
      layout(title="Bicarbonate SPRR",
         yaxis=list(title="Concentration Bicarboante [mg/L]"),
         xaxis=list(title="Experiment no.")) 
 

 
 


```


## Overview data against Experiment no. 



```{R import af data god, message=FALSE, include=FALSE}


SPRR_data <- read_excel("data/SPRR/SPRR_analysesvar_samlet.xlsx",3,col_names = T,
                        col_types=c("numeric","text","numeric","numeric","numeric","numeric","numeric","numeric","numeric","numeric","numeric"))
SPRR_data_raw=SPRR_data 

```

```{r kigger på feed koncentrationer}
new_ratios_feed = SPRR_data %>% filter(Stream=="Feed")
new_ratios_feed =new_ratios_feed %>% mutate(acutal_cl_ratio = (Cl/35)/((SO4/96)+(Cl/35)))
new_ratios_feed = new_ratios_feed %>% mutate(acutal_na_ratio = (Na/23)/((Ca/40)+(Na/23)))
SPRR_data = SPRR_data %>% mutate(Cl_ratio=replace(Cl_ratio,Stream=="Feed",new_ratios_feed$acutal_cl_ratio)) 
SPRR_data = SPRR_data %>% mutate(Cl_ratio=replace(Cl_ratio,Stream=="Rejection",new_ratios_feed$acutal_cl_ratio))
SPRR_data = SPRR_data %>% mutate(Cl_ratio=replace(Cl_ratio,Stream=="Permeat",new_ratios_feed$acutal_cl_ratio))
SPRR_data = SPRR_data %>% mutate(Cl_ratio=Cl_ratio*100)
#A=SPRR_data %>% filter(Stream=="Feed"& (!is.na(Cl))&Experiment_no >1)
```

```{R plot af experiment no., eval=FALSE, message=FALSE, include=FALSE}

str(SPRR_data)
  plot_ly(data=SPRR_data, x=~Experiment_no,
          y=~Ca,
         color=~Stream,
          type='scatter',mode='lines+markers',
          colors=c(colors[1],colors[2],colors[3]))  %>%
      layout(title="Calcium SPRR",
         yaxis=list(title="Concentration Calcium [mg/L]"),
         xaxis=list(title="Experiment no.")) 
 

 plot_ly(data=SPRR_data, x=~Experiment_no,
          y=~Na,
         color=~Stream,
          type='scatter',mode='lines+markers',
          colors=c(colors[1],colors[2],colors[3]))  %>%
      layout(title="Sodium SPRR",
         yaxis=list(title="Concentration Sodium [mg/L]"),
         xaxis=list(title="Experiment no.")) 
 
 plot_ly(data=SPRR_data, x=~Experiment_no,
          y=~Cl,
         color=~Stream,
          type='scatter',mode='lines+markers',
          colors=c(colors[1],colors[2],colors[3]))  %>%
      layout(title="Chloride SPRR",
         yaxis=list(title="Concentration Chloride [mg/L]"),
         xaxis=list(title="Experiment no.")) 
 
 plot_ly(data=SPRR_data, x=~Experiment_no,
          y=~SO4,
         color=~Stream,
          type='scatter',mode='lines+markers',
          colors=c(colors[1],colors[2],colors[3]))  %>%
      layout(title="Sulphate SPRR",
         yaxis=list(title="Concentration Sulphate [mg/L]"),
         xaxis=list(title="Experiment no.")) 
 
 plot_ly(data=SPRR_data, x=~Experiment_no,
          y=~SiO2,
         color=~Stream,
          type='scatter',mode='lines+markers',
          colors=c(colors[1],colors[2],colors[3]))  %>%
      layout(title="Silica SPRR",
         yaxis=list(title="Concentration Silica [mg/L]"),
         xaxis=list(title="Experiment no.")) 
 
 plot_ly(data=SPRR_data, x=~Experiment_no,
          y=~HCO3,
         color=~Stream,
          type='scatter',mode='lines+markers',
          colors=c(colors[1],colors[2],colors[3]))  %>%
      layout(title="Bicarbonate SPRR",
         yaxis=list(title="Concentration Bicarboante [mg/L]"),
         xaxis=list(title="Experiment no.")) 
 
 
 


```
## Silica analyse

```{R Plot af Silica subplots, eval=FALSE, message=FALSE, include=FALSE}

x_tick <- 1:18


fig_1 <- SPRR_data %>% filter(Stream=="Rejection",pH=="9.25",Silica_content=="75")%>%
  plot_ly(x=~Cl_ratio,
          y=~SiO2,
          type='scatter',mode='lines+markers') %>%
      layout(
        #title="silica, pH 9.25, silica 75 mg/L",
         yaxis=list(title="Rejection silica",range=c(0,50)),
        xaxis=list(title="Chloride content %") )

fig_2 <- SPRR_data %>% filter(Stream=="Rejection",pH=="9.5",Silica_content=="75")%>%
  plot_ly(x=~Cl_ratio,
          y=~SiO2,
          type='scatter',mode='lines+markers') %>%
      layout(
        #title="silica, pH 9.5, silica 75 mg/L",
         yaxis=list(title="Rejection silica",range=c(0,50)),
        xaxis=list(title="Chloride content %") )


fig_3 <- SPRR_data %>% filter(Stream=="Rejection",pH=="9.75",Silica_content=="75")%>%
  plot_ly(x=~Cl_ratio,
          y=~SiO2,
          type='scatter',mode='lines+markers') %>%
      layout(
        #title="silica, pH 9.75, silica 75 mg/L",
         yaxis=list(title="Rejection silica",range=c(0,50)),
        xaxis=list(title="Chloride content %") )

fig_4 <- SPRR_data %>% filter(Stream=="Rejection",pH=="9.25",Silica_content=="125")%>%
  plot_ly(x=~Cl_ratio,
          y=~SiO2,
          type='scatter',mode='lines+markers') %>%
      layout(
        #title="silica, pH 9.25, silica 125 mg/L",
         yaxis=list(title="Rejection silica",range=c(0,50)),
        xaxis=list(title="Chloride content %") )

fig_5 <- SPRR_data %>% filter(Stream=="Rejection",pH=="9.5",Silica_content=="125")%>%
  plot_ly(x=~Cl_ratio,
          y=~SiO2,
          type='scatter',mode='lines+markers') %>%
      layout(
        #title="silica, pH 9.5, silica 125 mg/L",
         yaxis=list(title="Rejection silica",range=c(0,50)),
        xaxis=list(title="Chloride content %"))


fig_6 <- SPRR_data %>% filter(Stream=="Rejection",pH=="9.75",Silica_content=="125")%>%
  plot_ly(x=~Cl_ratio,
          y=~SiO2,
          type='scatter',mode='lines+markers') %>%
      layout(
        #title="silica, pH 9.75, silica 125 mg/L",
         yaxis=list(title="Rejection silica",range=c(0,50)),
        xaxis=list(title="Chloride content %") )
 
fig_SiO2 <- subplot(fig_1,fig_2,fig_3,fig_4,fig_5,fig_6,nrows=2,titleY=TRUE,titleX=TRUE,margin=0.1)
  
# Update title
annotations = list( 
  list( 
    x = 0.15,  
    y = 1.0,  
    text = "Silica 75 mg/L, pH 9,25",  
    xref = "paper",  
    yref = "paper",  
    xanchor = "center",  
    yanchor = "bottom",  
    showarrow = FALSE 
  ),  
  list( 
    x = 0.5,  
    y = 1,  
    text = "Silica 75 mg/L, pH 9,5",  
    xref = "paper",  
    yref = "paper",  
    xanchor = "center",  
    yanchor = "bottom",  
    showarrow = FALSE 
  ),  
  list( 
    x = 0.85,  
    y = 1,  
    text = "Silica 75 mg/L, pH 9,75",  
    xref = "paper",  
    yref = "paper",  
    xanchor = "center",  
    yanchor = "bottom",  
    showarrow = FALSE 
  ),
  list( 
    x = 0.15,  
    y = 0.4,  
    text = "Silica 125 mg/L, pH 9,25",  
    xref = "paper",  
    yref = "paper",  
    xanchor = "center",  
    yanchor = "bottom",  
    showarrow = FALSE 
  ),  
  list( 
    x = 0.5,  
    y = 0.4,  
    text = "Silica 125 mg/L, pH 9,5",  
    xref = "paper",  
    yref = "paper",  
    xanchor = "center",  
    yanchor = "bottom",  
    showarrow = FALSE 
  ),  
  list( 
    x = 0.85,  
    y = 0.4,  
    text = "Silica 125 mg/L, pH 9,75",  
    xref = "paper",  
    yref = "paper",  
    xanchor = "center",  
    yanchor = "bottom",  
    showarrow = FALSE 
  ))

fig_SiO2 <- fig_SiO2 %>%layout(annotations = annotations) 


fig_SiO2

#mere inspo
#https://plotly.com/r/subplots/

```

```{R Plot af Silica subplots_2, eval=FALSE, message=FALSE, include=FALSE}

x_tick <- 1:18


fig_1 <- SPRR_data %>% filter(Stream=="Rejection",pH=="9.25")%>%
  plot_ly(x=~Cl_ratio,
          y=~SiO2,
          color =~Silica_content,
          colors=c(colors[1],colors[2]),
          type='scatter',mode='lines+markers') %>%
      layout(
        #title="silica, pH 9.25, silica 75 mg/L",
         yaxis=list(title="Rejection silica",range=c(0,50)),
        xaxis=list(title="Chloride content %") )

fig_2 <- SPRR_data %>% filter(Stream=="Rejection",pH=="9.5")%>%
  plot_ly(x=~Cl_ratio,
          y=~SiO2,
          color =~Silica_content,
          colors=c(colors[1],colors[2]),
          type='scatter',mode='lines+markers') %>%
      layout(
        #title="silica, pH 9.25, silica 75 mg/L",
         yaxis=list(title="Rejection silica",range=c(0,50)),
        xaxis=list(title="Chloride content %") )


fig_3 <- SPRR_data %>% filter(Stream=="Rejection",pH=="9.75")%>%
  plot_ly(x=~Cl_ratio,
          y=~SiO2,
          color =~Silica_content,
          colors=c(colors[1],colors[2]),
          type='scatter',mode='lines+markers') %>%
      layout(
        #title="silica, pH 9.25, silica 75 mg/L",
         yaxis=list(title="Rejection silica",range=c(0,50)),
        xaxis=list(title="Chloride content %") )

 
fig_SiO2 <- subplot(fig_1,fig_2,fig_3,nrows=1,titleY=TRUE,titleX=TRUE,margin=0.1)
  
# Update title
annotations = list( 
  list( 
    x = 0.15,  
    y = 1.0,  
    text = "pH 9,25",  
    xref = "paper",  
    yref = "paper",  
    xanchor = "center",  
    yanchor = "bottom",  
    showarrow = FALSE 
  ),  
  list( 
    x = 0.5,  
    y = 1,  
    text = "pH 9,5",  
    xref = "paper",  
    yref = "paper",  
    xanchor = "center",  
    yanchor = "bottom",  
    showarrow = FALSE 
  ),  
  list( 
    x = 0.85,  
    y = 1,  
    text = "pH 9,75",  
    xref = "paper",  
    yref = "paper",  
    xanchor = "center",  
    yanchor = "bottom",  
    showarrow = FALSE 
  ))

fig_SiO2 <- fig_SiO2 %>%layout(annotations = annotations) 


fig_SiO2

#mere inspo
#https://plotly.com/r/subplots/

```


```{R Plot af Silica subplots_3, echo=FALSE, message=FALSE}


fig_1 <- SPRR_data %>% filter(Stream=="Rejection",Silica_content=="75")%>%
  plot_ly(x=~Cl_ratio,
          y=~SiO2,
          color =~pH,
          colors=c(colors[1],colors[2],colors[3]),
          type='scatter',mode='lines+markers',
          showlegend=FALSE) %>%
      layout(
        #title="silica, pH 9.25, silica 75 mg/L",
         yaxis=list(title="Rejection silica",range=c(0,50)),
        xaxis=list(title="Chloride content %") )

fig_2 <- SPRR_data %>% filter(Stream=="Rejection",Silica_content=="125")%>%
  plot_ly(x=~Cl_ratio,
          y=~SiO2,
          color =~pH,
          colors=c(colors[1],colors[2],colors[3]),
          type='scatter',mode='lines+markers') %>%
      layout(
        #title="silica, pH 9.25, silica 75 mg/L",
         yaxis=list(title="Rejection silica",range=c(0,50)),
        xaxis=list(title="Chloride content %") )


fig_SiO2 <- subplot(fig_1,fig_2,nrows=1,titleY=TRUE,titleX=TRUE,margin=0.1)
  
# Update title
annotations = list( 
  list( 
    x = 0.2,  
    y = 1.0,  
    text = "Silica 75 mg/L",  
    xref = "paper",  
    yref = "paper",  
    xanchor = "center",  
    yanchor = "bottom",  
    showarrow = FALSE 
  ),  
  list( 
    x = 0.8,  
    y = 1,  
    text = "Silica 125 mg/L",  
    xref = "paper",  
    yref = "paper",  
    xanchor = "center",  
    yanchor = "bottom",  
    showarrow = FALSE 
  ),
  list( 
    x = 1.100009,  
    y = 1,  
    text = "pH",  
    xref = "paper",  
    yref = "paper",  
    xanchor = "center",  
    yanchor = "bottom",  
    showarrow = FALSE 
  ))
  
  #,list(yref='paper',xref="paper",y=1.05,x=1.1, text="Cylinders",showarrow=F))

fig_SiO2 <- fig_SiO2 %>%layout(annotations = annotations) 


fig_SiO2

#mere inspo
#https://plotly.com/r/subplots/

```

```{R Plot af Silica subplots_4, eval=FALSE, message=FALSE, include=FALSE}


fig_1 <- SPRR_data %>% filter(Stream=="Rejection",Silica_content=="75")%>%
  plot_ly(x=~pH,
          y=~SiO2,
          color =~Cl_ratio,
          colors=c(colors[1],colors[2],colors[3]),
          type='scatter',mode = 'lines+markers',
          showlegend=FALSE) %>%
      layout(
        #title="silica, pH 9.25, silica 75 mg/L",
         yaxis=list(title="Rejection silica",range=c(0,50)),
        xaxis=list(title="pH") )

fig_2 <- SPRR_data %>% filter(Stream=="Rejection",Silica_content=="125")%>%
  plot_ly(x=~pH,
          y=~SiO2,
          color =~Cl_ratio,
          colors=c(colors[2],colors[3]),
         type='scatter',mode='lines+markers') %>%
      layout(
        #title="silica, pH 9.25, silica 75 mg/L",
         yaxis=list(title="Rejection silica",range=c(0,50)),
        xaxis=list(title="pH ") )


fig_SiO2 <- subplot(fig_1,fig_2,nrows=1,titleY=TRUE,titleX=TRUE,margin=0.1)
  
# Update title
annotations = list( 
  list( 
    x = 0.2,  
    y = 1.0,  
    text = "Silica 75 mg/L",  
    xref = "paper",  
    yref = "paper",  
    xanchor = "center",  
    yanchor = "bottom",  
    showarrow = FALSE 
  ),  
  list( 
    x = 0.8,  
    y = 1,  
    text = "Silica 125 mg/L",  
    xref = "paper",  
    yref = "paper",  
    xanchor = "center",  
    yanchor = "bottom",  
    showarrow = FALSE 
  ))

fig_SiO2 <- fig_SiO2 %>%layout(annotations = annotations) 


fig_SiO2

#mere inspo
#https://plotly.com/r/subplots/

```


```{R Plot af Calcium mere, eval=FALSE, message=FALSE, include=FALSE}
SPRR_data %>% filter(Stream=="Rejection")%>%
 plot_ly(x=~Experiment_no,
          y=~Ca,
         color=~pH,
          type='scatter',mode='lines+markers',
          colors=c(colors[1],colors[2],colors[3]))  %>%
      layout(title="Calcium pH",
             legend=list(title=list(text='<b> pH </b>')),
         yaxis=list(title="Rejection of Calcium % ",range=c(1,100)),
         xaxis=list(title="Experiment no.",tickvals=x_tick)) 
 

SPRR_data %>% filter(Stream=="Rejection")%>%
 plot_ly(x=~Experiment_no,
          y=~Ca,
         color=~Cl_ratio,
          type='scatter',mode='lines+markers',
          colors=c(colors[1],colors[2],colors[3]))  %>%
      layout(title="Calcium, Chloride ratio",
             legend=list(title=list(text='<b> Chloride Ratio </b>')),
         yaxis=list(title="Rejection of Calcium % ",range=c(1,100)),
         xaxis=list(title="Experiment no.",tickvals=x_tick)) 

SPRR_data %>% filter(Stream=="Rejection")%>%
 plot_ly(x=~Experiment_no,
          y=~Ca,
         color=~Silica_content,
          type='scatter',mode='lines+markers',
          colors=c(colors[1],colors[2],colors[3]))  %>%
      layout(title="Calcium, Silica content",
             legend=list(title=list(text='<b> Silica content </b>')),
         yaxis=list(title="Rejection of Calcium % ",range=c(1,100)),
         xaxis=list(title="Experiment no.",tickvals=x_tick)) 

```

## Calcium 

```{R Plot af Calcium subplots, echo=FALSE, message=FALSE}


fig_1 <- SPRR_data %>% filter(Stream=="Rejection",Silica_content=="75")%>%
  plot_ly(x=~Cl_ratio,
          y=~Ca,
          color =~pH,
          colors=c(colors[1],colors[2],colors[3]),
          type='scatter',mode='lines+markers',
          showlegend=FALSE) %>%
      layout(
        #title="silica, pH 9.25, silica 75 mg/L",
         yaxis=list(title="Rejection Calcium",range=c(0,100)),
        xaxis=list(title="Chloride content %") )

fig_2 <- SPRR_data %>% filter(Stream=="Rejection",Silica_content=="125")%>%
  plot_ly(x=~Cl_ratio,
          y=~Ca,
          color =~pH,
          colors=c(colors[1],colors[2],colors[3]),
          type='scatter',mode='lines+markers') %>%
      layout(
        #title="silica, pH 9.25, silica 75 mg/L",
         yaxis=list(title="Rejection Calcium",range=c(0,100)),
        xaxis=list(title="Chloride content %") )


fig_Ca <- subplot(fig_1,fig_2,nrows=1,titleY=TRUE,titleX=TRUE,margin=0.1)
  
# Update title
annotations = list( 
  list( 
    x = 0.2,  
    y = 1.0,  
    text = "Silica 75 mg/L",  
    xref = "paper",  
    yref = "paper",  
    xanchor = "center",  
    yanchor = "bottom",  
    showarrow = FALSE 
  ),  
  list( 
    x = 0.8,  
    y = 1,  
    text = "Silica 125 mg/L",  
    xref = "paper",  
    yref = "paper",  
    xanchor = "center",  
    yanchor = "bottom",  
    showarrow = FALSE 
  ),
  list( 
    x = 1.100009,  
    y = 1,  
    text = "pH",  
    xref = "paper",  
    yref = "paper",  
    xanchor = "center",  
    yanchor = "bottom",  
    showarrow = FALSE 
  ))

fig_Ca <- fig_Ca %>%layout(annotations = annotations) 


fig_Ca

#mere inspo
#https://plotly.com/r/subplots/

```

## Sodium

```{R Plot af Sodium subplots, echo=FALSE, message=FALSE}


fig_1 <- SPRR_data %>% filter(Stream=="Rejection",Silica_content=="75")%>%
  plot_ly(x=~Cl_ratio,
          y=~Na,
          color =~pH,
          colors=c(colors[1],colors[2],colors[3]),
          type='scatter',mode='lines+markers',
          showlegend=FALSE) %>%
      layout(
        #title="silica, pH 9.25, silica 75 mg/L",
         yaxis=list(title="Rejection Sodium",range=c(0,100)),
        xaxis=list(title="Chloride content %") )

fig_2 <- SPRR_data %>% filter(Stream=="Rejection",Silica_content=="125")%>%
  plot_ly(x=~Cl_ratio,
          y=~Na,
          color =~pH,
          colors=c(colors[1],colors[2],colors[3]),
          type='scatter',mode='lines+markers') %>%
      layout(
        #title="silica, pH 9.25, silica 75 mg/L",
         yaxis=list(title="Rejection Sodium",range=c(0,100)),
        xaxis=list(title="Chloride content %") )


fig_Na <- subplot(fig_1,fig_2,nrows=1,titleY=TRUE,titleX=TRUE,margin=0.1)
  
# Update title
annotations = list( 
  list( 
    x = 0.2,  
    y = 1.0,  
    text = "Silica 75 mg/L",  
    xref = "paper",  
    yref = "paper",  
    xanchor = "center",  
    yanchor = "bottom",  
    showarrow = FALSE 
  ),  
  list( 
    x = 0.8,  
    y = 1,  
    text = "Silica 125 mg/L",  
    xref = "paper",  
    yref = "paper",  
    xanchor = "center",  
    yanchor = "bottom",  
    showarrow = FALSE 
  ),
  list( 
    x = 1.100009,  
    y = 1,  
    text = "pH",  
    xref = "paper",  
    yref = "paper",  
    xanchor = "center",  
    yanchor = "bottom",  
    showarrow = FALSE 
  ))

fig_Na <- fig_Na %>%layout(annotations = annotations) 


fig_Na

#mere inspo
#https://plotly.com/r/subplots/

```

## Chloride

```{R Plot af Chloride subplots, echo=FALSE, message=FALSE}


fig_1 <- SPRR_data %>% filter(Stream=="Rejection",Silica_content=="75")%>%
  plot_ly(x=~Cl_ratio,
          y=~Cl,
          color =~pH,
          colors=c(colors[1],colors[2],colors[3]),
          type='scatter',mode='lines+markers', showlegend=FALSE) %>%
      layout(
        #title="silica, pH 9.25, silica 75 mg/L",
         yaxis=list(title="Rejection Chloride",range=c(-25,20)),
        xaxis=list(title="Chloride content %") )

fig_2 <- SPRR_data %>% filter(Stream=="Rejection",Silica_content=="125")%>%
  plot_ly(x=~Cl_ratio,
          y=~Cl,
          color =~pH,
          colors=c(colors[1],colors[2],colors[3]),
          type='scatter',mode='lines+markers') %>%
      layout(
        #title="silica, pH 9.25, silica 75 mg/L",
         yaxis=list(title="Rejection Chloride",range=c(-25,20)),
        xaxis=list(title="Chloride content %") )


fig_Cl <- subplot(fig_1,fig_2,nrows=1,titleY=TRUE,titleX=TRUE,margin=0.1)
  
# Update title
annotations = list( 
  list( 
    x = 0.2,  
    y = 1.0,  
    text = "Silica 75 mg/L",  
    xref = "paper",  
    yref = "paper",  
    xanchor = "center",  
    yanchor = "bottom",  
    showarrow = FALSE 
  ),  
  list( 
    x = 0.8,  
    y = 1,  
    text = "Silica 125 mg/L",  
    xref = "paper",  
    yref = "paper",  
    xanchor = "center",  
    yanchor = "bottom",  
    showarrow = FALSE 
  ),
  list( 
    x = 1.100009,  
    y = 1,  
    text = "pH",  
    xref = "paper",  
    yref = "paper",  
    xanchor = "center",  
    yanchor = "bottom",  
    showarrow = FALSE 
  ))

fig_Cl <- fig_Cl %>%layout(annotations = annotations) 


fig_Cl

#mere inspo
#https://plotly.com/r/subplots/

```

## Sulphate

```{R Plot af Sulphate subplots, echo=FALSE, message=FALSE}


fig_1 <- SPRR_data %>% filter(Stream=="Rejection",Silica_content=="75")%>%
  plot_ly(x=~Cl_ratio,
          y=~SO4,
          color =~pH,
          colors=c(colors[1],colors[2],colors[3]),
          type='scatter',mode='lines+markers',
          showlegend=FALSE) %>%
      layout(
        #title="silica, pH 9.25, silica 75 mg/L",
         yaxis=list(title="Rejection Sulphate",range=c(90,100)),
        xaxis=list(title="Chloride content %") )

fig_2 <- SPRR_data %>% filter(Stream=="Rejection",Silica_content=="125")%>%
  plot_ly(x=~Cl_ratio,
          y=~SO4,
          color =~pH,
          colors=c(colors[1],colors[2],colors[3]),
          type='scatter',mode='lines+markers') %>%
      layout(
        #title="silica, pH 9.25, silica 75 mg/L",
         yaxis=list(title="Rejection Sulphate",range=c(90,100)),
        xaxis=list(title="Chloride content %") )


fig_SO4 <- subplot(fig_1,fig_2,nrows=1,titleY=TRUE,titleX=TRUE,margin=0.1)
  
# Update title
annotations = list( 
  list( 
    x = 0.2,  
    y = 1.0,  
    text = "Silica 75 mg/L",  
    xref = "paper",  
    yref = "paper",  
    xanchor = "center",  
    yanchor = "bottom",  
    showarrow = FALSE 
  ),  
  list( 
    x = 0.8,  
    y = 1,  
    text = "Silica 125 mg/L",  
    xref = "paper",  
    yref = "paper",  
    xanchor = "center",  
    yanchor = "bottom",  
    showarrow = FALSE 
  ),
  list( 
    x = 1.100009,  
    y = 1,  
    text = "pH",  
    xref = "paper",  
    yref = "paper",  
    xanchor = "center",  
    yanchor = "bottom",  
    showarrow = FALSE 
  ))

fig_SO4 <- fig_SO4 %>%layout(annotations = annotations) 


fig_SO4

#mere inspo
#https://plotly.com/r/subplots/

```

## Bicarbonate

```{R Plot af Bicarbonate subplots, echo=FALSE, message=FALSE}


fig_1 <- SPRR_data %>% filter(Stream=="Rejection",Silica_content=="75")%>%
  plot_ly(x=~Cl_ratio,
          y=~HCO3,
          color =~pH,
          colors=c(colors[1],colors[2],colors[3]),
          type='scatter',mode='lines+markers',showlegend=FALSE) %>%
      layout(
        #title="silica, pH 9.25, silica 75 mg/L",
         yaxis=list(title="Rejection Bicarbonate",range=c(-10,100)),
        xaxis=list(title="Chloride content %") )

fig_2 <- SPRR_data %>% filter(Stream=="Rejection",Silica_content=="125")%>%
  plot_ly(x=~Cl_ratio,
          y=~HCO3,
          color =~pH,
          colors=c(colors[1],colors[2],colors[3]),
          type='scatter',mode='lines+markers') %>%
      layout(
        #title="silica, pH 9.25, silica 75 mg/L",
         yaxis=list(title="Rejection Bicarbonate",range=c(-10,100)),
        xaxis=list(title="Chloride content %") )


fig_HCO3 <- subplot(fig_1,fig_2,nrows=1,titleY=TRUE,titleX=TRUE,margin=0.1)
  
# Update title
annotations = list( 
  list( 
    x = 0.2,  
    y = 1.0,  
    text = "Silica 75 mg/L",  
    xref = "paper",  
    yref = "paper",  
    xanchor = "center",  
    yanchor = "bottom",  
    showarrow = FALSE 
  ),  
  list( 
    x = 0.8,  
    y = 1,  
    text = "Silica 125 mg/L",  
    xref = "paper",  
    yref = "paper",  
    xanchor = "center",  
    yanchor = "bottom",  
    showarrow = FALSE 
  ),
  list( 
    x = 1.100009,  
    y = 1,  
    text = "pH",  
    xref = "paper",  
    yref = "paper",  
    xanchor = "center",  
    yanchor = "bottom",  
    showarrow = FALSE 
  ))

fig_HCO3 <- fig_HCO3 %>%layout(annotations = annotations) 


fig_HCO3

#mere inspo
#https://plotly.com/r/subplots/

```

## ions in each experiment

```{R plot of ions experiment, eval=FALSE, message=FALSE, include=FALSE}


fig_5 <- SPRR_data %>% filter(Stream == "Rejection", Experiment_no=="5")%>%
  plot_ly(x=~c("Ca","Na","Cl","SO4","SiO2","HCO3"),
          y=~c(Ca,Na,Cl,SO4,SiO2,HCO3),
          type='scatter',mode='lines+markers') %>%
      layout(
        title="Experiment no. 5",
         yaxis=list(title="Rejection"),
        xaxis=list(title="Species") )
fig_5


fig_6 <- SPRR_data %>% filter(Stream == "Rejection", Experiment_no=="6")%>%
  plot_ly(x=~c("Ca","Na","Cl","SO4","SiO2","HCO3"),
          y=~c(Ca,Na,Cl,SO4,SiO2,HCO3),
          type='scatter',mode='lines+markers') %>%
      layout(
        title="Experiment no. 6",
         yaxis=list(title="Rejection"),
        xaxis=list(title="Species") )
fig_6

fig_8 <- SPRR_data %>% filter(Stream == "Rejection", Experiment_no=="8")%>%
  plot_ly(x=~c("Ca","Na","Cl","SO4","SiO2","HCO3"),
          y=~c(Ca,Na,Cl,SO4,SiO2,HCO3),
          type='scatter',mode='lines+markers') %>%
      layout(
        title="Experiment no. 8",
         yaxis=list(title="Rejection"),
        xaxis=list(title="Species") )
fig_8

fig_9 <- SPRR_data %>% filter(Stream == "Rejection", Experiment_no=="9")%>%
  plot_ly(x=~c("Ca","Na","Cl","SO4","SiO2","HCO3"),
          y=~c(Ca,Na,Cl,SO4,SiO2,HCO3),
          type='scatter',mode='lines+markers') %>%
      layout(
        title="Experiment no. 9",
         yaxis=list(title="Rejection"),
        xaxis=list(title="Species") )
fig_9

fig_12 <- SPRR_data %>% filter(Stream == "Rejection", Experiment_no=="12")%>%
  plot_ly(x=~c("Ca","Na","Cl","SO4","SiO2","HCO3"),
          y=~c(Ca,Na,Cl,SO4,SiO2,HCO3),
          type='scatter',mode='lines+markers') %>%
      layout(
        title="Experiment no. 12",
         yaxis=list(title="Rejection"),
        xaxis=list(title="Species") )
fig_12

fig_14 <- SPRR_data %>% filter(Stream == "Rejection", Experiment_no=="14")%>%
  plot_ly(x=~c("Ca","Na","Cl","SO4","SiO2","HCO3"),
          y=~c(Ca,Na,Cl,SO4,SiO2,HCO3),
          type='scatter',mode='lines+markers') %>%
      layout(
        title="Experiment no. 14",
         yaxis=list(title="Rejection"),
        xaxis=list(title="Species") )
fig_14

fig_15 <- SPRR_data %>% filter(Stream == "Rejection", Experiment_no=="15")%>%
  plot_ly(x=~c("Ca","Na","Cl","SO4","SiO2","HCO3"),
          y=~c(Ca,Na,Cl,SO4,SiO2,HCO3),
          type='scatter',mode='lines+markers') %>%
      layout(
        title="Experiment no. 15",
         yaxis=list(title="Rejection"),
        xaxis=list(title="Species") )
fig_15

fig_18 <- SPRR_data %>% filter(Stream == "Rejection", Experiment_no=="18")%>%
  plot_ly(x=~c("Ca","Na","Cl","SO4","SiO2","HCO3"),
          y=~c(Ca,Na,Cl,SO4,SiO2,HCO3),
          type='scatter',mode='lines+markers') %>%
      layout(
        title="Experiment no. 18",
         yaxis=list(title="Rejection"),
        xaxis=list(title="Species") )
fig_18



```


## noget med effect.

```{R 3D plot, echo=FALSE, message=FALSE}

SPRR_rejection <- (SPRR_data%>%filter(Stream == "Rejection"))

fig_1 <- SPRR_rejection%>%
  plot_ly(x=~Cl_ratio,
          y=~Silica_content,
          z=~SiO2,
          color =~pH)
fig_1 <- fig_1%>% add_lines()
fig_1


```