---
title: "stor_tabel"
author: "Lærke"
date: "27/5/2022"
output: 
  html_document:
    toc: true
    toc_depth: 3
editor_options: 
  markdown: 
    wrap: sentence
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,warning=F,message=F)
library(plyr)
library(dplyr)
library(tidyr)
library(ggplot2)
library(visdat)
library(GGally)
library(Hmisc)
library(DMwR2)
library(data.table)
library(mltools)
library(ggfortify)
library(ggiraphExtra)
library(coronavirus)
library(lubridate)
library(plotly)
#library(naniar)
library(readxl)
require(readr)
library(zoo)
library(latex2exp)
library(fs)
library(plyr)
library(matrixStats)
library(haven)
library(sjmisc)
require(gridExtra)
require(ggpubr)

colors = c(
  '#1f77b4',  # muted blue
  '#ff7f0e',  # safety orange
  '#2ca02c',  # cooked asparagus green
  '#d62728',  # brick red
  '#9467bd',  # muted purple
  '#8c564b',  # chestnut brown
  '#e377c2',  # raspberry yogurt pink
  '#7f7f7f',  # middle gray
  '#bcbd22',  # curry yellow-green
  '#17becf'   # blue-teal
)
```


```{r import af data rejection, echo=FALSE}

#multisalt: 
multi_salt_rejection = read.table(file='data/multi_salt_rejection.csv', header = T,sep = "\t",stringsAsFactors = T)
colnames(multi_salt_rejection)=c("Filtration","Time","Recovery","Species","Rejection","Std")
multi_salt_rejection$Type="Synthetic"
multi_salt_rejection$A_B="A"
multi_salt_rejection$System="Lab_scale"

#ICR:
ICR_rejection = read.table(file='data/ICR_rejection.csv', header = T,sep = "\t",stringsAsFactors = T)
colnames(ICR_rejection)=c("Filtration","Time","Recovery","Species","Rejection","Std")
ICR_rejection$Type="Synthetic"
ICR_rejection$A_B=c(rep("A",75),rep("B",4),rep("A",4),rep("B",4),rep("A",4),rep("B",4),rep("A",4),rep("B",4),rep("A",4),rep("B",4),rep("A",4))
ICR_rejection$System="Lab_scale"

#FCT:
FCT_rejection = read.table(file='data/FCT_rejection.csv', header = T,sep = "\t",stringsAsFactors = T)
colnames(FCT_rejection)=c("Filtration","Time","Recovery","Species","Rejection","Std")
FCT_rejection$Type="Authentic"
FCT_rejection$A_B=c(rep("A",4),rep("B",4),rep("A",4),rep("B",4),rep("A",4),rep("B",4),rep("A",4),rep("B",4),rep("A",4),rep("B",4),rep("A",5),rep("B",5),rep("A",5),rep("B",5))
FCT_rejection$System="Lab_scale"

#pilot:
Pilot_rejection = read.table(file='data/Pilot_rejection.csv', header = T,sep = "\t",stringsAsFactors = T)
colnames(Pilot_rejection)=c("Filtration","Time","Recovery","Species","Rejection","Std")
Pilot_rejection$Species=c(rep("Cl",11),rep("SO4",11),rep("Na",11),rep("Ca",11),rep("SiO2",11))
Pilot_rejection$Type="Authentic"
Pilot_rejection$A_B=c(rep("A",6),rep("B",5),rep("A",6),rep("B",5),rep("A",6),rep("B",5),rep("A",6),rep("B",5),rep("A",6),rep("B",5))
Pilot_rejection$System="Pilot_scale"

Rejection_data_samlet=rbind(multi_salt_rejection,ICR_rejection,FCT_rejection,Pilot_rejection)

Rejection_data_samlet%>%filter(Filtration=="ID:8A",Time==1)

```
```{r plot, echo=FALSE}

filtreringer=c('ID:1 - pH 9.3',
               "ID:2 - pH 10.1",
               "ID:3 - pH 10.5",
               "ID:4A - pH 9.8",
               "ID:5A - pH 9.8",
               "ID:6A - pH 9.8",
               "ID:7A - pH 9.7",
               "ID:8A - pH 9.8")

library(RColorBrewer)
#brewer.pal(n=5,"Set1")
colors3=c(    '#d62728',  # brick red
  '#9467bd',  # muted purple 
 '#ff7f0e',  # safety orange
 '#8c564b',  # chestnut brown
   '#e377c2',  # raspberry yogurt pink
  '#1f77b4',  # muted blue 
  '#2ca02c',  # cooked asparagus green
  '#17becf'   # blue-teal
 )
  
  
colors4=c('#F8766D', '#CD9600' ,'#7CAE00', '#00BE67','#00BFC4' ,'#00A9FF', '#C77CFF' ,'#FF61CC')
#)
#vi klipper lige alle B filtreringer af. 

Cl_authentic_synthetic_plot=Rejection_data_samlet%>%filter(Species=="Cl")%>%filter(A_B!="B")%>%
ggplot(aes(x=Recovery,y=Rejection,color=Filtration))+
  geom_point()+geom_line()+scale_color_manual(labels = filtreringer, values =colors4)+
 # scale_color_brewer(palette= "Spectral")+
  geom_hline(yintercept=0)+
    geom_errorbar(aes(x=Recovery,ymin=Rejection-(Rejection*Std), ymax=Rejection+(Rejection*Std),color=Filtration), width=1, position=position_dodge(0.05))+theme(legend.text.align=0)+
    facet_grid(cols=vars(Type),rows = vars(Species),scale="free")+
 # scale_y_continuous(limits=c(-60, 105), breaks=c(-60,-40,-20,0,20, 40,60,80,100 ))+
   scale_x_continuous(limits=c(0, 95), breaks=c(0,20, 40,60,80 ))+labs(x="Water Recovery [%]",y="Rejection [%]", color="Filtration")
Cl_authentic_synthetic_plot
ggplotly(Cl_authentic_synthetic_plot)

SIO2_authentic_synthetic_plot=Rejection_data_samlet%>%filter(Species=="SiO2")%>%filter(A_B!="B")%>%
ggplot(aes(x=Recovery,y=Rejection,color=Filtration))+
  geom_point()+geom_line()+scale_color_manual(labels = filtreringer, values =colors4)+
 # scale_color_brewer(palette= "Spectral")+
  geom_hline(yintercept=0)+
    geom_errorbar(aes(x=Recovery,ymin=Rejection-(Rejection*Std), ymax=Rejection+(Rejection*Std),color=Filtration), width=1, position=position_dodge(0.05))+theme(legend.text.align=0)+
    facet_grid(cols=vars(Type),rows = vars(Species),scale="free")+
  scale_y_continuous(limits=c(0, 100), breaks=c(0,20, 40,60,80,100 ))+
   scale_x_continuous(limits=c(0, 95), breaks=c(0,20, 40,60,80 ))+labs(x="Water Recovery [%]",y="Rejection [%]", color="Filtration")
SIO2_authentic_synthetic_plot
ggplotly(SIO2_authentic_synthetic_plot)


Rejection_data_samlet%>%filter(Species!="Cl",Species!="SiO2",Species!="Mg")%>%filter(A_B!="B")%>%
ggplot(aes(x=Recovery,y=Rejection,color=Filtration))+
  geom_point()+geom_line()+scale_color_manual(labels = filtreringer, values =colors4)+
 # scale_color_brewer(palette= "Spectral")+
  geom_hline(yintercept=0)+
    geom_errorbar(aes(x=Recovery,ymin=Rejection-(Rejection*Std), ymax=Rejection+(Rejection*Std),color=Filtration), width=1, position=position_dodge(0.05))+theme(legend.text.align=0)+
    facet_grid(cols=vars(Type),rows = vars(Species),scale="free")+
  scale_y_continuous(limits=c(0, 105), breaks=c(-60,-40,-20,0,20, 40,60,80,100 ))+
   scale_x_continuous(limits=c(0, 95), breaks=c(0,20, 40,60,80 ))+labs(x="Water Recovery [%]",y="Rejection [%]", color="Filtration")


Rejection_data_samlet%>%filter(Species=="Cl"|Species=="SiO2")%>%filter(Type=="Authentic")%>%
ggplot(aes(x=Recovery,y=Rejection,color=Filtration))+
  geom_point()+geom_line()+scale_color_manual(values =colors3)+
 # scale_color_brewer(palette= "Spectral")+
  geom_hline(yintercept=0)+
    geom_errorbar(aes(x=Recovery,ymin=Rejection-(Rejection*Std), ymax=Rejection+(Rejection*Std),color=Filtration), width=1, position=position_dodge(0.05))+theme(legend.text.align=0)+
    facet_grid(cols=vars(A_B),rows = vars(Species),scale="free")+
 # scale_y_continuous(limits=c(0, 100), breaks=c(0,20, 40,60,80,100 ))+
   scale_x_continuous(limits=c(0, 95), breaks=c(0,20, 40,60,80 ))+labs(x="Water Recovery [%]",y="Rejection [%]", color="Filtration")


Rejection_data_samlet%>%filter(Species=="Cl"|Species=="SiO2")%>%filter(A_B=="A")%>%filter(Type=="Authentic")%>%
ggplot(aes(x=Recovery,y=Rejection,color=Filtration))+
  geom_point()+geom_line()+scale_color_manual(values =colors3)+
 # scale_color_brewer(palette= "Spectral")+
  geom_hline(yintercept=0)+
    geom_errorbar(aes(x=Recovery,ymin=Rejection-(Rejection*Std), ymax=Rejection+(Rejection*Std),color=Filtration), width=1, position=position_dodge(0.05))+theme(legend.text.align=0)+
    facet_grid(cols=vars(System),rows = vars(Species),scale="free")+
 # scale_y_continuous(limits=c(-60, 105), breaks=c(-60,-40,-20,0,20, 40,60,80,100 ))+
   scale_x_continuous(limits=c(0, 95), breaks=c(0,20, 40,60,80 ))+labs(x="Water Recovery [%]",y="Rejection [%]", color="Filtration")



B_authentic_synthetic_plot=Rejection_data_samlet%>%filter(A_B=="B")%>%filter(Species!="Mg")%>%
ggplot(aes(x=Recovery,y=Rejection,color=Filtration))+
  geom_point()+geom_line()+#scale_color_manual(values =colors3)+
 # scale_color_brewer(palette= "Spectral")+
  geom_hline(yintercept=0)+
    geom_errorbar(aes(x=Recovery,ymin=Rejection-(Rejection*Std), ymax=Rejection+(Rejection*Std),color=Filtration), width=1, position=position_dodge(0.05))+theme(legend.text.align=0)+
    facet_grid(cols=vars(Species),scale="free")+
 # scale_y_continuous(limits=c(-60, 105), breaks=c(-60,-40,-20,0,20, 40,60,80,100 ))+
   scale_x_continuous(limits=c(0, 95), breaks=c(0,20, 40,60,80 ))+labs(x="Water Recovery [%]",y="Rejection [%]", color="Filtration")
B_authentic_synthetic_plot
ggplotly(B_authentic_synthetic_plot)


```



```{r import af data concentration, echo=FALSE}

#brug denne til export af tabels. 
#write.table(M9.2,file='data/M9.2_df.csv',col.names = T,row.names = F,sep="\t")


#brug denne til import: 
#SPRR = read.table(file='data/multi_salt_rejection', header = T,sep = "\t",stringsAsFactors = T)

#multisalt: 
multisalt_concentration = read.table(file='data/multisalt_concentration.csv', header = T,sep = "\t",stringsAsFactors = T)
multisalt_concentration$Mw=c(rep(35.45,39),rep(96.06,39),rep(40.078,39),rep(22.99,39),rep(60.08,43))
colnames(multisalt_concentration)=c("Filtration","Time","Stream","Recovery","Species","Concentration","Std","Plot","Mw")
multisalt_concentration$Type="Synthetic"
multisalt_concentration$System="Lab_scale"

#ICR:
ICR_concentration = read.table(file='data/ICR_concentration.csv', header = T,sep = "\t",stringsAsFactors = T)
ICR_concentration=ICR_concentration[,c(1:3,10,7,9,6,11,8)]
colnames(ICR_concentration)=c("Filtration","Time","Stream","Recovery","Species","Concentration","Std","Plot","Mw")
ICR_concentration$Type="Synthetic"
ICR_concentration$System="Lab_scale"

#FCT:
FCT_concentration = read.table(file='data/FCT_concentration.csv', header = T,sep = "\t",stringsAsFactors = T)
FCT_concentration=FCT_concentration[,c(1:3,10,4,5,6,11,7)]
colnames(FCT_concentration)=c("Filtration","Time","Stream","Recovery","Species","Concentration","Std","Plot","Mw")
FCT_concentration$Type="Authentic"
FCT_concentration$System="Lab_scale"
FCT_concentration$Concentration=FCT_concentration$Concentration/FCT_concentration$Mw

#pilot:
Pilot_concentration = read.table(file='data/Pilot_concentration.csv', header = T,sep = "\t",stringsAsFactors = T)
Pilot_concentration$Mw=c(rep(35.45,34),rep(96.06,34),rep(22.99,34),rep(40.078,34),rep(60.08,34))
Pilot_concentration$Plot=c(rep("Ca, Cl, SiO2, SO4",68),rep("Na",34),rep("Ca, Cl, SiO2, SO4",68))
colnames(Pilot_concentration)=c("Filtration","Time","Stream","Recovery","Species","Concentration","Std","Plot","Mw")

Pilot_concentration$Species=c(rep("Cl",34),rep("SO4",34),rep("Na",34),rep("Ca",34),rep("SiO2",34))
Pilot_concentration$Type="Authentic"
Pilot_concentration$System="Pilot_scale"

concentration_data_samlet=rbind(multisalt_concentration,ICR_concentration,FCT_concentration,Pilot_concentration)

concentration_data_samlet%>%filter(Filtration=="ID:8A",Time==1 , Stream=="Feed")

```
 Concentration of filtraiton A divided into cations and anions. 

```{r plot concentraiton, echo=FALSE}


concentration_Feed_plot=concentration_data_samlet%>%filter(Stream=="Feed")%>%filter(Species=="Cl"|Species=="SiO2"|Species=="SO4")%>%filter(Filtration!="ID:5B",Filtration!="ID:4B",Filtration!="ID:6B",Filtration!="ID:7B",Filtration!="ID:8B")%>%
ggplot(aes(x=Recovery,y=Concentration,color=Filtration))+
  geom_point()+geom_line()+#scale_color_manual(values =colors3)+
  #scale_color_brewer(palette= "Spectral")+
  geom_hline(yintercept=0)+
    geom_errorbar(aes(x=Recovery,ymin=Concentration-(Concentration*Std), ymax=Concentration+(Concentration*Std),color=Filtration), width=1, position=position_dodge(0.05))+theme(legend.text.align=0)+
    facet_grid(cols=vars(Type),rows = vars(Species),scale="free")+
 # scale_y_continuous(limits=c(-60, 105), breaks=c(-60,-40,-20,0,20, 40,60,80,100 ))+
   scale_x_continuous(limits=c(0, 90), breaks=c(0,20, 40,60,80 ))+labs(x="Water Recovery [%]",y="Concentration [%]", color="Filtration")
concentration_Feed_plot
ggplotly(concentration_Feed_plot)

Cation_concentration_Feed_plot=concentration_data_samlet%>%filter(Stream=="Feed")%>%filter(Species=="Ca"|Species=="Na")%>%
  filter(Filtration!="ID:5B",Filtration!="ID:4B",Filtration!="ID:6B",Filtration!="ID:7B",Filtration!="ID:8B")%>%
ggplot(aes(x=Recovery,y=Concentration,color=Filtration))+
  geom_point()+geom_line()+#scale_color_manual(values =colors3)+
  #scale_color_brewer(palette= "Spectral")+
  geom_hline(yintercept=0)+
    geom_errorbar(aes(x=Recovery,ymin=Concentration-(Concentration*Std), ymax=Concentration+(Concentration*Std),color=Filtration), width=1, position=position_dodge(0.05))+theme(legend.text.align=0)+
    facet_grid(cols=vars(Type),rows = vars(Species),scale="free")+
 # scale_y_continuous(limits=c(-60, 105), breaks=c(-60,-40,-20,0,20, 40,60,80,100 ))+
   scale_x_continuous(limits=c(0, 90), breaks=c(0,20, 40,60,80 ))+labs(x="Water Recovery [%]",y="Concentration [%]", color="Filtration")
Cation_concentration_Feed_plot
ggplotly(Cation_concentration_Feed_plot)

concentration_initial_plot=concentration_data_samlet%>%filter(Time==0,Stream=="Feed")%>%filter(Species=="Cl"|Species=="SiO2"|Species=="SO4")%>%filter(Filtration!="5B")%>%
ggplot(aes(x=Filtration, y=Concentration, fill=Species, )) +geom_bar(stat="identity",
  width = 0.5, position=position_dodge())+ labs(x="Species",y="Concentraiton mM")+
  #scale_y_continuous(limits=c(0, 20), breaks=c(0, 5,10,15,20 ))+
  #scale_x_continuous(limits=c(0, 95), breaks=c(20, 40,60,80 ))+
  ggtitle("ID:8A/8B")
concentration_initial_plot


```

```{r ikke bar plot, echo=FALSE}

#vi laver sejt plot til ICR: 

ICR_data=concentration_data_samlet%>%filter(Filtration=="ID:4A"|Filtration=="ID:4B")%>%filter(Stream!="Perm spand")
ICR_data$plads=c(rep("4A Feed",17),rep("4A Permeat",15),rep("4A Feed",17),rep("4A Permeat",15),rep("4A Feed",17),rep("4A Permeat",15),rep("4A Feed",17),rep("4A Permeat",15),rep("4A Feed",17),rep("4A Permeat",15),"4B Feed",
                 rep(c("4B Feed","4B Permeate"),4),"4B Feed",
                 rep(c("4B Feed","4B Permeate"),4),"4B Feed",
                 rep(c("4B Feed","4B Permeate"),4),"4B Feed",
                 rep(c("4B Feed","4B Permeate"),4),"4B Feed",
                 rep(c("4B Feed","4B Permeate"),4))


ioner=c(expression(Ca^{textstyle("2+")}),expression(Cl^{textstyle("-")}),expression(Na^{textstyle("+")}),expression(SiO[2]),expression(SO[4]^{textstyle("2-")}),expression(Mg^{textstyle("2+")}))
colors2=c( 
  '#d62728',  # brick red
  '#1f77b4',  # muted blue 
  '#2ca02c',  # cooked asparagus green
  '#9467bd',  # muted purple  
  '#ff7f0e',  # safety orange
 '#7f7f7f',  # middle gray
   '#8c564b',  # chestnut brown
  '#e377c2',  # raspberry yogurt pink
  
  '#bcbd22',  # curry yellow-green
  '#17becf'   # blue-teal
)


  ICR_data%>%
ggplot(aes(x=Recovery,y=Concentration,color=Species))+
  geom_point()+geom_line()+scale_color_manual(labels = ioner, values =colors2)+
  geom_hline(yintercept=0)+
    geom_errorbar(aes(x=Recovery,ymin=Concentration-(Concentration*Std), ymax=Concentration+(Concentration*Std),color=Species), width=1, position=position_dodge(0.05))+theme(legend.text.align=0)+
    facet_grid(cols=vars(plads),rows=vars(Plot),scale="free")+
 # scale_y_continuous(limits=c(-60, 105), breaks=c(-60,-40,-20,0,20, 40,60,80,100 ))+
   scale_x_continuous(limits=c(0, 90), breaks=c(0,20, 40,60,80 ))+labs(x="Water Recovery [%]",y="Concentration [%]", color="Species")
  
  ICR_data%>%
ggplot(aes(x=Recovery,y=Concentration,color=Species))+
  geom_point()+geom_line()+scale_color_manual(labels = ioner, values =colors2)+
  geom_hline(yintercept=0)+
    geom_errorbar(aes(x=Recovery,ymin=Concentration-(Concentration*Std), ymax=Concentration+(Concentration*Std),color=Species), width=1, position=position_dodge(0.05))+theme(legend.text.align=0)+
    facet_grid(cols=vars(plads),scale="free")+
 # scale_y_continuous(limits=c(-60, 105), breaks=c(-60,-40,-20,0,20, 40,60,80,100 ))+
   scale_x_continuous(limits=c(0, 90), breaks=c(0,20, 40,60,80 ))+labs(x="Water Recovery [%]",y="Concentration [%]", color="Species")


  
  #vi laver sejt plot til FCT: 

FCT_6A_data=concentration_data_samlet%>%filter(Filtration=="ID:6A"|Filtration=="ID:6B")%>%filter(Stream!="CT vand", Stream!="Perm spand")
FCT_6A_data$plads=c(rep(c("6A Feed","6A Feed","6A Permeate","6A Feed","6A Permeate",
                    "6B Feed","6B Feed","6B Permeate","6B Feed","6B Permeate"),5),rep("6A Feed",5),rep("6B Feed",5),rep("6A Permeate",5),rep("6B Permeate",5))
                        
FCT_7A_data=concentration_data_samlet%>%filter(Filtration=="ID:7A"|Filtration=="ID:7B")%>%filter(Stream!="CT vand", Stream!="Perm spand")
FCT_7A_data$plads=c(rep(c("7A Feed","7A Feed","7A Permeate","7A Feed","7A Permeate",
                    "7B Feed","7B Feed","7B Permeate","7B Feed","7B Permeate"),5),rep("7A Feed",5),rep("7B Feed",5),rep("7A Permeate",5),rep("7B Permeate",5))
                        
         FCT_6A_data%>%
ggplot(aes(x=Recovery,y=Concentration,color=Species))+
  geom_point()+geom_line()+scale_color_manual(labels = ioner, values =colors2)+
  geom_hline(yintercept=0)+
    geom_errorbar(aes(x=Recovery,ymin=Concentration-(Concentration*Std), ymax=Concentration+(Concentration*Std),color=Species), width=1, position=position_dodge(0.05))+theme(legend.text.align=0)+
    facet_grid(cols=vars(plads),rows=vars(Plot),scale="free")+
 # scale_y_continuous(limits=c(-60, 105), breaks=c(-60,-40,-20,0,20, 40,60,80,100 ))+
   scale_x_continuous(limits=c(0, 90), breaks=c(0,20, 40,60,80 ))+labs(x="Water Recovery [%]",y="Concentration [%]", color="Species")          

         
         FCT_7A_data%>%
ggplot(aes(x=Recovery,y=Concentration,color=Species))+
  geom_point()+geom_line()+scale_color_manual(labels = ioner, values =colors2)+
  geom_hline(yintercept=0)+
    geom_errorbar(aes(x=Recovery,ymin=Concentration-(Concentration*Std), ymax=Concentration+(Concentration*Std),color=Species), width=1, position=position_dodge(0.05))+theme(legend.text.align=0)+
    facet_grid(cols=vars(plads),rows=vars(Plot),scale="free")+
 # scale_y_continuous(limits=c(-60, 105), breaks=c(-60,-40,-20,0,20, 40,60,80,100 ))+
   scale_x_continuous(limits=c(0, 90), breaks=c(0,20, 40,60,80 ))+labs(x="Water Recovery [%]",y="Concentration [%]", color="Species")          
  
```



```{r MEGA dataframe}
Ion_data_frame = data.frame()
## SPRR data håndtering
SPRR = read.table(file='data/SPRR_df.csv', header = T,sep = "\t",stringsAsFactors = T)
SPRR_pH= c(NA,9.37,9.26,NA,9.26,9.35,NA,9.67,9.68,NA,9.56,9.66,NA,9.83,9.89,NA,9.81,9.87)
SPRR_con= c(NA,2350,1670,NA,2330,1680,NA,2440,1750,NA,2510,1760,NA,2450,1840,NA,2540,1830)
#SPRR_type=rep(c("SPRR"),each=18)
SPRR_names = c("SPRR_1","SPRR_2","SPRR_3","SPRR_4","SPRR_5","SPRR_6","SPRR_7","SPRR_8","SPRR_9","SPRR_10","SPRR_11","SPRR_12","SPRR_13","SPRR_14","SPRR_15","SPRR_16","SPRR_17","SPRR_18")


SPRR_wrangle = cbind(SPRR%>%filter(Stream == "Feed"),SPRR%>%filter(Stream == "Rejection")%>%select("Na","Ca","Cl","SO4","SiO2","HCO3"))
SPRR_wrangle$pH = SPRR_pH
SPRR_wrangle$con = SPRR_con
#SPRR_wrangle$type = SPRR_type


colnames(SPRR_wrangle) = c("name","Stream","Cl_ratio","SiO2_teo","pH","Ca","Na","Cl","SO4","SiO2_mgL","HCO3","Rej_Na","Rej_Ca","Rej_Cl","Rej_SO4","Rej_SiO2","Rej_HCO3","Conductivity")
SPRR_wrangle$name = SPRR_names
SPRR_clean = SPRR_wrangle%>%select(-c("Stream","SiO2_teo","HCO3","Rej_HCO3","Cl_ratio"))
SPRR_clean$state = "Steady State"
SPRR_clean$type = "SPRR"
SPRR_clean$pH[1]=9.33
SPRR_clean$time=NA
SPRR_clean$start_vol = NA

###multisalt håndtering
M_9.2 = read.table(file='data/M9.2_df.csv', header = T,sep = "\t",stringsAsFactors = T)
M_9.2_clean = M_9.2%>%select(-c("time","conductivity"))
M_9.2_clean$Conductivity = c(1560,1730,1880,2080,2390,2700)
M_9.2_clean$state = "Batch"
M_9.2_clean$type = "multi"
M_9.2_clean$name = c("M_9.2_3.5h","M_9.2_5h","M_9.2_6h","M_9.2_7h","M_9.2_8h","M_9.2_8.7h")
M_9.2_clean$time = c(3.5,5,6,7,8,8.7)
M_9.2_clean$start_vol = 10

M_10 = read.table(file='data/M10_df.csv', header = T,sep = "\t",stringsAsFactors = T)
M_10_clean = M_10%>%select(-c("time"))
M_10_clean$Conductivity = c(1830,2050,2350,2550,2830,3250)
M_10_clean$state = "Batch"
M_10_clean$type = "multi"
M_10_clean$pH = c(10.13,10.15,10.17,10.19,10.21,10.24)
M_10_clean$name = c("M_10_3h","M_10_4h","M_10_5h","M_10_5.5h","M_10_6h","M_10_6.5h")
M_10_clean$time = c(3,4,5,5.5,6,6.5)
M_10_clean$start_vol = 8.5

M_10.5 = read.table(file='data/M10.5_df.csv', header = T,sep = "\t",stringsAsFactors = T)
M_10.5_clean = M_10.5%>%select(-c("time"))
M_10.5_clean$Conductivity = c(2080,2390,2660,3020,3570,4470)
M_10.5_clean$state = "Batch"
M_10.5_clean$type = "multi"
M_10.5_clean$pH = c(10.5,10.52,10.54,10.56,10.59,10.63)
M_10.5_clean$name = c("M_10.5_2.5h","M_10.5_4h","M_10.5_5h","M_10.5_6h","M_10.7h","M_10.5_8h")
M_10.5_clean$time = c(2.5,4,5.5,6,7,8)
M_10.5_clean$start_vol = 10

### ICR data
ICR_1 = read.table(file='data/ICR_df.csv', header = T,sep = "\t",stringsAsFactors = T)
colnames(ICR_1) = c("name","SiO2_mgL","Na","Cl","SO4","Ca","pH","Rej_Cl","Rej_SO4","Rej_Na","Rej_Ca","Rej_SiO2","state")
ICR_clean = ICR_1
ICR_clean$Conductivity = c(2477,2517,2570,2625,2685,2740,2810,2881,2951,3040,3126,3221,3376,3568,4019)
SPRR_clean$Conductivity[1]=4210
ICR_clean$type = "ICR"
ICR_clean$time = c(20/60,40/60,60/60,80/60,100/60,2,140/60,160/60,3,200/60,220/60,240/60,270/60,300/60,360/60)
ICR_clean$start_vol = 10

###Sættes sammen
col_order <- c("name","Na","Cl","SO4","Ca","SiO2_mgL","pH","Rej_Cl","Rej_SO4","Rej_Na","Rej_Ca","Rej_SiO2","state","type","time","start_vol")
M_9.2_clean = M_9.2_clean[,col_order]
M_10_clean = M_10_clean[,col_order]
M_10.5_clean = M_10.5_clean[,col_order]
SPRR_clean = SPRR_clean[,col_order]
ICR_clean = ICR_clean[,col_order]

Ion_data_frame = rbind(M_9.2_clean,M_10_clean,M_10.5_clean,SPRR_clean,ICR_clean)
Ion_data_frame[1:18,8:12] = Ion_data_frame[1:18,8:12]*100
Mw_Cl=35.45
Mw_Na=22.99
Mw_Ca=40.078
Mw_SO4=96.06
Mw_SiO2=60.08
Ion_data_frame = Ion_data_frame%>%mutate("Na_mmol"=Na/Mw_Na)
Ion_data_frame = Ion_data_frame%>%mutate("Ca_mmol"=Ca/Mw_Ca)
Ion_data_frame = Ion_data_frame%>%mutate("Cl_mmol"=Cl/Mw_Cl)
Ion_data_frame = Ion_data_frame%>%mutate("SO4_mmol"=SO4/Mw_SO4)
Ion_data_frame = Ion_data_frame%>%mutate("SiO2_mmol"=SiO2_mgL/Mw_SiO2)




### noget med recovery
Ion_data_frame = Ion_data_frame%>%mutate("perm_vol"=time*1.02)
Ion_data_frame = Ion_data_frame%>%mutate("Recovery"=100*(1-(start_vol-perm_vol)/start_vol))








#Udtryk for ladning af silica som funk af pH, jeg kan ikkehuske hvor det kommer fra
a=1.00016
b=2.314233
c=9.831689
Ion_data_frame = Ion_data_frame%>%mutate(SiO2_ladet =  a/(1+exp(-b*(pH-c))))
#Ion_data_frame = Ion_data_frame%>%mutate(SiO2_ladet1=-0.0052*pH^5+0.2074*pH^4-3.2404*pH^3+24.84*pH^2-93.425*pH+137.74) #Gammelt udtryk for samme



Ion_data_frame = Ion_data_frame%>%mutate(Cl_SO4 = Cl_mmol/(Cl_mmol+SO4_mmol))
Ion_data_frame = Ion_data_frame%>%mutate(total_sio2_ladet=SiO2_mmol*SiO2_ladet)
Ion_data_frame = Ion_data_frame%>%mutate(anion_total = total_sio2_ladet+SO4_mmol+Cl_mmol)
Ion_data_frame = Ion_data_frame%>%mutate(Cl_anion = Cl_mmol/anion_total)

FCT_data=read.table(file='data/FCT_stor_tabel.csv',header= T,sep="\t")
pilot_data=read.table(file='data/pilot_stor_tabel.csv',header= T,sep="\t")
ICR_data=read.table(file='data/ICR_stor_tabel.csv',header= T,sep="\t")

Ion_data_frame = rbind(Ion_data_frame,FCT_data)
Ion_data_frame = rbind(Ion_data_frame,pilot_data)
Ion_data_frame = rbind(Ion_data_frame,ICR_data)

pH_FCT=c(9.77,9.92,9.65,9.78,8.28,8.5,8.87,8.89)
pH_pilot=c(9.86,9.81,9.85,9.92,10.03,10.15,8.84,8.87,8.92,9.0,9.12)
pH_ICR=c(7.9,7.88,7.91,7.92,9.81,9.82,9.85,9.89)

Ion_data_frame$pH[52:59]=pH_FCT
Ion_data_frame$pH[60:70]=pH_pilot
Ion_data_frame$pH[71:78]=pH_ICR


Ion_data_frame$name[37:51]="ID:4A"
Ion_data_frame$name[1:6]="ID:1"
Ion_data_frame$name[7:12]="ID:2"
Ion_data_frame$name[13:18]="ID:3"
Ion_data_frame$name[19:36]="SS"
Ion_data_frame$name[52:59]=c("ID:6A","ID:6A","ID:7A","ID:7A","ID:6B","ID:6B","ID:7B","ID:7B")



Ion_data_frame = Ion_data_frame%>%mutate(SiO2_ladet =  a/(1+exp(-b*(pH-c))))
Ion_data_frame = Ion_data_frame%>%mutate(Cl_SO4 = Cl_mmol/(Cl_mmol+SO4_mmol))
Ion_data_frame = Ion_data_frame%>%mutate(total_sio2_ladet=SiO2_mmol*SiO2_ladet)
Ion_data_frame = Ion_data_frame%>%mutate(anion_total = total_sio2_ladet+SO4_mmol+Cl_mmol)
Ion_data_frame = Ion_data_frame%>%mutate(Cl_anion = Cl_mmol/anion_total)


 Ion_data_frame%>%filter(name!="ID:4B",name!="ID:5B",name!="ID:6B",name!="ID:7B",name!="ID:8B")%>%
ggplot(aes(x=Cl_SO4,y=Rej_Cl,color=name))+
  geom_point()+geom_line()+#scale_color_manual(labels = ioner, values =colors2)+
  geom_hline(yintercept=0)+
   theme(legend.text.align=0)+
    facet_grid(cols=vars(type),scale="free")
 
 Ion_data_frame%>%filter(name!="ID:4B",name!="ID:5B",name!="ID:6B",name!="ID:7B",name!="ID:8B")%>%
ggplot(aes(x=Cl_anion,y=Rej_Cl,color=name))+
  geom_point()+geom_line()+#scale_color_manual(labels = ioner, values =colors2)+
  geom_hline(yintercept=0)+
   theme(legend.text.align=0)+
    facet_grid(cols=vars(type),scale="free")
 
  Ion_data_frame%>%filter(name!="ID:4B",name!="ID:5B",name!="ID:6B",name!="ID:7B",name!="ID:8B")%>%
ggplot(aes(x=SiO2_ladet/anion_total,y=Rej_SiO2,color=name))+
  geom_point()+geom_line()+#scale_color_manual(labels = ioner, values =colors2)+
  geom_hline(yintercept=0)+
   theme(legend.text.align=0)+
    facet_grid(cols=vars(type),scale="free")

  Ion_data_frame%>%filter(name!="ID:4B",name!="ID:5B",name!="ID:6B",name!="ID:7B",name!="ID:8B")%>%
ggplot(aes(x=SO4_mmol,y=Rej_SiO2,color=name))+
  geom_point()+geom_line()+#scale_color_manual(labels = ioner, values =colors2)+
  geom_hline(yintercept=0)+
   theme(legend.text.align=0)+
    facet_grid(cols=vars(type),scale="free")
  
```

```{r silica udtryk pH alt data, eval=FALSE, include=FALSE}
Ion_data_frame$name[Ion_data_frame$name == "SS"] <- "Single Pass"
## How well does the old line match?
ggplotly(ggplot(Ion_data_frame, aes(x=pH, y=Rej_SiO2,color=name))+geom_point())

ggplotly(ggplot(Ion_data_frame, aes(x=pH, y=Rej_SiO2,color=name))+geom_point()+geom_abline(intercept=-281.8,slope=32.493)+ylab("SiO2 Rejection [%]"))

linear_SPRR=readRDS("linear_SPRR.rds")
multiple_linear_SPRR=readRDS("multiple_linear_SPRR.rds")

plot(x=predict(linear_SPRR,newdata=Ion_data_frame%>%select(pH)), y=Ion_data_frame$Rej_SiO2,
     xlab='Predicted Values',
     ylab='Actual Values',
     main='pH',
     abline(a=0, b=1))

        
plot(x=predict(linear_SPRR,newdata=Ion_data_frame_A%>%select(pH)), y=Ion_data_frame_A$Rej_SiO2,
     xlab='Predicted Values',
     ylab='Actual Values',
     main='pH',
     abline(a=0, b=1))

model_fit=data.frame(actual=Ion_data_frame_A$Rej_SiO2,predicted=predict(linear_SPRR,newdata=Ion_data_frame_A%>%select(pH)))
model_fit=na.omit(model_fit)
old_RMSE=rmse(model_fit$actual,model_fit$predicted)

## How are new models?
fit_SiO2_pH = lm(Rej_SiO2~pH, data = Ion_data_frame)
ggplotRegression(fit_SiO2_pH)+ylab("SiO2 Rejection [%]")
summary(fit_SiO2_pH)
plot(x=predict(fit_SiO2_pH), y=na.omit(Ion_data_frame$Rej_SiO2),
     xlab='Predicted Values',
     ylab='Actual Values',
     main='pH',
     abline(a=0, b=1))

ggplotly(ggplot(Ion_data_frame, aes(x=pH, y=Rej_SiO2,color=name))+geom_point()+
           geom_abline(intercept=-281.8,slope=32.493)+
           geom_abline(intercept=fit_SiO2_pH$coefficients[1],slope=fit_SiO2_pH$coefficients[2],linetype="dashed")+
           ylab("SiO2 Rejection [%]"))

## What about B filtreringer?
Ion_data_frame_A=Ion_data_frame%>%filter(!name%in%c("ID:4B","ID:6B","ID:7B","ID:8B"))
fit_SiO2_low_pH = lm(Rej_SiO2~pH, data = Ion_data_frame%>%filter(name%in%c("ID:4B","ID:6B","ID:7B","ID:8B")))

test_low_pH=Ion_data_frame%>%filter(name%in%c("ID:4B","ID:6B","ID:7B","ID:8B"))
model_fit_low=data.frame(actual=test_low_pH$Rej_SiO2,predicted=predict(fit_SiO2_low_pH,newdata=test_low_pH%>%select(pH)))
model_fit_low=na.omit(model_fit_low)
low_RMSE=rmse(model_fit_low$actual,model_fit_low$predicted)


#det er det rigtige plot. 
ggplotly(ggplot(Ion_data_frame, aes(x=pH, y=Rej_SiO2,color=name))+geom_point()+geom_abline(intercept=-281.8,slope=32.493)+geom_abline(intercept=fit_SiO2_low_pH$coefficients[1],slope=fit_SiO2_low_pH$coefficients[2],linetype="dashed"))

#rmse(ex_model_fit$actual,ex_model_fit$predicted)

#Hmm looks like the low pH data does not fit so well, can we do some other models
ex_model = lm(log(Rej_SiO2)~ pH,data=Ion_data_frame)
summary(ex_model)
plot(x=exp(predict(ex_model,newdata=Ion_data_frame%>%select(pH))), y=Ion_data_frame$Rej_SiO2,
     xlab='Predicted Values',
     ylab='Actual Values',
     main='pH',
     abline(a=0, b=1))



Ion_data_frame$pH2=Ion_data_frame$pH^2
q_model=lm(Rej_SiO2~ pH+pH2,data=Ion_data_frame)
summary(q_model)
ydata=predict(q_model,newdata=Ion_data_frame%>%select(pH,pH2))

Ion_data_frame%>%
  ggplot(aes(x=pH,y=Rej_SiO2))+geom_point()+stat_smooth(method = "lm",formula = y~poly(x, 2))

Ion_data_frame%>%
  ggplot(aes(x=pH,y=Rej_SiO2))+geom_point()+stat_smooth(method = "lm",formula = y~exp(x))

### Just do linear regression on high pH
fit_SiO2_high_pH = lm(Rej_SiO2~pH, data =Ion_data_frame_A)
ggplotRegression(fit_SiO2_pH)+ylab("SiO2 Rejection [%]")
summary(fit_SiO2_high_pH)
plot(x=predict(fit_SiO2_pH), y=na.omit(Ion_data_frame_A$Rej_SiO2),
     xlab='Predicted Values',
     ylab='Actual Values',
     main='pH',
     abline(a=0, b=1))

ggplotly(ggplot(Ion_data_frame_A, aes(x=pH, y=Rej_SiO2,color=name))+geom_point()+
           geom_abline(intercept=-281.8,slope=32.493)+
           geom_abline(intercept=fit_SiO2_high_pH$coefficients[1],slope=fit_SiO2_high_pH$coefficients[2],linetype="dashed")+
           ylab("SiO2 Rejection [%]"))



new_model_fit=data.frame(actual=Ion_data_frame_A$Rej_SiO2,predicted=predict(fit_SiO2_pH,newdata=Ion_data_frame_A%>%select(pH)))
new_model_fit=na.omit(new_model_fit)
new_RMSE=rmse(new_model_fit$actual,new_model_fit$predicted)

print(data.frame(`old RMSE`=old_RMSE,`new RMSE`=new_RMSE,`difference[%]`=((old_RMSE-new_RMSE)/new_RMSE)*100))

ex_model_fit=data.frame(actual=Ion_data_frame$Rej_SiO2,predicted=exp(predict(ex_model,newdata=Ion_data_frame%>%select(pH))))
ex_model_fit=na.omit(ex_model_fit)
ex_RMSE=rmse(ex_model_fit$actual,ex_model_fit$predicted)
ex_RMSE
```


Nu med multiple regression
```{r silica pH OG koncentration alt date, eval=FALSE, include=FALSE}

## How well does the old line match?
ggplotly(ggplot(Ion_data_frame, aes(x=pH, y=Rej_SiO2,color=name))+geom_point()+geom_abline(intercept=-281.8,slope=32.493))


multiple_linear_SPRR=readRDS("multiple_linear_SPRR.rds")

plot(x=predict(multiple_linear_SPRR,newdata=Ion_data_frame%>%select(pH,SiO2_mmol)), y=Ion_data_frame$Rej_SiO2,
     xlab='Predicted Values',
     ylab='Actual Values',
     main='pH',
     abline(a=0, b=1))

#High pH area       
plot(x=predict(multiple_linear_SPRR,newdata=Ion_data_frame_A%>%select(pH,SiO2_mmol)), y=Ion_data_frame_A$Rej_SiO2,
     xlab='Predicted Values',
     ylab='Actual Values',
     main='pH',
     abline(a=0, b=1))

model_fit=data.frame(actual=Ion_data_frame_A$Rej_SiO2,predicted=predict(multiple_linear_SPRR,newdata=Ion_data_frame_A%>%select(pH,SiO2_mmol)))
model_fit=na.omit(model_fit)
old_RMSE=rmse(model_fit$actual,model_fit$predicted)

## How are new models?
fit_SiO2_pH_sio2 = lm(Rej_SiO2~pH+SiO2_mmol, data = Ion_data_frame)
summary(fit_SiO2_pH_sio2)
plot(x=predict(fit_SiO2_pH_sio2), y=na.omit(Ion_data_frame$Rej_SiO2),
     xlab='Predicted Values',
     ylab='Actual Values',
     main='pH',
     abline(a=0, b=1))

#Hmm looks like the low pH data does not fit so well, can we do some other model
ex_model = lm(log(Rej_SiO2)~ pH+SiO2_mmol,data=Ion_data_frame)
summary(ex_model)
plot(x=exp(predict(ex_model,newdata=Ion_data_frame%>%select(pH,SiO2_mmol))), y=Ion_data_frame$Rej_SiO2,
     xlab='Predicted Values',
     ylab='Actual Values',
     main='pH',
     abline(a=0, b=1))



### Just do linear regression on high pH
fit_SiO2_pH_sio2 = lm(Rej_SiO2~pH+SiO2_mmol, data = Ion_data_frame_A)
summary(fit_SiO2_pH_sio2)
plot(x=predict(fit_SiO2_pH_sio2), y=na.omit(Ion_data_frame_A$Rej_SiO2),
     xlab='Predicted Values',
     ylab='Actual Values',
     main='pH',
     abline(a=0, b=1))

new_model_fit=data.frame(actual=Ion_data_frame_A$Rej_SiO2,predicted=predict(fit_SiO2_pH_sio2,newdata=Ion_data_frame_A%>%select(pH,SiO2_mmol)))
new_model_fit=na.omit(new_model_fit)
new_RMSE=rmse(new_model_fit$actual,new_model_fit$predicted)

print(data.frame(`old RMSE`=old_RMSE,`new RMSE`=new_RMSE,`difference[%]`=((old_RMSE-new_RMSE)/new_RMSE)*100))

ex_model_fit=data.frame(actual=Ion_data_frame$Rej_SiO2,predicted=exp(predict(ex_model,newdata=Ion_data_frame%>%select(pH,SiO2_mmol))))
ex_model_fit=na.omit(ex_model_fit)
ex_RMSE=rmse(ex_model_fit$actual,ex_model_fit$predicted)
ex_RMSE
```
```{r Correlation matrix?, eval=FALSE, include=FALSE}
library(corrplot)
Ion_data_frame_var_SPRR=na.omit(Ion_data_frame%>%filter(type=="SPRR")%>%select(-c(state,type,name,Ca,pH2,Na,Cl,SO4,SiO2_ladet,Cl_anion,total_sio2_ladet,SiO2_mgL,time,start_vol,perm_vol,Recovery,anion_total)))

SPRR_cor=cor(Ion_data_frame_var_SPRR,method="pearson")

rcorr(as.matrix(Ion_data_frame_var_SPRR))


corrplot(SPRR_cor, type = "upper", order = "hclust", 
         tl.col = "black", tl.srt = 45)


col <- colorRampPalette(c("#BB4444", "#EE9988", "#FFFFFF", "#77AADD", "#4477AA"))

cor.mtest <- function(mat, ...) {
    mat <- as.matrix(mat)
    n <- ncol(mat)
    p.mat<- matrix(NA, n, n)
    diag(p.mat) <- 0
    for (i in 1:(n - 1)) {
        for (j in (i + 1):n) {
            tmp <- cor.test(mat[, i], mat[, j], ...)
            p.mat[i, j] <- p.mat[j, i] <- tmp$p.value
        }
    }
  colnames(p.mat) <- rownames(p.mat) <- colnames(mat)
  p.mat
}
# matrix of the p-value of the correlation
p.mat <- cor.mtest(Ion_data_frame_var_SPRR)

corrplot(SPRR_cor, method="color", col=col(200),  
         type="lower", order="hclust", 
         number.cex=0.75,#størrelse på coeff tal
         addCoef.col = "black", # Add coefficient of correlation
         tl.col="black", tl.srt=45, #Text label color and rotation
         # Combine with significance
         p.mat = p.mat, sig.level = 0.05, insig = "blank", 
         # hide correlation coefficient on the principal diagonal
         diag=FALSE 
         )
```


