---
title: "Membran og ion parameter"
author: "Steffen"
date: "18/3/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(plyr)
library(dplyr)
library(tidyr)
library(ggplot2)
library(visdat)
library(GGally)
library(Hmisc)
library(DMwR2)
library(data.table)
library(mltools)
library(ggfortify)
library(ggiraphExtra)
library(coronavirus)
library(lubridate)
library(plotly)
#library(naniar)
library(readxl)
require(readr)
library(zoo)
library(latex2exp)
library(fs)
library(plyr)
library(matrixStats)
library(haven)
library(sjmisc)
require(gridExtra)
require(ggpubr)

colors = c(
  '#1f77b4',  # muted blue
  '#ff7f0e',  # safety orange
  '#2ca02c',  # cooked asparagus green
  '#d62728',  # brick red
  '#9467bd',  # muted purple
  '#8c564b',  # chestnut brown
  '#e377c2',  # raspberry yogurt pink
  '#7f7f7f',  # middle gray
  '#bcbd22',  # curry yellow-green
  '#17becf'   # blue-teal
)
```


```{r cars}

ion_data = data.frame(
  ion = c("Na", "Cl", "SO4", "SiO2","Ca","HCO3"),
  Mw=c(22.99,35.45,96.06,60.08,40.078,61),
  molar_con = c(50.1, 76.4, 160, NA,119,NA),# Molær konduktivitet[S*cm^2*mol^-1]
 Stokes=c(1.84,1.21,2.3,1.81,3.1,NA)*0.1,#jeg har fundet på silica tal.
 Pauling=c(0.95,1.81,2.9,2.36,0.99,NA)*0.1,#jeg har fundet på silica tal.
 Hydrated=c(3.58,3.32,3.82,3.57,3.12,NA)*0.1,#jeg har fundet på silica tal.
 z=c(1,-1,-2,-1,2,-1)
)



```

```{r steric, echo=FALSE, message=FALSE, warning=FALSE}
radius_navne = c("Stokes","Pauling","Hydrated")

df_steric=data.frame( 
  rp=double(),
  Na=double(),
  Cl=double(),
  SO4=double(),
  SiO2=double(),
  Ca=double(),
  HCO3=double()
)
store_df_steric = data.frame()
for (j in 1:3) {
  radius=radius_navne[j]
  radii = ion_data%>%select(c(ion,radius))

for (i in 1:100) {
 rper = seq(0.5,1,0.005)
 rp= rper[i]
 
 
  steric=(1-(radii[,2]/rp))^2
  df_steric[i,2:7]=steric
  df_steric[i,1]=rp
}
store_df_steric = rbind(store_df_steric,df_steric %>%mutate(type = radius_navne[j]))
  }
steric.long = store_df_steric%>%filter(type=="Stokes") %>% 
  gather(key,value,Na,Cl,SO4,SiO2,Ca,HCO3)
level_order = c('Na','Cl','SO4','SiO2','Ca','HCO3')

ggplot(steric.long,aes(x=rp,y=value,color=factor(key,level=level_order)))+geom_line()+
  scale_color_brewer(palette="Set1",labels = level_order)+
  theme_bw()+labs(y = "Phi S", x = "rp [nm]", color = "Ion")




steric.long = store_df_steric%>%filter(type=="Pauling") %>% 
  gather(key,value,Na,Cl,SO4,SiO2,Ca,HCO3)
ggplot(steric.long,aes(x=rp,y=value,color=factor(key,level=level_order)))+geom_line()+
  scale_color_brewer(palette="Set1",labels = level_order)+
  theme_bw()+labs(y = "Phi S", x = "rp [nm]", color = "Ion")


steric.long = store_df_steric%>%filter(type=="Hydrated") %>% 
  gather(key,value,Na,Cl,SO4,SiO2,Ca,HCO3)
ggplot(steric.long,aes(x=rp,y=value,color=factor(key,level=level_order)))+geom_line()+
  scale_color_brewer(palette="Set1",labels = level_order)+
  theme_bw()+labs(y = "Phi S", x = "rp [nm]", color = "Ion")







```
```{r steric facet plot , echo=FALSE, message=FALSE, warning=FALSE}

ioner=c(expression(Ca^{textstyle("2+")}),expression(Cl^{textstyle("-")}),expression(Na^{textstyle("+")}),expression(SO[4]^{textstyle("2-")}))

steric.stokes = store_df_steric%>%filter(type=="Stokes") %>% 
  gather(key,value,Na,Cl,SO4,Ca)
#level_order = c('Na','Cl','SO4','SiO2','Ca','HCO3')

library(RColorBrewer)
my_palette = c(brewer.pal(9, "Set1")[c(1,2,3,5)])

colors2=c( 
  '#d62728',  # brick red
  '#1f77b4',  # muted blue 
  '#2ca02c',  # cooked asparagus green
  '#ff7f0e'  # safety orange
)

  
Steric_plot_stokes = ggplot(steric.stokes,aes(x=rp,y=value,color=key))+
  geom_line()+scale_color_manual(labels = ioner, values =colors2)+geom_hline(yintercept=0)+theme(legend.text.align=0)+
  scale_x_continuous(limits=c(0.5, 1), breaks=c(0.5, 0.6,0.7,0.8,0.9,1 ))+
  scale_y_continuous(limits=c(0, 1), breaks=c(0.2,0.4,0.6,0.8,1 ))+
    facet_grid(cols=vars(type))+labs(x="Radius Pore [nm]",y="Steric exclusion factor", color="Species")

Steric_plot_stokes

steric.pauling = store_df_steric%>%filter(type=="Pauling") %>% 
  gather(key,value,Na,Cl,SO4,Ca)

steric.hydrated = store_df_steric%>%filter(type=="Hydrated") %>% 
  gather(key,value,Na,Cl,SO4,Ca)

steric_noob=rbind(steric.pauling, steric.hydrated)

Steric_plot_noob = ggplot(steric_noob,aes(x=rp,y=value,color=key))+
  geom_line()+scale_color_manual(labels = ioner, values =colors2)+geom_hline(yintercept=0)+theme(legend.text.align=0)+
  scale_x_continuous(limits=c(0.5, 1), breaks=c(0.5, 0.6,0.7,0.8,0.9,1 ))+
  scale_y_continuous(limits=c(0, 1), breaks=c(0.2,0.4,0.6,0.8,1 ))+
    facet_grid(cols=vars(type))+labs(x="Radius Pore [nm]",y="Steric exclusion factor", color="Species")
Steric_plot_noob


steric_all=rbind(steric.stokes,steric.pauling, steric.hydrated)


Steric_plot_noob = ggplot(steric_all,aes(x=rp,y=value,color=key))+
  geom_line()+scale_color_manual(labels = ioner, values =colors2)+geom_hline(yintercept=0)+theme(legend.text.align=0)+
  scale_x_continuous(limits=c(0.5, 1), breaks=c(0.5, 0.6,0.7,0.8,0.9,1 ))+
  scale_y_continuous(limits=c(0, 1), breaks=c(0.2,0.4,0.6,0.8,1 ))+
    facet_grid(cols=vars(type))+labs(x="Radius Pore [nm]",y="Steric exclusion factor", color="Species")
Steric_plot_noob

```





```{r Dielectric exclusion}

radius_navne = c("Stokes","Pauling","Hydrated")
E_b = 78.4
E_la = 31
delta = 0.28 #nm
e = 1.602*10^-19 #C
E_0 = 8.85*10^-12 #F m^-1
k_B = 1.386*10^-23
Temp=25
Temp=Temp+273.15
  
  
df_DE=data.frame( 
  rp=double(),
  Na=double(),
  Cl=double(),
  SO4=double(),
  SiO2=double(),
  Ca=double(),
  HCO3=double()
)
store_df_DE = data.frame()
for (j in 1:3) {
  radius=radius_navne[j]
  ioner = ion_data%>%select(c(ion,radius,z))

for (i in 1:100) {
 rper = seq(0.5,1,0.005)
 rp= rper[i]
 
 


  E_p=E_la+(E_b-E_la)*(1-(delta/rp))^2
  dW = (ioner$z^2*e^2)/(8*pi*E_0*ioner[,2]*10^-9)*(1/E_p-1/E_b)
  phi_DE = exp(-dW/(k_B*Temp))
  
  df_DE[i,2:7]=phi_DE
  df_DE[i,1]=rp
}
store_df_DE = rbind(store_df_DE,df_DE %>%mutate(type = radius_navne[j]))
}



DE.long = store_df_DE %>% 
  gather(key,value,Na,Cl,SO4,Ca)
level_order = c('Na','Cl','SO4','Ca')

ggplot(DE.long%>%filter(type=="Stokes"),aes(x=rp,y=value,color=factor(key,level=level_order)))+geom_line()+
  scale_color_brewer(palette="Set1",labels = level_order)+
  theme_bw()+labs(y = "Phi DE", x = "rp [nm]", color = "Ion")

ggplot(DE.long%>%filter(type=="Pauling"),aes(x=rp,y=value,color=factor(key,level=level_order)))+geom_line()+
  scale_color_brewer(palette="Set1",labels = level_order)+
  theme_bw()+labs(y = "Phi DE", x = "rp [nm]", color = "Ion")

ggplot(DE.long%>%filter(type=="Hydrated"),aes(x=rp,y=value,color=factor(key,level=level_order)))+geom_line()+
  scale_color_brewer(palette="Set1",labels = level_order)+
  theme_bw()+labs(y = "Phi DE", x = "rp [nm]", color = "Ion")

```

```{r dielectric facet plot , echo=FALSE, message=FALSE, warning=FALSE}

ioner=c(expression(Ca^{textstyle("2+")}),expression(Cl^{textstyle("-")}),expression(Na^{textstyle("+")}),expression(SO[4]^{textstyle("2-")}))



library(RColorBrewer)
my_palette = c(brewer.pal(9, "Set1")[c(1,2,3,5)])

colors2=c( 
  '#d62728',  # brick red
  '#1f77b4',  # muted blue 
  '#2ca02c',  # cooked asparagus green
  '#ff7f0e'  # safety orange
)

  
Dielectric_plot_Alle = ggplot(DE.long,aes(x=rp,y=value,color=key))+
  geom_line()+scale_color_manual(labels = ioner, values =colors2)+geom_hline(yintercept=0)+theme(legend.text.align=0)+
  scale_x_continuous(limits=c(0.5, 1), breaks=c(0.5, 0.6,0.7,0.8,0.9,1 ))+
  scale_y_continuous(limits=c(0, 1), breaks=c(0.2,0.4,0.6,0.8,1 ))+
    facet_grid(cols=vars(type))+labs(x="Radius Pore [nm]",y="Dielectric exclusion factor", color="Species")

Dielectric_plot_Alle


Dielectric_plot_hydrated = ggplot(DE.long%>%filter(type=="Hydrated"),aes(x=rp,y=value,color=key))+
  geom_line()+scale_color_manual(labels = ioner, values =colors2)+geom_hline(yintercept=0)+theme(legend.text.align=0)+
  scale_x_continuous(limits=c(0.5, 1), breaks=c(0.5, 0.6,0.7,0.8,0.9,1 ))+
  scale_y_continuous(limits=c(0, 1), breaks=c(0.2,0.4,0.6,0.8,1 ))+
    facet_grid(cols=vars(type))+labs(x="Radius Pore [nm]",y="Steric exclusion factor", color="Species")

Dielectric_plot_hydrated


Dielectric_plot_Noob = ggplot(DE.long%>%filter(type!="Hydrated"),aes(x=rp,y=value,color=key))+
  geom_line()+scale_color_manual(labels = ioner, values =colors2)+geom_hline(yintercept=0)+theme(legend.text.align=0)+
  scale_x_continuous(limits=c(0.5, 1), breaks=c(0.5, 0.6,0.7,0.8,0.9,1 ))+
  scale_y_continuous(limits=c(0, 1), breaks=c(0.2,0.4,0.6,0.8,1 ))+
    facet_grid(cols=vars(type))+labs(x="Radius Pore [nm]",y="Dielectric exclusion factor", color="Species")

Dielectric_plot_Noob


ggplot(DE.long%>%filter(type=="Pauling",key=="Ca"),aes(x=rp,y=value,color=key))+
  geom_line()+scale_color_manual(labels = ioner, values =colors2)+geom_hline(yintercept=0)+theme(legend.text.align=0)+
  #scale_x_continuous(limits=c(0.5, 1), breaks=c(0.5, 0.6,0.7,0.8,0.9,1 ))+
  #scale_y_continuous(limits=c(0, 1), breaks=c(0.2,0.4,0.6,0.8,1 ))+
    facet_grid(cols=vars(type),scale="free")+labs(x="Radius Pore [nm]",y="Dielectric exclusion factor", color="Species")

```

```{r Noget med Silica , echo=FALSE, message=FALSE, warning=FALSE}

steric.S.stokes = store_df_steric%>%filter(type=="Stokes") %>% 
  gather(key,value,Na,Cl,SO4,Ca,SiO2)
steric.S.Pauling = store_df_steric%>%filter(type=="Pauling") %>% 
  gather(key,value,Na,Cl,SO4,Ca,SiO2)
steric.S.hydrated = store_df_steric%>%filter(type=="Hydrated") %>% 
  gather(key,value,Na,Cl,SO4,Ca,SiO2)


steric_m_silica=rbind(steric.S.stokes,steric.S.Pauling, steric.S.hydrated)

#level_order = c('Na','Cl','SO4','SiO2','Ca','HCO3')

ggplot(steric_m_silica,aes(x=rp,y=value,color=key))+
  geom_line()+#scale_color_manual(labels = ioner, values =colors2)+geom_hline(yintercept=0)+theme(legend.text.align=0)+
  scale_x_continuous(limits=c(0.5, 1), breaks=c(0.5, 0.6,0.7,0.8,0.9,1 ))+
  scale_y_continuous(limits=c(0, 1), breaks=c(0.2,0.4,0.6,0.8,1 ))+
    facet_grid(cols=vars(type))+labs(x="Radius Pore [nm]",y="Steric exclusion factor", color="Species")


DE.long.silica = store_df_DE %>% 
  gather(key,value,Na,Cl,SO4,Ca,SiO2)
#level_order = c('Na','Cl','SO4','Ca')

ggplot(DE.long.silica,aes(x=rp,y=value,color=key))+
  geom_line()+#scale_color_manual(labels = ioner, values =colors2)+geom_hline(yintercept=0)+theme(legend.text.align=0)+
  scale_x_continuous(limits=c(0.5, 1), breaks=c(0.5, 0.6,0.7,0.8,0.9,1 ))+
  scale_y_continuous(limits=c(0, 1), breaks=c(0.2,0.4,0.6,0.8,1 ))+
    facet_grid(cols=vars(type))+labs(x="Radius Pore [nm]",y="Steric exclusion factor", color="Species")


``` 
```{r bare stokes  , echo=FALSE, message=FALSE, warning=FALSE}

#steric.stokes

Dielectric.stokes=DE.long%>%filter(type=="Stokes")

steric.stokes$factor="Steric"

Dielectric.stokes$factor="Dielectric"

samlet_stokes=rbind(steric.stokes,Dielectric.stokes)


ggplot(samlet_stokes,aes(x=rp,y=value,color=key))+
  geom_line()+scale_color_manual(labels = ioner, values =colors2)+geom_hline(yintercept=0)+theme(legend.text.align=0)+
  scale_x_continuous(limits=c(0.5, 1), breaks=c(0.5, 0.6,0.7,0.8,0.9,1 ))+
  scale_y_continuous(limits=c(0, 1), breaks=c(0.2,0.4,0.6,0.8,1 ))+
    facet_grid(cols=vars(factor))+labs(x="Pore Radius [nm]",y="Exclusion Factor", color="Species")
```

